### ISSUE TITLE
Report export over secure network fail - Return to main map view

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar-web#1005]
On modern app, latest master:
When exporting a report while logged in over https just return to main map view
When changing back to http it works as expected.

**Comment by tananaev** [comment]
Maybe you're missing some headers? Compare the response.

**Comment by tananaev** [comment]
> Didn't make any changes to headers

Have you actually compared the headers? To make sure your proxy doesn't mess it up.

**Comment by tananaev** [comment]
Can you please compare the headers.

**Comment by tananaev** [comment]
This is missing with your HTTPS request:
```
Content-Disposition: attachment; filename=report.xlsx
```
Actually a lot of other stuff seems to be missing.
