### ISSUE TITLE
Replay on multiple vehicles

### ISSUE THREAD

**Issue by cop98** [traccar/traccar-web#1007]
The replay function of the modern interface, is possible with only one vehicle at a time. It would be nice to be able to select multiple vehicles (and a group) to see, for example, the day's trips of the entire fleet. (On the old interface it was possible with the route report).

**Comment by tananaev** [comment]
It's already implemented.

**Comment by cop98** [comment]
I don't see the option to select the group (I'm on demo2 server which I guess has 5.3)! Is there any setting?

![image](https://user-images.githubusercontent.com/49091679/183612536-c1813d88-bfbd-4a05-a9fc-e721181b2ee7.png)

**Comment by tananaev** [comment]
Route report. You can't select a group, but you can multiple vehicles.

**Comment by cop98** [comment]
In the route report, I cannot select more than one vehicle (in the summary, I can). However, even using that report I can't see the tracks on the map at the same time!

**Comment by tananaev** [comment]
> In the route report, I cannot select more than one vehicle

It means you're not using the latest version of Traccar. You should upgrade first.
