### ISSUE TITLE
Popup attributes that you can move

### ISSUE THREAD

**Issue by cop98** [traccar/traccar-web#1009]
The attribute popup now opens in the center of the map and cannot be moved.
It would be nice to make it moveable so that it is always open in a corner for example
(And maybe be able to resize it to make it smaller)

**Comment by tananaev** [comment]
It is already movable.

**Comment by cop98** [comment]
Excuse me, but how do you move? I can't move it!
I'm talking about the screen

![image](https://user-images.githubusercontent.com/49091679/183612090-16c4e367-37ee-4543-a49b-df9a236e1eaf.png)

**Comment by tananaev** [comment]
What version are you using? It should be draggable by the header.

**Comment by cop98** [comment]
I use the 5.2
I can't move it, see video

https://youtu.be/sZAqxP0e47E

**Comment by tananaev** [comment]
You have to upgrade first. In the future, before you claim that some doesn't work, please make sure you're using the latest release. It will save your time and our time.
