### ISSUE TITLE
Display attributes during replay.

### ISSUE THREAD

**Issue by ScaredyCat** [traccar/traccar-web#1010]
It would be good to be able to see specific details of a vehicle attributes point during replay. The information could be displayed in the same way as appears on the main map (see attached screenshot, floating window). The attributes displayed should update for each data point recorded and continue to be displayed if the replay is paused. 

Alternatively present a table at the bottom of the page that shows the attributes for each data point.

![replay1](https://user-images.githubusercontent.com/168872/183948619-f3032f42-7699-4e60-a1f4-fe3d1cf0ec5a.png)

**Comment by interduo** [comment]
+1 In old interface this was resolved in little different way. Now the UX is worse in that form.
Slider is also useful but checking the time of the point is main process in most cases.

**Comment by interduo** [comment]
@tananaev I don't think so:

look:
![image](https://user-images.githubusercontent.com/17087236/191988559-e8b46126-f242-4a5b-9624-82700ce8789b.png)

I would like to click on any point in the path and check (at least) the nearest avaiable timestamp. Now I need to use the slider from left to right. If the car is doing more kilometers to area its a little hard to use. Also showing some timestamps on the map would be useful - but this would complicate the map so I dont recommend this.

**Comment by tananaev** [comment]
Again, this is replay, not the route report. Legacy app didn't even have a replay.

**Comment by interduo** [comment]
But it had track marked on current map so looking from my side it was equal function

**Comment by tananaev** [comment]
Yeah, but why are you not comparing route reports, which exist on both versions and both have maps? It's just odd that you're comparing Apples to Oranges instead of comparing exactly the same feature in both apps.

**Comment by tananaev** [comment]
Implemented it here https://github.com/traccar/traccar-web/commit/d212a2897ec3c7f0cb7b4a4556e9147bb29a8aae.

**Comment by interduo** [comment]
@tananaev when do You plan next release of traccar? 
(I checked roadmap/readme and didn't find the information about releases cycles)

**Comment by tananaev** [comment]
There's no fixed release cycle, so we don't know yet.
