### ISSUE TITLE
[Feature Request] Modern Web App Search Devices by Contact

### ISSUE THREAD

**Issue by nitorplus** [traccar/traccar-web#1011]
**Is your feature request related to a problem? Please describe.**
On the old web interface, I could use the device 'search' box to lookup any information on a device and see the information easily in the sidebar. This was also customisable depending on what fields the end user had chosen to view, sort or filter by.  Old version could search by most columns, and we use 'contact' to display the driver name alongside the vehicle registration, makes looking up drivers very quick and easy. Could also quickly see a list of vehicles at any Geofence - EG a home / depot geofence. 

**Describe the solution you'd like**
I think it would be good to 'search devices' by contact, phone, or model etc.
Would also be helpful to display the contact’s name along with the tracking device name in the main window. (Poss. customise what fields show in the side panel)

**Describe alternatives you've considered**
A workaround in the modern web interface, would be to include the Name and contact in the same field, eg 'REG0 123 - ADAM', instead of just 'REG0 123' and then the contact name separately , only problem, is still cannot search by other fields, eg if i want to find an identifier to update, a number etc etc.  Also makes comparing data back in other systems difficult as the device name now does not match. 

**Additional context**

Current modern web interface work around example:
![image](https://user-images.githubusercontent.com/34402810/184141048-422644fc-92fa-4473-bf70-ee0e26d2dfc1.png)

Old web interface for reference example:
![image](https://user-images.githubusercontent.com/34402810/184142992-2a350df2-05dd-434b-b389-7b43cd8d0383.png)

**Comment by tananaev** [comment]
You can already search by the identifier.

Which specific fields are you really using for the search?

**Comment by nitorplus** [comment]
Mainly the "Contact" field and to display this in the same panel along with the name.
