### ISSUE TITLE
Device Groups not showing correctly

### ISSUE THREAD

**Issue by neilromig** [traccar/traccar-web#1020]
The "Groups" dropdown in the map "Search Devices" filter does not always show the users defined groups.

To reproduce, log in to Traccar as one user and check the groups shown. Log out and without reloading the page, log in as another user with a different set of groups. Check the groups shown.
If the second login has less groups assigned, the previous users extra groups are still showing. If the second login has more groups, then these are shown.

The Groups dropdown should always show the groups the current user has access to and no others.

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Firefox 103.0.2

I haven't explored it thoroughly yet, but it seems admin users may be affected differently - in particular, initial login does not show all groups the user has access to (see forum topic "device-group-not-showing").
I also don't have enough users with differing group assignments to test all possible scenarios.

**Comment by tananaev** [comment]
I wasn't able to reproduce the issue.

- Created two users A and B
- Created two groups 1 and 2
- Assigned both groups to user A
- Assigned group 1 to user B
- Login as user A and I see both groups
- Logout (no page refresh)
- Login as user B and I see only group 1

Everything seems to be correct.

**Comment by neilromig** [comment]
I can reproduce the scenario with my server consistently across Linux, Windows and Android platforms. Will you try using my tc_groups table as shown in forum post? One user with access to groups 1,6,9,10,11,11 and another with groups 1,9,10,11,12?

**Comment by tananaev** [comment]
Are you saying you can reproduce it with the same steps I did on a clean server?
