### ISSUE TITLE
Copy function of notifications or alerts

### ISSUE THREAD

**Issue by mirindao** [traccar/traccar-web#1023]
![CHECK](https://user-images.githubusercontent.com/109631800/188282309-d4ac98fa-3b01-4ae9-9135-279c9ef7a8f6.png)
this function will solution be assigning the notifications one by one to each device

![ALERTS2](https://user-images.githubusercontent.com/109631800/188281983-2db5e929-2fc5-4d86-892a-260d9ef843bf.png)

**Comment by tananaev** [comment]
Please change all your tickets to not be in ALL CAPS!

**Comment by mirindao** [comment]
ok

**Comment by mirindao** [comment]
Is there a way that notifications assigned to a user or multiple users.
the problem I have is when a user deletes the notifications all users are deleted.
The solution would be that if the user deletes his notifications, it will only be deleted for him, not for the others.

**Comment by tananaev** [comment]
You have to update all your tickets and comments to be not in all caps before we can discuss anything.

**Comment by mirindao** [comment]
i already changed the capital letters what do you think of the idea
