### ISSUE TITLE
change the geofence to be unlimited

### ISSUE THREAD

**Issue by mirindao** [traccar/traccar-web#1025]
greetings here I leave a link to download a geofence in gpx that gives me an error since it is a bit big
https://drive.google.com/drive/folders/158dkGZqprJ1bueNxd0zP5dhmeVR3GSE2?usp=sharing
![GEOCERCA](https://user-images.githubusercontent.com/109631800/188282692-944be5de-c37d-4455-be8f-f6e08ce34397.png)
when loading a large geofence it gives me this error that you see in the photo

**Comment by tananaev** [comment]
There's no plan to increase the default limit. Large geofences can cause performance problems. If you want you can always change the limit locally in your database. It doesn't require any code changes.

This has been discussed multiple times in the past, so I would recommend searching first to get full context.
