### ISSUE TITLE
Ignition On/Off issue

### ISSUE THREAD

**Issue by BIhab** [traccar/traccar-web#1034]
**Describe the bug**
Fire Ignition Off/On in the same time when device moving

**To Reproduce**
1. Go to 'notifications'
2. Create ignition on and ignition off notifications
3. Affect notification user

**Expected behavior**
Only show notification for ignition on when ignition is on for the first time and off when is off for the first time.

**Screenshot**
![IMG-20221008-WA0009.jpg](https://user-images.githubusercontent.com/33871976/194723313-e2116933-6cbc-40b9-bd95-b08b7a314d30.jpg)

**Comment by tananaev** [comment]
Please provide raw data (JSON or Excel report) and details on what events are missing (type and time).

**Comment by BIhab** [comment]
> 
Events: Ignition On & Ignition OFF
[report.xlsx](https://github.com/traccar/traccar-web/files/9740241/report.xlsx)

Trip: for the same vehicule
[report(1).xlsx](https://github.com/traccar/traccar-web/files/9740243/report.1.xlsx)

You can notice that the device is moving and the device handle ignition on & off every 3 seconds.

The event is handled for all the devices I have.

**Comment by tananaev** [comment]
Missing the raw data.

**Comment by BIhab** [comment]
> Missing the raw data.

Sorry, my bad, here it is.

[console-export-2022-10-8_22-25-33.txt](https://github.com/traccar/traccar-web/files/9740291/console-export-2022-10-8_22-25-33.txt)

**Comment by tananaev** [comment]
These are events. That's not the raw data.

**Comment by BIhab** [comment]
> These are events. That's not the raw data.

I made a quick search, is this config param still work: `database.saveOriginal` , if yes, I'll add it to the config file to store raw data and restart the server after some hours, if there is another way that I could use without restarting the server, please tell me.

**Comment by tananaev** [comment]
By raw data I meant positions. That contains original data as device reports it. Events are calculated on the server based on that data. That's why I'm asking for it.

**Comment by BIhab** [comment]
> By raw data I meant positions. That contains original data as device reports it. Events are calculated on the server based on that data. That's why I'm asking for it.

[tc_positions(1).csv](https://github.com/traccar/traccar-web/files/9740587/tc_positions.1.csv)

**Comment by tananaev** [comment]
Now it doesn't match the time of your event report.

**Comment by BIhab** [comment]
Hi Anton, under your guidance I found that it's not a bug, but the devices send the raw data with faulty data, hundreds of devices sadly, I thought about minimizing the risk of error, with adding an interval about 10 seconds, if no ignition true was sent during this interval it means that the ignition is off, if that interest you, I can create a pull request when It's done.
