### ISSUE TITLE
Why i am getting npm fund to pay

### ISSUE THREAD

**Issue by brohisoft** [traccar/traccar-web#1037]
**Is your feature request related to a problem? Please describe.**
I am first time using this source code and I am willing to test it on my computer, but when I installed it and I was getting npm fund to pay those people who haven't contributed, or maybe they had but I am not sure. So please let me know how I can use it without being a sponsor.

**Describe the solution you'd like**
I am willing to use this source without being a sponsor because I am not using it for any client or for business. it just for a interest

**Describe alternatives you've considered**

**Additional context**

**Comment by tananaev** [comment]
You don't have to pay anything to use Traccar or the source code.
