### ISSUE TITLE
Error when queuing a new, custom command - Latest master 

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar-web#1038]
**Describe the bug**
I get below error when sending a gprs command to a device that is currently offline.
```
Column 'description' cannot be null - SQLIntegrityConstraintViolationException (... < QueryBuilder:469 < DatabaseStorage:95 < CommandsManager:87 < ...)
```
**To Reproduce**
1. Select a device that is offline
2. Send new, custom command. Ive sent web_connect to one of my Teltonika devices (GPRS command)

**Comment by tananaev** [comment]
Fixed here https://github.com/traccar/traccar/commit/8f537de3bbf4dc1a742222dfd3123090b79e6419.
