### ISSUE TITLE
Main Devices panel missing the "close" button

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar-web#1039]
The "close" button disappeared from the main device panel after changes were made to latest master.
 
Before
![image](https://user-images.githubusercontent.com/63212232/196838201-57f7331e-ebd6-4ca8-b91c-3aaa2927541d.png)

After
![image](https://user-images.githubusercontent.com/63212232/196838254-676c175c-1312-4f72-8115-33cb9cd8994b.png)

**Comment by tananaev** [comment]
This is work in progress. We're removing that button.
