### ISSUE TITLE
resources/l10n is missing

### ISSUE THREAD

**Issue by brohisoft** [traccar/traccar-web#1040]
**Describe the bug**
I am using the traccar-web on my local computer to use it. I cloned it using git clone and then given the link, after that I used npm install, and then npm start. but I got several errors related to the resources/l10n directory.
for details, you can check the image. Would you please suggest to me how to use the Traccar-web in development mode on the windows machine? I have the react js environment prerequisites already.
![image](https://user-images.githubusercontent.com/21063130/196894496-999099c5-44ff-4ffd-9de4-5022f461c005.png)

**Comment by tananaev** [comment]
It's not a bug. It means you didn't checkout from GitHub correctly with symbolic links.

**Comment by brohisoft** [comment]
how to check them? i searched the resource folder it was not available in the modern folder where the actually traccar-web app is.

**Comment by brohisoft** [comment]
Sorry, I am asking you again, because I am immensely confused here. The traccar-web app is available in modern folder/directory which we can use for development mode right? And which file/directory is required it's available in main directory then web/l10n

**Comment by tananaev** [comment]
Yes, you can.

**Comment by brohisoft** [comment]
Thanks, i changed all directories all errors were resolved. But there is a technical error now. When I use npm start so it starts by default on port 3000, localhost:3000 and I get this Error occurred while trying to proxy: localhost:3000/api/server
but when I use localhost:8082 then I get this message Failed to fetch.
does it is due to the wrong port or something else? So please help me to resolve it

**Comment by tananaev** [comment]
Are you running the backend?

**Comment by brohisoft** [comment]
no, what should be in the backend?

**Comment by brohisoft** [comment]
well, I was thinking that maybe the Traccar Server setup that I installed is blocking the port. it was my mistake.
Okay, now I installed the Traccar server Setup again and its URL is: localhost:8082 the traccar-web app is also running and its URL is localhost:3000. I am sure it's funny for you, but I am now confused about what actually I am visiting the Traccar server which I installed by Setup file or I am on Traccar-web app, both are same as I registered as a new user and I am login by default on localhost:8082 
I am new to it, so please guide me thanks
