### ISSUE TITLE
Error when opening link from notification

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar-web#1044]
**Describe the bug**
On a copy of latest master with some modifications.
When opening the link from the email notification I get error "TypeError: Cannot read properties of undefined (reading 'type')".

**To Reproduce**
1. Create "Ignition On" notification and set channel to email.
2. Open the Point: link once you received the notification on email.

**Comment by tananaev** [comment]
Can you please provide a full stack trace or even better screenshot with the error.

**Comment by tananaev** [comment]
Are you able to run it in the debug mode?
