### ISSUE TITLE
The text field in device settings is blank

### ISSUE THREAD

**Issue by kjetilpp** [traccar/traccar-web#1045]
**Describe the bug**
The text field in device settings is blank

**To Reproduce**
1. Go to settings on a device
2. Click on Connections
3. Click on Notifications.
5. See error

**Expected behavior**
The text field to be filled without clicking on it. 

**Screenshots**

https://user-images.githubusercontent.com/5620578/200382090-f597a68b-07e5-4025-84d5-bada5d7a5936.mp4

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Chrome
 - Versjon 106.0.5249.119
 Traccar 4.5

**Comment by tananaev** [comment]
This is not a bug, but exactly expected behavior. We don't want to needlessly send 10+ expensive API requests to load all that data.
