### ISSUE TITLE
Undefined not processed

### ISSUE THREAD

**Issue by mryyg** [traccar/traccar-web#1049]
![image](https://user-images.githubusercontent.com/30715633/200982891-54bb942c-e437-49c3-a385-75e25e6b64b9.png)

Add Attribute - When the option has no corresponding language, options name is undefned

**Comment by tananaev** [comment]
Do you mean the localization is missing? That's expected.

**Comment by mryyg** [comment]
Yes, many Chinese do not.

**Comment by tananaev** [comment]
That's expected. We update non English localization just before the official release.

**Comment by mryyg** [comment]
ok,thanks
