### ISSUE TITLE
Search box for users, vehicles and error on location

### ISSUE THREAD

**Issue by track-ex-machina** [traccar/traccar-web#1056]
**Is your feature request related to a problem? Please describe.**
If I create to many users is difficult to reach them. This problem get more serious when I want to assiging a vehicle to a user.
If I create 500 vehicles, I had to search one by one the target vehigle to assiging it to a user.
Color of selection is very poor of units its very poor. I didnt understand if i had selected a unit or not. Even worste when i de-select a unit.
I noticed, also, that apliacation appear vehicles in the center of the Earth, more precisely at Atlantic ocean. Probably device sent packets with zero satellites.

**Describe the solution you'd like**
1. A search box on users, to find an user very quick
2. a search box on user properties when you want to assiging a vehicle or group of vehicles
3. Change the color when you select a unit on user propertaries.
4. no invalid location should display on map. The last position should appear or no satellite connection message/icon should appear.

**Describe alternatives you've considered**

**Additional context**
I mentioned, when I log out from a user, it doesnt send me back to previus user, but it sends me to log in page. So I have to log in again, scroll down, find again the user etc etc
Also, when you select a unit on list, then enter the properties of unit, and then click back (to get out from units properties), application send you to the top of list, so you have to scroll down again to find on what unit did you work.
Very annoying fuctions for something easy to fix

**Comment by tananaev** [comment]
1. You should have separate requests for each feature, but first make sure they are valid 
2. Zero coordinates filtering is already available. It seems like you haven't done you research before creating a ticket
3. Searching users and connections is also already available. Maybe you're not using a latest version or maybe you mean something else, but it needs to be clearly explained
