### ISSUE TITLE
Device title-filed on map marker

### ISSUE THREAD

**Issue by Kobrairaq** [traccar/traccar-web#1071]
when adding a new device with other lang such as Arabic or Hebrw  the title dose not show on top of marker only if it's in english

**Comment by tananaev** [comment]
Cyrillic works for me. I guess some languages are not supported by the map fonts for some reason.

**Comment by Kobrairaq** [comment]
> Cyrillic works for me. I guess some languages are not supported by the map fonts for some reason.

I just fixed it by changing the font in the core/mapUtil.js to Noto Sans Regular
