### ISSUE TITLE
MapView border

### ISSUE THREAD

**Issue by Kobrairaq** [traccar/traccar-web#1072]
When click on sidebar menu button for hiding it it's supposed to replace it's empty space with map so when it's hidden you cant drag the map from left side or interact with the map i tried to change sidebar menu from visibility: hidden to display: none and it's look's like that didn't work also

**Comment by tananaev** [comment]
Please provide a screen recording of the problem.

**Comment by Kobrairaq** [comment]
> Please provide a screen recording of the problem.

https://user-images.githubusercontent.com/56718017/212491489-06d4567a-37d2-4bc8-ae53-6767fba949a0.MOV

See how the mouse crusor cant interacts with the map inside this area y

**Comment by tananaev** [comment]
Fixed. Thanks for reporting it.
