### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'fixTime')

### ISSUE THREAD

**Issue by shift-tyson** [traccar/traccar-web#1078]
**Describe the bug**
When performing a 'last week' replay on a device, I was scrubbing through the timeline and when i got to the end it triggered this 

**TypeError: Cannot read properties of undefined (reading 'fixTime')**

![traccar_exception](https://user-images.githubusercontent.com/116026303/217049168-2a499fc2-e0fd-4f80-82a6-983ee525bb06.png)

**To Reproduce**
I was not able to consistently reproduce this error, but this is what I did
1. Load a long replay on a device
2. Scrub through it, to the end
3. See error

**Expected behavior**
Fail gracefully

**Desktop (please complete the following information):**
 - OS: AWS Amazon Linux
 - Browser: MS Edge
 - Version 109.0.1518.78 (Official build) (64-bit)

**Comment by shift-tyson** [comment]
5.5.0
Built from master branch about a week ago.

**Comment by tananaev** [comment]
Master is not guaranteed to be stable. Please only log tickets about official releases.
