### ISSUE TITLE
traccar 5.6 - impossible to create calculated attributes

### ISSUE THREAD

**Issue by cop98** [traccar/traccar-web#1079]
when creating a custom calculated attribute, the error in the screen is displayed.

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/49091679/217339767-11fafe4e-f3ee-43a6-a325-fbb5895e0901.png">

I also report abnormal operation of calculated attributes. It is not possible to use, for example, variables, constants, if

**Comment by tananaev** [comment]
You have not selected the attribute. You probably just typed it in. You have to select the value from the dropdown.

**Comment by cop98** [comment]
I have dozens of attributes calculated with the custom name! They have always been created without problems and work perfectly even now in 5.6
Why can't this be done since the last version?

<img width="1047" alt="Screenshot 2023-02-08 alle 07 52 12" src="https://user-images.githubusercontent.com/49091679/217455967-af22eeeb-f0d2-49fc-96a0-eefb95356e3f.png">

**Comment by tananaev** [comment]
You can still do it. You just need to select it in the pop-up.

**Comment by cop98** [comment]
There are only the default attributes in the list, though.
For example, if I wanted to recreate "Allarme inserito" (as you see about halfway down in the picture above) I can't do that, because it is not in the list

**Comment by tananaev** [comment]
You can type and custom name. Once it appears in the pop-up, you have to tap on it.

**Comment by cop98** [comment]
Thanks as always Anton, now I understand and indeed it works!
