### ISSUE TITLE
Server Force Settings not working properly

### ISSUE THREAD

**Issue by TecSeguridad** [traccar/traccar-web#1081]
When you create a new user and then check his account settigs there is two items that "Admin force settings" are not changing.

1- Speed Unit
2-Default Map

**Comment by tananaev** [comment]
Just tested the speed units and it is working correctly for me.

**Comment by TecSeguridad** [comment]
"Excuse me, Anton. Have you tested on a newly created 'normal' user? I forced the measurement unit to "km", but in the newly created user it shows as "knots"

**Comment by tananaev** [comment]
I have tested a new normal user on a clean server.
