### ISSUE TITLE
Option to expire or delete alerts from the main device list.

### ISSUE THREAD

**Issue by TecSeguridad** [traccar/traccar-web#1082]
Option that allows deleting an alert from the device list once it has been resolved, as in the case of an SOS or powercut.

Let's remember that the main purpose of the platform is vehicle monitoring. In a practical scenario, especially with many vehicles on the screen, it can be confusing for an operator who is monitoring device activity to see alerts that happened days ago.

In conclusion, it would be ideal for the operator to be able to delete that alert once the problem has been resolved and focus on something else.
![Captura](https://user-images.githubusercontent.com/22125646/220752273-118fd490-2fb7-475a-87b7-550d13c86fc7.JPG)

**Comment by tananaev** [comment]
It seems like it would somewhat duplicate the "events" panel. Can you please explain why you don't use that panel instead.

**Comment by TecSeguridad** [comment]
Honestly, I hadn't thought about the events panel, but I have a question. Are the events in the panel only temporary? I mean, if an SOS event is triggered before I open the browser, wouldn't I be able to see it or mark it as solved anymore?

**Comment by tananaev** [comment]
> Are the events in the panel only temporary?

Currently events there are temporary, but there are other requests to make them not temporary.

> Also, we only have the option to delete everything and not each device that triggers an event.

This is not correct. You can clear each event separately.

**Comment by TecSeguridad** [comment]
I retract that each event can be cleaned separately, my mistake.
