### ISSUE TITLE
UI: Disable Vehicle Features 

### ISSUE THREAD

**Issue by hamilton82** [traccar/traccar-web#1085]
Greetings, in previous versions you could use UI: Disable Vehicle Features to hide the devices tab so that users could not see the imei or phone numbers, in the latest version this option does not cover said tab

**Comment by tananaev** [comment]
Are you sure? How's IMEI and phone number related specifically to vehicles?

**Comment by hamilton82** [comment]
https://ibb.co/MpVLD7b

https://ibb.co/SrPfm12

both with 5.6 and the ttps://github.com/traccar/traccar-web.git downloaded only to change the logo color and details like favicon (nice detail placing the connections and others in the users and devices tabs)

**Comment by tananaev** [comment]
Old version didn't have a separate devices page at all. It has nothing to do with "UI: Disable Vehicle Features".

Also I'm not sure if you realize that, but you can actually see the id on the main screen.

**Comment by hamilton82** [comment]
both versions are 5.6, the difference is the traccar-web.git, the last one downloaded yesterday without that, (full traccar base) you can hide that tab from users with that attribute on the server. but with git, which is noticeably modified by the new options at the end even when you don't modify it and only compile it, that option doesn't hide said tab, the idea of ​​hiding it seemed attractive so that users who can't see neither the imei nor the phone number assigned to the vehicle

**Comment by hamilton82** [comment]
both versions are 5.6, the difference is the traccar-web.git, the last one downloaded yesterday without that, (full traccar base) you can hide that tab from users with that attribute on the server. but with git, which is noticeably modified by the new options at the end even when you don't modify it and only compile it, that option doesn't hide said tab, the idea of ​​hiding it seemed attractive so that users who can't easy see neither the imei nor the phone number assigned to the vehicle

**Comment by tananaev** [comment]
There's only one version 5.6. If you're using a custom build from the source code, please don't call it 5.6. You have to refer to specific revision you're using.

**Comment by hamilton82** [comment]
What version do I download when using wget ttps://github.com/traccar/traccar-web.git? Or how do I know the version of that area? I refer to it as 5.6 since when compiling it in info it tells me app version 5.6, if I'm wrong about it, I'm sorry, I wouldn't know what to call it

**Comment by tananaev** [comment]
`wget ttps://github.com/traccar/traccar-web.git` does not download any app.

**Comment by hamilton82** [comment]
my mistake

git clone https://github.com/traccar/traccar-web.git

**Comment by tananaev** [comment]
That's the master branch that we keep updating all the time with new changes.

I'm going to close this ticket because it does not make sense to me as it is. "UI: Disable Vehicle Features" option has nothing to do with device list. That's not what it's for.
