### ISSUE TITLE
Login Popup Come

### ISSUE THREAD

**Issue by kalp2525** [traccar/traccar-web#1089]
**Describe the bug**
I implemented this traccar API in my website so there was one popup coming when I entered first time in browser.

**Screenshots**
This popup comes when start my web-app.
![image](https://user-images.githubusercontent.com/122508708/227183651-09e69c02-e854-402a-a452-f074edb7e22f.png)

Here in API's session and server API called but there was token API status was pending.
![image](https://user-images.githubusercontent.com/122508708/227183702-6fd74b75-089e-4ec2-a2c4-c894453d1dcc.png)

When I give username and password and then press signin button on popup then traccar API working fine. But when I press cancel button of popup then token and all other API cancelled and `HTTP 401 Unauthorized-WebApplicationException(SecurityRequestFilter: 126<...)` this error gives by all the cancelled API's.

So Please gives me suggestion how I will fix it.

**Comment by tananaev** [comment]
Please use the forum for questions.
