### ISSUE TITLE
Add button obstruct last listed record

### ISSUE THREAD

**Issue by TecSeguridad** [traccar/traccar-web#1091]
The add button on the screens of devices and users is obstructing the last record on the list. In which part of the code can I change its position? I'm thinking that raising it to 75px would solve the problem since it would allow it to be moved for editing.

Thanks

![image](https://user-images.githubusercontent.com/22125646/227985887-da2e0b9a-7645-4296-bf5e-3988f0fb8ee2.png)

**Comment by tananaev** [comment]
Check `CollectionFab`.

**Comment by TecSeguridad** [comment]
> Check `CollectionFab`.

Thank you Anton

**Comment by gustavofcalmeida** [comment]
Is this going to be fixed in official repository?
It happens with notifications screen too. And also on desktop browser.

![001](https://user-images.githubusercontent.com/11458901/232883591-f564c73b-23de-4f77-9829-b2072b8ae17f.png)

**Comment by tananaev** [comment]
Feel free to create a ticket for it.
