### ISSUE TITLE
Possible to create unnamed geofence in modern app

### ISSUE THREAD

**Issue by gustavofcalmeida** [traccar/traccar-web#1102]
**Describe the bug**
One can easily create geofences with no name that cause trouble to link to devices.

**To Reproduce**
1. finish your polygon
2. leave the name field blank
3. press cancel

OR

1. finish your polygon
2. type a name
3. press cancel

**Expected behavior**
By hitting cancel, the creation should be aborted. Instead you get a fence without name, no matter you type a name or not.

**Screenshots**
![001](https://user-images.githubusercontent.com/11458901/232860628-795779c2-5995-419f-a708-970e7cb1d449.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20
 - Browser Updated Chrome

**Additional context**
The no name fence means trouble when you try to list fences to link to a device, because the emptiness of name makes the height of the item very small.
![002](https://user-images.githubusercontent.com/11458901/232860717-1218f263-1170-4884-ba3b-b7619045ba55.png)

**Comment by tananaev** [comment]
I think one easy solution is to assign a default name, like "New Geofence" or something like that.
