### ISSUE TITLE
It is not possible to save the resources (geofences, notifications, drivers, computed attributes, saved commands, maintenance) assigned to devices

### ISSUE THREAD

**Issue by Turbovix** [traccar/traccar-web#1104]
It is not possible to save the resources (geofences, notifications, drivers, computed attributes, saved commands, maintenance) assigned to devices in CONNECTIONS. After making the settings, there is no save button.

Problem reproduction:
1. Go to Settings
2. Click on devices
3. click on the first icon before the pencil
4. release the resources for the device in question
5. No way to save changes

**Comment by tananaev** [comment]
It is saved automatically. You don't need any save button. It always worked like that.

**Comment by Turbovix** [comment]
Really saved without having to click anywhere. And the saved resources are only visible if you click on the resource field in question.
Thank you and I'm sorry.
