### ISSUE TITLE
mobile name error

### ISSUE THREAD

**Issue by carlock2022** [traccar/traccar-web#1106]
in mobile the devices tab has the name DRIVERS

![2](https://user-images.githubusercontent.com/114795834/233559877-5f0a14db-a0e0-4fab-b2ca-caab8d18aba5.jpg)
![1](https://user-images.githubusercontent.com/114795834/233559917-38eeff8f-9c9a-4bf9-8a6d-1deaf1fc8c33.jpg)

**Comment by tananaev** [comment]
Fixed, thanks for reporting it.
