### ISSUE TITLE
Feature request - share location of a vehicule

### ISSUE THREAD

**Issue by Ykrm** [traccar/traccar-web#1118]
Hello,

I would suggest to add an option on the map screen to share location of a vehicule like this : 

https://ibb.co/3fmLNRy

You can use email to share location : 
https://ibb.co/xhVKQ7f

Or just using an other app like whatsapp or telegram etc 
https://ibb.co/PjzwZ1c

This feature is very useful and will be simething new in traccar.

Thank you.

**Comment by jsnxptech** [comment]
também concordo!
