### ISSUE TITLE
Disable Bolean "Send SMS" in command windows

### ISSUE THREAD

**Issue by TecSeguridad** [traccar/traccar-web#1126]
A way to disable the accent mark when sending SMS in the command window? I suppose it would be good if it's not enabled when the SMS system is not configured. I've noticed that users instinctively use the accent mark and then complain that the commands don't work.

**Comment by ligenzasantiago** [comment]
es buena idea, no hay forma de hacerlo actualmente pero se puede implementar bastante rapido

**Comment by TecSeguridad** [comment]
Thank you
