### ISSUE TITLE
Feature request - Dark mode

### ISSUE THREAD

**Issue by Ykrm** [traccar/traccar-web#1129]
Hello,

I highly suggest to add dark mode option on the mobile App (traccar manager) for good UX

Thanks

**Comment by priddhesh** [comment]
Are you asking for web app or mobile app?

**Comment by Ykrm** [comment]
Hello, 

I think it should be added on the web app since the mobile app is based on the configuration of web interface

**Comment by smessou** [comment]
@Ykrm I think so too
