### ISSUE TITLE
No save button on editing user connections

### ISSUE THREAD

**Issue by nitorplus** [traccar/traccar-web#1132]
**Describe the bug**
Can't save user connection details such as add a device as an administrator user. Don't see any error messages in the console. 

**To Reproduce**
Fresh install of traccar on ubuntu

**Expected behavior**
Should there not be a save button? 

**Screenshots**
If applicable, add screenshots to help explain your problem.![Screenshot_20230607_194752_Chrome.jpg](https://github.com/traccar/traccar-web/assets/34402810/ab050a30-78a0-4db6-aaa2-959175836d11)

![Screenshot_20230607_194814_Chrome.jpg](https://github.com/traccar/traccar-web/assets/34402810/5b364be8-9450-47c9-8477-752693fa25b1)

**Comment by tananaev** [comment]
There's no save button. It's applied when you click.
