### ISSUE TITLE
Notification Channel Issue

### ISSUE THREAD

**Issue by TecSeguridad** [traccar/traccar-web#1134]
Hello Anton can you please help me? The error occurs in the notification of "the device exits the geofence." The notification is not sent through the Web and Telegram channels; however, it is sent via email. I performed several tests on two different servers, and the same issue occurs. It is only a problem with the notification because if I check the reports, I can see the geofence exit alerts.

Traccar V5.7

**Comment by tananaev** [comment]
First of all, we would only accept a bug against the latest version of Traccar.

Secondly, you have to provide evidence that there is a bug. If you're not able to do so, you have to use the forum instead.

And either way you have provide much more details.

**Comment by TecSeguridad** [comment]
First, I apologize for the inconvenience caused by my post, and now I understand that you only accept bugs regarding the latest version. I will keep that in mind going forward and will update accordingly. My intention is not to make a complaint but to contribute by reporting an error that I am experiencing. I always search for information in the forum before using this platform. I will try to reproduce the error in a fresh installation and on the same demo servers to gather more details. Thank you.

**Comment by tananaev** [comment]
OK, we'll close the ticket for now then until the information is provided.
