### ISSUE TITLE
Problem with the color attribute fields in the server section > version 5.8

### ISSUE THREAD

**Issue by coviedo** [traccar/traccar-web#1136]
The attribute primary color and secondary color are of type string
However if you put something other than an html color value
the app explodes.

<img width="1110" alt="Captura de Pantalla 2023-06-16 a la(s) 7 02 03 a  m" src="https://github.com/traccar/traccar-web/assets/2223503/dcde8682-3bcd-48b1-a0df-fd87e9cc3065">

**Comment by tananaev** [comment]
What do you propose?

**Comment by tananaev** [comment]
Obviously it could, but we need to balance development effort here. This is something **admin configures** and it's usually done only **once**. I'm happy to keep it open, but seems very unlikely to get prioritized.

**Comment by jinzo** [comment]
So I guess this can be closed? https://github.com/traccar/traccar-web/commit/5f0fb3d0346acca3796b129e304251d8060bff42

**Comment by tananaev** [comment]
Yes, I think so.
