### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by miguelGerez** [traccar/traccar-web#1139]
**Describe the bug**

When I access "Devices," I encounter the following error:

TypeError: Cannot read properties of undefined (reading 'fixTime')

**To Reproduce**
1. Go to 'Setting'
2. Click on 'Devices'
3. See error

**Screenshots**
![img1](https://github.com/traccar/traccar-web/assets/51457754/03630c30-d1ce-4b40-b63d-d7c1e251202d)
![img2](https://github.com/traccar/traccar-web/assets/51457754/b6675ff1-4efd-47b6-8634-9e6cefaeb0a2)

**Desktop:**
 - OS: [Windows 11]
 - Browser [chrome, edge]

**Traccar:**
 -Version: 5.8

**Comment by tananaev** [comment]
This has already been fixed in cd5b1513be814f27dcb6196779af772d9fdf656f.
