### ISSUE TITLE
popup screen too big

### ISSUE THREAD

**Issue by cop98** [traccar/traccar-web#1146]
If you enable too many attributes in the popup window, it becomes very long and on small screens such as that of a phone it protrudes outside not allowing proper movement and display.
It would be nice to add a scroll bar when you exceed tot rows displayed

![Screenshot_20230705-092109](https://github.com/traccar/traccar-web/assets/49091679/4b7a9f2c-32f0-4c75-96b9-aab2e70af7a4)

**Comment by jinzo** [comment]
PR https://github.com/traccar/traccar-web/pull/1155 fixes this too from what I can see?
