### ISSUE TITLE
Chart type Traccar 5.8

### ISSUE THREAD

**Issue by Cris3021** [traccar/traccar-web#1147]
In version 5.8 the graph report includes custom attributes, but the attribute is not configurable, which may mean that an ordinary user does not understand it. For example a teltonika device may display the attribute io251 and not know what it is.

![Tipo grafico 1](https://github.com/traccar/traccar-web/assets/32416242/2edadcac-a064-4eec-a3e4-edb0b6340e0c)

You could implement that if the attribute is not in **usePositionAttributes** it could be configurable.

this was the change in 5.8
https://github.com/traccar/traccar-web/commit/b756ef71c34dbfb5caa8a908ff890afc168fda3d

**Comment by jinzo** [comment]
You can use [Computed Attributes](https://www.traccar.org/computed-attributes/) to "map" the io* values to something that is user understandable (or update the decoders in the code and submit a pull request).
