### ISSUE TITLE
Chart Reports X Axis is not time linear

### ISSUE THREAD

**Issue by nikoroxy** [traccar/traccar-web#1167]
**Describe the bug**
Time-related records are not correctly shown into charts, as they are merged without taking into account distance between timestamps.

**To Reproduce**
1. Go to Reports
2. Click on Chart
3. Set desired attribute and time span 
4. See bad formatting

**Screenshots**
![immagine](https://github.com/traccar/traccar-web/assets/16979271/0b9113da-9a2e-4cc4-81a9-0e683c81d07c)

**References**
[Here](https://github.com/recharts/recharts/issues/956#issuecomment-1476801215) there are some useful tips

**Comment by tananaev** [comment]
Fixed, thanks for reporting.
