### ISSUE TITLE
 Feature request: Exporting device list

### ISSUE THREAD

**Issue by hypoclone** [traccar/traccar-web#1171]
**Is your feature request related to a problem? Please describe.**
Right now there is no way to generate a spreadsheet of the list of all devices you have on traccar, for example in a situation where you need to generate all the phone numbers and identifiers of all devices so as to subscribe data on them, it is difficult if you don't already maintain a list of all your devices monthly.

**Describe the solution you'd like**
Ability to export an excel file containing list of all devices under Devices in Setting, just as shown below
![Traccar request](https://github.com/traccar/traccar/assets/992984/b67e609d-7698-41be-9caf-c3c80bc38ccb)

**Comment by tananaev** [comment]
This would require more back-end work than the web app.

**Comment by hypoclone** [comment]
Ok @tananaev I have closed it and reopen on the traccar repo... thanks
