### ISSUE TITLE
Traccar web demo unavailable

### ISSUE THREAD

**Issue by ildar170975** [traccar/traccar-web#1173]
**Describe the bug**
Today (01.09.23) cannot open ant demo web interface:

![image](https://github.com/traccar/traccar-web/assets/71872483/88b724d1-873c-46ce-ae81-a6576244a7aa)
Page is blank.
Same for demo2..4.
As for demo1 - a picture is different (probably the server was switched off by purpose):

![image](https://github.com/traccar/traccar-web/assets/71872483/9d728fc5-931f-43f3-85b6-f406d66c091b)

Same for FF, Chrome, Edge.

**To Reproduce**
1. Open a "https://demo3.traccar.org/" in a browser.

**Expected behavior**
A web page is open in a browser.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Сhrome, FF, Edge

**Comment by tananaev** [comment]
We don't provide support for demo servers.

Also all of the demo servers are working for me, so I suspect it's something on your end.

**Comment by ildar170975** [comment]
Tested with 2 local ISPs & cellular (MTS) - same, not available.
So, this seems to be not only on MY side only, many users here in Russia may not have access.

**Comment by tananaev** [comment]
Just tried through a VPN with Russian endpoint and all of the demo servers are still working.

**Comment by ildar170975** [comment]
Very strange.
2 desktops (Win10), different ISPs - web interface not working (3 browsers)
1 tablet with some ISPs - same
1 mobile via 4G - same

**Comment by ildar170975** [comment]
@tananaev 
Anton, the glitch has been fixed yesterday.
Have no idea what could be a reason of this.
Thanks a lot for keeping the service alive!
