### ISSUE TITLE
Show street does not decode address, master

### ISSUE THREAD

**Issue by YeiserCode** [traccar/traccar-web#1174]
**Describe the error**
A clear and concise description of what the error is.

Show Street Only Shows coordinates and does not show the street

Latest Version MASTER AVAILABLE TESTED ON LOCALHOST:3000
Visual Studio CODE 

**To play**
1. Go to 'Select Device'
2. Click 'Show Street'
3. Scroll down to 'Result Shown'
only shows coordinates

**Expected behavior**
Expected behavior show street no coordinates
It must show the encoded address and not just coordinates

**Screenshots**
![WhatsApp Image 2023-09-01 at 10 54 28 AM](https://github.com/traccar/traccar-web/assets/131619978/6d7fee3d-b84d-415a-af49-e7be2ece126c)

![WhatsApp Image 2023-09-01 at 11 08 21 AM](https://github.com/traccar/traccar-web/assets/131619978/6314c120-fe4e-4e26-a29c-49ea126ec481)

**Desktop (complete the following information):**
 - Browser [Chrome, edge]
 - Version [latest version]

**Additional context**
Add any other context about the issue here.

The Test was done locally and the behavior is unexpected 
unless you already have a new setting to decode the address

**Comment by tananaev** [comment]
It looks like you just haven't enabled a proper reverse geocoder. Next time I would recommend asking on the forum first before submitting a bug report.
