### ISSUE TITLE
popup no longer visible in replay

### ISSUE THREAD

**Issue by cop98** [traccar/traccar-web#1177]
From Traccar 5.9 when creating a "replay" report, it is no longer possible (by clicking on the vehicle icon) to open the popup. Until version 5.8 this was possible.

It was very practical because it made it easy to get the status of the device at any time during the trip

**Comment by hypoclone** [comment]
@cop98 looks like it's been solved here
https://www.traccar.org/forums/topic/route-replay-from-device-popup-window/

**Comment by cop98** [comment]
True. had not seen that. Thank you
