### ISSUE TITLE
Introduction of the concept of "tracks"

### ISSUE THREAD

**Issue by noseshimself** [traccar/traccar-web#119]
The first step could be a table consisting of a unique track ID, the device ID of the tracked device, the ID of the first recorded position and the ID of the last recorded position.

If you want to be really nice you might add columns for duration, average speed, time in motion (we'll discuss later how to calculate that – detecting non-motion can be tricky) and average rise (and optionally a remark/name/whatever string if you want to be very nice to users).

[I've started – and shelved – doing my own tracking project geared at recording long distance rides and started working on the background stuff like statistics and extracting GPX/KML tracks but I chose Python and don't have the faintest idea about working with Java.]

**Comment by spacecabbie** [comment]
No more Replies since. Most of this is implemented as far as i can see. The rest is really more specialistic and i would suggest to contact traccar directly https://www.traccar.org/product/professional-services/

@tananaev can be closed.
