### ISSUE TITLE
Deploy the modern Traccar web application on Vercel

### ISSUE THREAD

**Issue by emmanuelh-dev** [traccar/traccar-web#1198]
I now have the backend on a Digital Ocean droplet, accessible at [https://api.gonzher.com](https://api.gonzher.com). Currently, I'm working on uploading the frontend to [https://gps.gonzher.com](https://gps.gonzher.com), which will be hosted on Vercel.

However, I encountered an error: `https://gps.gonzher.com/api/server 404 (Not Found)`. Strangely, this error only occurs in production. When I upload the repository to Vercel in development, this error doesn't appear.

Here's a snippet from my `vite.config.file`:

```javascript
server: {
  port: 3000,
  proxy: {
    '/api/socket': 'ws:https://api.gonzher.com/',
    '/api': 'https://api.gonzher.com/',
  },
},
build: {
  outDir: 'build',
},

**Comment by tananaev** [comment]
Proxy is only used for development.
