### ISSUE TITLE
Modern web UI - Live Route Length

### ISSUE THREAD

**Issue by kjetilpp** [traccar/traccar-web#1206]
**Describe the bug**
Live Route Length do not work when using Modern web UI, setting WEB Live Route Length set to 1000 in server attributes. But if set in user attributes it works. 

1. Look on a moving object. 

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Chrome
 - Version Versjon 120.0.6099.199
 - Traccar 5.101

**Comment by tananaev** [comment]
Just tested and it's working fine.

I suspect you forgot to enable live routes.
