### ISSUE TITLE
Big File Not Download From /opt/traccar/modern From V5.8

### ISSUE THREAD

**Issue by SmartGpsBD** [traccar/traccar-web#1207]
Dear Anton,
Big file is not download from V5.8
Please see the screenshot: i have put a 1GB file in /opt/traccar/modern and current traccar V5.10

![error1](https://github.com/traccar/traccar-web/assets/73643926/3cf3bcab-d354-43d0-adde-577095324102)

![error3](https://github.com/traccar/traccar-web/assets/73643926/9215c7ca-bc63-4e90-91af-485a6522aecc)

and when i hit http://185.239.209.116/backup.zip in my browser it show 500 - Server Error

![error2](https://github.com/traccar/traccar-web/assets/73643926/d7f16839-df4c-44cf-9514-c8664f5bdff7)

Please note that upto V5.7 any kind of file download perfectly and has no problems.

Lastly my use case is: i have download mysqldump backup file from other vps for any kind of failure in my server.
Thanks

**Comment by tananaev** [comment]
I don't think we can classify this as a bug. Also, you shouldn't need to do it this way.
