### ISSUE TITLE
Multiple notifications - v5.11

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar-web#1208]
**Describe the bug**
Multiple notifications when device is connected to a group.
V5.11 with some customization

**To Reproduce**
1. Create "Ignition on" Notification, channels web, email
2. Link device to "Ignition on" notification
3. Don't link device to a group yet
4. Turn ignition on
Result: One web and one email notification generated which is as expected

1. Then create a group and link the device to a group
2. Turn the ignition on again
Result: 3 x web and 3 x email notifications generated

Only one "Ignition on" event is reported in events report for both tests performed.

I have some customization on v5.11 but it is the same customization I had on v5.10
On v5.10 I did not have the issue

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar/commit/079eaa6ed49813f4050076ac45849f6e4334e45b. Please try.
