### ISSUE TITLE
Yandex browser problem

### ISSUE THREAD

**Issue by borozenetsvv** [traccar/traccar-web#1218]
On Yandex browser not show "Delete element" in bottom of screen when try to delete geofence, but work in Chromium. Another messages not show too.

OS: Windows 11
Browser: Yandex
Version: 24.1.0.2570

**Comment by tananaev** [comment]
1. Have you checked console for errors?
2. Have you tried stable version?

**Comment by borozenetsvv** [comment]
No errors on console. Nothing happens.
I use last version 5.12

**Comment by borozenetsvv** [comment]
In "Incognito mode" all work perfectly. Sorry. Try to find reason.

**Comment by borozenetsvv** [comment]
AdGuard is reason. Sorry again.
