### ISSUE TITLE
Translation error  

### ISSUE THREAD

**Issue by fengshengchang** [traccar/traccar-web#1219]
In file:   traccar-web\modern\src\resources\l10n\zh.json
![image](https://github.com/traccar/traccar-web/assets/14884481/c1190ad0-bc09-4d39-8974-f329166bbb81)

"commandData" means  "命令数据"  or just "数据" in Chinese，not "日期"  .  "Date" means  “日期” in Chinese, not "Data"

**Comment by tananaev** [comment]
If you want to fix the translations, please use Transifex:

https://www.transifex.com/traccar
