### ISSUE TITLE
Limit number of markers on the map

### ISSUE THREAD

**Issue by juniormelo26** [traccar/traccar-web#1222]
The functionality would help the administrator user's vision, reducing the number of markers on the map and thus making it lighter.
If you're interested, I've already implemented and tested it and it worked well.

![All Icons](https://i.imgur.com/zGJ32TQ.png)

![One Icons](https://i.imgur.com/Md6liEF.png)

![Other](https://i.imgur.com/kkoeo7l.png)

**Comment by tananaev** [comment]
Is this a feature request? I don't understand how the limit supposed to work.

**Comment by juniormelo26** [comment]
It is a resource request/contribution. This would filter the number of markers/devices to be displayed on the map.

**Comment by tananaev** [comment]
How do you decide which devices to filter?

**Comment by juniormelo26** [comment]
The filter would be random, it would not be filtering a specific device but rather the quantity of them. The first one that was rendered/updated would be displayed.

**Comment by tananaev** [comment]
This makes no sense to me.

**Comment by juniormelo26** [comment]
It would help to reduce the load by redefining the icons on the map. It's okay Anton, it's just a suggestion.

**Comment by tananaev** [comment]
We have clustering that solves this problem. Just hiding devices randomly makes no sense in my opinion.
