### ISSUE TITLE
[Feature request] Reports duration show in hours and minutes 

### ISSUE THREAD

**Issue by JellevanKraaij** [traccar/traccar-web#1223]
**In the reports tab, duration is rounded to whole hours**
When a stop or trip duration is longer than 30-45 minutes its rounded to 1 hour, or when its in between hours its always rounded.

**Keep minutes after the hour**
Don't round to whole hours but instead show 5 hours and 40 minutes for example.

![image](https://github.com/traccar/traccar-web/assets/55192476/7de7342c-725f-49a5-b2a2-55a1734ac57b)

**Comment by tananaev** [comment]
It's already done in https://github.com/traccar/traccar-web/commit/32302e6bc54a65b9594d4cde4ff4c8983f97dacc.

**Comment by JellevanKraaij** [comment]
OW wow, AMAzING

**Comment by JellevanKraaij** [comment]
Thans alot!
Sorry did not notice it!
