### ISSUE TITLE
Does Traccar support the new Coban 405a with a temperature sensor?

### ISSUE THREAD

**Issue by emmanuelh-dev** [traccar/traccar-web#1224]
Is your feature request related to a requirement? Please describe.
The new Coban 405a includes temperature control support, and I have a need for this functionality.

Describe the solution you'd like
Requesting the integration of the new characteristic (temperature control) into the platform.

Describe alternatives you've considered
No alternatives have been explored, as the inclusion of this essential feature is preferred.

Additional context
I currently possess the latest Coban 405a and require support for its temperature sensor functionality.

**Comment by tananaev** [comment]
For questions use the forum.
