### ISSUE TITLE
Showing other device positions when displaying report(s) on a map

### ISSUE THREAD

**Issue by jinzo** [traccar/traccar-web#1230]
The Legacy web interface displays current live (other, non reported) device positions when displaying a report on a map (for example Trip report - specific trip view).  So you see the selected trip, and if there is currently a device (or more of them) near the selected trip (or you zoom out) they are shown 'normally' like in the base map view.

Modern interface does not do that, and some of my users prefer to see other devices alongside the specific selected trip data. Would this be considered a bug or intended (change of) behaviour in the Modern web interface? What do you think about either replicating the old interface behaviour or putting this behaviour under a specific user attribute/setting?

**Comment by tananaev** [comment]
This would be considered a feature request.

**Comment by jinzo** [comment]
I'm willing to implement it - did some basic research and tried a few things. What's your preference - gated with a user attribute/setting or default behaviour like in Legacy?

**Comment by tananaev** [comment]
I want to know details on what and how you want to implement.

**Comment by jinzo** [comment]
Sorry, sometimes I have trouble communicating clearly. Let me try this step by step, as I cannot provide non identifying screenshots.
In Legacy Web, if you click on Reports at the bottom, select a "Trips" report type for a specific device and time frame you get a list of Trips. If you click on a specific Trip, the Trip (line) is displayed on the map. If there is currently a device (any other device) near that trip line (or you zoom out the map) it is displayed on the map.
In the Modern Web, ONLY the start/end markers and Trip (line) is displayed, without other devices. I would like the Modern interface to behave like the Legacy one in this aspect.
Basic technical idea to illustrate is adding a `<MapPositions ... />` here:
https://github.com/traccar/traccar-web/blob/b5bed7d8fc6d410edf06b23408a9857541381618/src/reports/TripReportPage.jsx#L162-L171

Hopefully this is clearer.

**Comment by tananaev** [comment]
Oh, I see. I don't think that makes sense. I thought you're talking about displaying trips from multiple devices on the same map.

**Comment by jinzo** [comment]
Yeah I have the same feeling, but apparently some of my users find this helpful. And I just decided to run it by you, to see if this could be upstreamed. Thanks for your time and feedback.
