### ISSUE TITLE
Regarding Traccar-Web Running issues in windows PC

### ISSUE THREAD

**Issue by BJagruti** [traccar/traccar-web#1235]
**Describe the bug**
I am running the code in my windows PC but getting proxy server Error

**To Reproduce**
1. Running the traccar-web code
2. https://www.traccar.org/build-web-app/
3. Traccar backend running locally
4. Install dependencies using npm install command
5. When i am running development server using npm start command 
6. Getting error
12:28:27 AM [vite] http proxy error: /api/server
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1116:18)
    at afterConnectMultiple (node:net:1683:7)
12:28:28 AM [vite] http proxy error: /api/server
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1116:18)
    at afterConnectMultiple (node:net:1683:7) (x2)

**Expected behavior**
I am expecting that the code should run properly in my Windows PC and also i need to deploy the same code in IIS server as well

**Screenshots**
![image (2)](https://github.com/traccar/traccar-web/assets/167743142/9cf170ad-9fbd-49c4-a2d4-7061841884f8)
![image (3)](https://github.com/traccar/traccar-web/assets/167743142/7109c121-8228-4282-9f05-1c8c43576c25)

In chrome its loading only now giving the response

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version npm--version ==10.5.0

**Additional context**
According to your documentations i followed all the steps but getting the proxy server error but i need to run the traccar web my PC.

Please give me the response ASAP..

Thank you so much
Jagruti Bagul

**Comment by tananaev** [comment]
For questions you should use the forum. This is a not a bug, so please don't report it here.
