### ISSUE TITLE
Cannot see a "Status" of a device

### ISSUE THREAD

**Issue by ildar170975** [traccar/traccar-web#1237]
**Describe the bug**
Cannot add a current status of a device to a popup.
Added a "Status" field in Settings:

![изображение](https://github.com/traccar/traccar-web/assets/71872483/0fdfccf2-ed45-4a90-bf0f-1af7cc219117)

But the popup still does not show the status:

![изображение](https://github.com/traccar/traccar-web/assets/71872483/57ee262d-fcf0-446e-82a1-3747ee27b78b)

Also, the "Status" is not shown here:

![изображение](https://github.com/traccar/traccar-web/assets/71872483/4ff2c39d-2872-40ce-bfef-fb5eada323e0)

**To Reproduce**
Steps to reproduce the behavior: see above

**Expected behavior**
The "Status" field should be displayed if selected in Settings.

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: FF
 - Version: 125.0.3

**Smartphone (please complete the following information):**
 - Device: Redmi 7A (in fact - for any device)
 - OS: Android 11, iOS 15x
 - Browser: na
 - Version: na

**Additional context**

**Comment by tananaev** [comment]
You're mixing up connection status with device status.

**Comment by ildar170975** [comment]
Then which parameter is used to represent a current connection status?
Online, offline, unknown.

**Comment by tananaev** [comment]
That parameter is on the device model, not position. You cannot display it in the popup.

**Comment by ildar170975** [comment]
I meant this parameter which can be "online", "offline" or smth else:
![изображение](https://github.com/traccar/traccar-web/assets/71872483/149ad188-1614-447f-afc8-dac649fe68d7)

I am asking because I am using a [Traccar server integration for Home Assistant](https://www.home-assistant.io/integrations/traccar_server/) (HA) and till some recent update of HA there was a parameter taken from Traccar server which could have same "online / offline / unknown" values. This parameter was used to show a current status of a connection between a client & a server.
Now I wonder is this parameter is still available as a part of Traccar API.

**Comment by tananaev** [comment]
I already answered in the previous comment.

**Comment by tananaev** [comment]
For discussions please use the forum.

**Comment by ildar170975** [comment]
In which part this is a discussion?
You answered in a rather unclear way, I asked for clarification.
Disappointed.

**Comment by ildar170975** [comment]
OK, I got your point!
Will ask in the Forum then.
