### ISSUE TITLE
Error after comment #1243

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar-web#1248]
**Describe the bug**
After including comment #1243 I get below error when running a combined report.
This is on latest master with some customisation but I compared the copy that worked with the one flagging the error and the only changes is from comment #1243 
```
TypeError: Cannot read properties of undefined (reading 'map')
    at index-DDKx5vYz.js:871:302118
    at uC (index-DDKx5vYz.js:40:24296)
    at Yg (index-DDKx5vYz.js:40:42451)
    at index-DDKx5vYz.js:40:40763
    at E (index-DDKx5vYz.js:25:1659)
    at MessagePort.de (index-DDKx5vYz.js:25:2039)
```
**To Reproduce**
1. On latest master select any device in combined reports and select show.

**Comment by tananaev** [comment]
@jcardus

**Comment by jcardus** [comment]
hello @joystickjockey, should be ok in the latest master. Can you check?

**Comment by tananaev** [comment]
Reverted the recent changes because they broke other things as well, like the name.
