### ISSUE TITLE
build traccar from sources

### ISSUE THREAD

**Issue by harshadura** [traccar/traccar-web#126]
Hi I am trying to build traccar from source: http://www.traccar.org/docs/build.jsp

I am stuck at step > 11) Follow up following documentation here
I am using linux so i hv followed this.

LINUX

Create setup:
1. Download "wrapper-delta-pack-*.tar.gz" from http://wrapper.tanukisoftware.com/doc/english/download.jsp
3. Copy files to "traccar/setup/linux"
4. Change directory to "traccar/setup/linux"
5. Run "./traccar.sh"

could you please elobarate what u meant by  "files"  in here : (3. Copy files to "traccar/setup/linux" )
also there is no file called traccar.sh in sources.

**Comment by arrafa20** [comment]
Once compiled with IDEA, in which path should be the files that i should copy into my production server?

**Comment by tananaev** [comment]
Please don't comment on old closed threads.

**Comment by notesMafia** [comment]
please help me i want to run traccar from source code in windows through intellj but not showing in browser

**Comment by tananaev** [comment]
Have you read the previous comment?
