### ISSUE TITLE
Cannot share device's location

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [traccar/traccar-web#1274]
**Describe the bug**
I have a device i wanted to share location of. I've clicked on the device on the list then hit the three dots and clicked share. Then i clicked show and I got error `extra data at the end - IOException (... < CryptoManager:85 < *:52 < TokenManager:73 < DeviceResource:265 < ... < OverrideFilter:49 < ...)`. The error comes from `/api/devices/share` endpoint. I don't see anything in the server log and I'm not sure how to debug the frontend so i would appreciate some guide.

**To Reproduce**
1. Go to main page
2. Click on device
3. click on the three dots
4. click share device
5. click show
6. error pops up

**Expected behavior**
I guess i should get the url.

**Screenshots**
![Screenshot_20240928_130309](https://github.com/user-attachments/assets/f41b72d7-b948-4ec2-9733-2594845b7c0d)
![Screenshot_20240928_130320](https://github.com/user-attachments/assets/07a34c40-7950-4d11-8aee-a56d0c125653)
![Screenshot_20240928_130329](https://github.com/user-attachments/assets/51764843-300a-4805-b696-e21ad4124552)
![Screenshot_20240928_130336](https://github.com/user-attachments/assets/fbce1bbd-0486-468c-8a88-1032af6903e4)

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Browser chromium and firefox
 - Version latest as of the time of writing

**Smartphone (please complete the following information):**
Does not apply

**Additional context**
Traccar 6.5

**Comment by tananaev** [comment]
Something seems to be wrong with your crypto keys. You can try removing data from `tc_keystore` table and Traccar will generate new keys.

**Comment by Michal-Szczepaniak** [comment]
Thanks that did the trick! maybe it was straggler from when i was moving databases and something broke
