### ISSUE TITLE
[FEAT] Scrollbar Styles

### ISSUE THREAD

**Issue by MishraTanishq619** [traccar/traccar-web#1279]
**Is your feature request related to a problem? Please describe.**
I think we haven't given customised styles to our scrollbar.
We should custom our scrollbar as per our theme.

**Describe the solution you'd like**
I will just add the css at global according the theme of our web-app.

**Additional context**
I want to work on this myself.
Please assign it to me and add tags for hacktoberfest-2024.

**Comment by Kalabint** [comment]
Do [you](https://github.com/mdazfar2/Ezyshop/pull/146) [want](https://github.com/mohitahlawat2001/Loco-Musica/pull/33) [to](https://github.com/anish2210/Mini_Projects/pull/2) [add](https://github.com/iamAyushChamoli/hacktoberfest-24/pull/52) [this](https://github.com/RamakrushnaBiswal/PlayCafe/issues/67) [to](https://github.com/livecoders/website/issues/298) [every](https://github.com/Anshul439/Blogverse/issues/41) [Project](https://github.com/Sriparno08/Openpedia/issues/525) [you](https://github.com/soham0005/ElectroKart/issues/86) [come](https://github.com/Komsos-Matias-Rasul/webpage-samara/issues/1) [accross](https://github.com/warmachine028/euphoria/issues/89)?!

**Comment by tananaev** [comment]
Seems like the last thing people would need. I'm going to close for now.
