### ISSUE TITLE
No layers when using OpenFreeMap

### ISSUE THREAD

**Issue by jcardus** [traccar/traccar-web#1281]
Because we don't set 'text-font' in the layers definition, Maplibre uses the default and tries to fetch: 

https://tiles.openfreemap.org/fonts/Open%20Sans%20Regular,Arial%20Unicode%20MS%20Regular/0-255.pbf

It returns 404 and the layers with text are not shown.

Based on [this](https://github.com/maplibre/maplibre-style-spec/issues/311) and [this](https://github.com/hyperknot/openfreemap/issues/10), I think we should use a constant for text-font in all layers and maybe use Noto Sans.

**Comment by tananaev** [comment]
Good catch. Fixed it as well.
