### ISSUE TITLE
Add Trailer Icon to Traccar Interface

### ISSUE THREAD

**Issue by chrystianmartins** [traccar/traccar-web#1290]
Hello,

In our current project with Traccar, we often need a specific icon to represent trailers, but there is no dedicated trailer icon available. This lack of a clear visual identifier for trailers can sometimes cause confusion, as we rely on icons to quickly identify vehicle types.

I would like a trailer icon to be added to the Traccar project. This icon should be representative of trailers commonly used in logistics, ideally similar to the silhouette of a semi-trailer or cargo trailer. Having this icon available would improve the user experience by providing a clear and distinct visual for trailers.

We have considered using generic vehicle icons or modifying existing icons to represent trailers, but none provide the same clarity or recognition as a dedicated trailer icon.

I have attached an SVG file of the suggested trailer icon. This file can be used as a direct reference or included in the project as-is.

![trailer](https://github.com/user-attachments/assets/39fd4004-6b57-4fe0-bd7f-1f3553f67f73)

**Comment by chrystianmartins** [comment]
Sorry Anton I redid the SVG
![trailer](https://github.com/user-attachments/assets/a6a411b3-8ffb-42c7-aa7c-ae892c052268)

**Comment by tananaev** [comment]
What's the license for this image?

**Comment by chrystianmartins** [comment]
I created this SVG from scratch using Figma. I'm contributing it to the project freely and without any restrictions. Feel free to use it in any way that benefits the project!
