### ISSUE TITLE
Devices disappear from map when group is not selected 

### ISSUE THREAD

**Issue by alburi13** [traccar/traccar-web#1297]
**Describe the bug**
When I began using the web app the devices were shown on map without any group filtering on the top bar. Also, when I opened the web app all filters where empty. After a few days of using the web app I tried again opening and noticed that the app started with filtered groups. I tried removing all selected filters but the devices disappeared from the map. Also, even when I removed all filters, the blue dot signifying selected filter remained. Since then, every time I open the web app from this chrome user, I have the same problem. If I login from another chrome user I do not have this issue (all filters are empty and I can see my devices on the map). Same thing happened with safari after using for some time. Could this be a cookie issue?  

**Expected behavior**
I expected that when I open the web app I will see my devices without having to select a specific group of devices. Some devices might not even belong to a group.

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.0 
 - Browser chrome: Version 130.0.6723.117 (Official Build) (arm64), safari: Version 17.0

**Additional context**

![Screenshot 2024-11-15 at 13 36 48](https://github.com/user-attachments/assets/8832003f-9769-474d-8e10-51e839988d95)

**Comment by tananaev** [comment]
It looks like you still have something selected. What do you see in the group popup?

**Comment by alburi13** [comment]
Hello, 

I have created a screen recording that shows how the web app responds in chrome from 2 separate users:

https://www.loom.com/share/a69e4f9da33046848841bd8928112e84?sid=1f3451e0-7c28-49f5-abc1-40d8e1a40260

As you will be able to see from user number 1 (F) when deselecting the groups, no devices are shown, also the blue dot on the filters remain even when no filters are selected. User 2 (A) works as expected. The only difference between the two users is that I used to login more often from user 1 (F)

**Comment by tananaev** [comment]
You forgot to mention that you're not using the latest official release. We only accept bug reports in the latest version.

**Comment by alburi13** [comment]
Hi, I updated my version to 6.5. The problem persists.

https://www.loom.com/share/164632222996442f97db376f590e4e89?sid=312ba461-d162-407c-ac30-88cdcad5762b

**Comment by tananaev** [comment]
Please provide access to take a look because I'm not able to reproduce it locally.

**Comment by alburi13** [comment]
What kind of access would you like? This problem seems to be related to browser, so you would have to access my own browser?

**Comment by tananaev** [comment]
You said it happens in different browsers.

**Comment by alburi13** [comment]
I have the same problem on safari as well at the moment. However, as I mentioned on my first message this problem appeared after using the app( from a specific chrome user) for some time. When I login from another chrome user I do not have this issue. Same thing happened on safari. The problem started after using the browser for a while. I think it is related to cookies stored on browser maybe?

**Comment by tananaev** [comment]
Did you happen to remove any groups? That would explain the issue.

**Comment by alburi13** [comment]
Yes I have removed groups in the past. How could this explain this issue? Is there a way to resolve it? does it make sense that from another chrome user I do not have this issue?

**Comment by tananaev** [comment]
If you had a group selected for filtering, you removed it, but it is still stored for filtering. To solve you just clear the browser cache or find specific item in the storage and clear that.

**Comment by alburi13** [comment]
Yep it works fine after clearing all browser cookies

**Comment by jcardus** [comment]
This also happens without deleting groups. For example, if you enter a user (pressing the login icon in the user list) and that user doesn't have access to the selected group. Maybe we can put a reset button to remove the filter key on local storage.

**Comment by tananaev** [comment]
We should probably clear local storage on explicit logout.
