### ISSUE TITLE
Chart in report

### ISSUE THREAD

**Issue by hypoclone** [traccar/traccar-web#1315]
**Is your feature request related to a problem? Please describe.**
The chart in report looks clumsy when there is much data as shown below
![Screenshot 2024-12-25 151550](https://github.com/user-attachments/assets/3b1d5d85-601f-41ee-95f1-e5c8c6fa2b65)

**Describe the solution you'd like**
having pan and zoom will make it better, also the dots should only show on mouse hover as below
I can submit a pull request on the solution

https://github.com/user-attachments/assets/4d01b2b8-2127-4a2d-af7e-d4e652ddefac

**Describe alternatives you've considered**
zoom on mouse scroll can also work

**Additional context**

**Comment by jinzo** [comment]
I think something like that would be nice indeed. And it looks like you already have some code, why not post a PR with that code?

**Comment by hypoclone** [comment]
@jinzo i have, thank you
https://github.com/traccar/traccar-web/pull/1316

**Comment by hypoclone** [comment]
Done in https://github.com/traccar/traccar-web/pull/1316
