### ISSUE TITLE
ignore locations where speed=0

### ISSUE THREAD

**Issue by vkrastanov** [traccar/traccar-web#14]
an option not to show locations where speed=0 on the map.

**Comment by spacecabbie** [comment]
@vitalidze I was wondering what happened with this. since that time you have made a web mod i see but not anymore for traccar 4.x. I was wondering if we maybe could merge the 2 projects join recourses ?

**Comment by tananaev** [comment]
We do have speed filtering on the server side. If that's not enough, please create a new ticket with details why server side filtering doesn't work for your specific case.
