### ISSUE TITLE
Magnet to road functionality .

### ISSUE THREAD

**Issue by dumar** [traccar/traccar-web#211]
Hello, have you think about magnet to road optional functionality for cars tracking? I mean something like normal car navigation works, it shows your position on the closest road instead of the field. It would be also perfect for calculating distance. I know some people use it for tracking off road moves, so it could be option for choose. I heard new web panel is during coding, maybe you could consider adding such a functionality  :)

**Comment by spacecabbie** [comment]
Similar to snap to road already in feature requests.
https://github.com/traccar/traccar/issues/4205
https://github.com/traccar/traccar/issues/2308

@tananaev can be closed.
