### ISSUE TITLE
Need Help in adding custom functionality in traccar-web

### ISSUE THREAD

**Issue by usman427** [traccar/traccar-web#219]
I am new to traccar. I am exploring it, but I am unable to understand it in order to implement my custom functionality. It would be great if you help me in understanding the traccar

What I want to do in traccar:
I have installed the ground System of Traccar. What I need is simple. If any Android/Iphone User that works with the Traccar Client App push the big red Panic Button (custom Button in mobile app) so in the Traccar Website the identifier-point must go to the color blinking red. So if there a security officer,  that monitors the
traccar site, so he can see that this person is in a case of emergency. The Button doesn’t exist and the red blinking point it also doesn’t developed in the Monitor Website of Traccar. So, I want to develop it.

1 - One button in mobile apps that when user presses it, it will send some message to traccar.
2 - Once the message is received in traccar, pointer must goto in blinking state or change it color.

Could you please help me how to make button and how to send message and receive it in traccar-web and implement accordingly, Also please tell me which java files will involves in it in order to implement the above functionality. Do i also need to make new protocol?

**Comment by alecalabro** [comment]
Hi there usman427,, did you find some app for android Phone which uses the Panic button.
I´m using traccar and need to use an application to send SOS message to traccar.. Find X-GPS app , I think it is using Osmand protocol... the server can see the location and tracking of the device but nothing happend when I press the button.. 
Could you help me on this? 
Thanks

**Comment by usman427** [comment]
Hi Alecalabro, 
I'd done this 2 years back. Could you please send me exactly what errors you are getting ? or if possible, can you share some screen shots ?

**Comment by alecalabro** [comment]
Hi usman427, no error on web page , just no receving of SOS commands.. I just find out X-GPS app (https://play.google.com/store/apps/details?id=com.navixy.xgps.client.app&hl=es_419).. but it seems nos working fine with SOS ALarm... all the rest of events like position,, are well received..
I´m not a developer so I need to use an app with SOS button...
On th other hand I´m usin a small Chinese GPS tracker (TK102 / Gps103 coban) and those trackers are working great!!
I´m wondering if you could use any app or develop a custom one.. if you can share with us..

Thanks In advance!!

**Comment by usman427** [comment]
Actually what i did is fixed that SOS functionality in traccar and added some custom function for both iPhone and Android. As I did it as my freelancing project two years ago, so I need to revise all logics.
