### ISSUE TITLE
Wish: Car/park finder with one Click in Google maps

### ISSUE THREAD

**Issue by Phantomatz** [traccar/traccar-web#253]
In the past I had created myself a "Tasker" app on my android mobile, which always saved the GPS position, when the bluetooth connection with my handsfree was disconnected. 
The coordinates where simply saved in a file and opening that file with Google maps helped me to find my car back.

Thats very usefull.

Would be great to have the opportunity to have a single Website call to get the last position openend in google earth or similar and being able to navigate directly to it.

**Comment by tananaev** [comment]
It sounds more like Navigation app feature.

**Comment by Phantomatz** [comment]
I think it would be usefull additional feature for Traccar Web that with a "single click" you could open a the latest recorded position.

**Comment by tananaev** [comment]
You can already do it. When you click on a device it centers it on the map and displays latest info.

**Comment by Phantomatz** [comment]
My idea is a one click icon on the desktop of my mobile phone which directly open Google Maps with the latest recorded position like 
https://www.google.de/maps/@48.7798534,9.1728372,15z
The latest position is from the Traccar and the link as shown above is automatically generated by Traccar on my server (Somewhere in my private or public NAS folders)
That could be a way to handle several GPS tracker, but for each tracker you only need one Link on your desktop which directly opens GoogleMaps with the most recent position.
No need to log into the user interface and select the tracker you like to see etc, which from a mobile phone is quite a task ...

**Comment by tananaev** [comment]
It might be a nice feature for mobile app.

**Comment by spacecabbie** [comment]
Good news we have a mobile app ! Its been out for a while have look in the google/apple store

@tananaev Can be closed
