### ISSUE TITLE
There are issues with open layer restricted bounds.

### ISSUE THREAD

**Issue by 7hill** [traccar/traccar-web#282]
Hi All,
    The restricted map bounds does not work with open layer map. After loading the map, if do mouse scroll the map boundary gets change and locked with same boundary.
    I am not sure whether setting the latitude and longitude correctly while creating restricted bounds.
Here the code for restricted bounds implemented,

```
        MapOptions defaultMapOptions = new MapOptions();
        defaultMapOptions.setDisplayProjection(new Projection("EPSG:3857"));

        MapWidget mapWidget = new MapWidget("900px", "650px", defaultMapOptions);

        OSM osmMapnik = OSM.Mapnik("Mapnik");
        OSM osmCycle = OSM.CycleMap("CycleMap");
        osmMapnik.setIsBaseLayer(true);
        osmCycle.setIsBaseLayer(true);

        mapWidget.getMap().addLayer(osmMapnik);
        mapWidget.getMap().addLayer(osmCycle);

        LonLat lonLat = new LonLat(140.456111, -32.0916665);  // longitude, latitude

        lonLat.transform("EPSG:4326", mapWidget.getMap().getProjection()); 
        mapWidget.getMap().setCenter(lonLat, 4);

        Map map = mapWidget.getMap();
        Bounds bound = new Bounds(-55.05, 112.928889, -9.133333, 167.983333);  // min_latitude, min_longitude, max_latitude, max_longitude
        map.setRestrictedExtent(bound);
```

Please suggest me to implement the restricted map bounds and mouse scroll, navigations.

Thanks in advance!!!

**Comment by tananaev** [comment]
Old web interface is no longer supported. Library limitations was one of the reasons for that.

**Comment by 7hill** [comment]
Thanks for your reply. If the old web interface is the problem. How can get new web interface and library to check this libraries? Please help me to achieve this. I can get only open layer version 1.0 for GWT, if there is any updated open layer version for GWT support. Please let me know.

Thanks.

**Comment by tananaev** [comment]
New web interface doesn't use GWT. It's pure JavaScript:

https://github.com/tananaev/traccar/tree/master/web

**Comment by spacecabbie** [comment]
@tananaev can be closed new web has been out for a while
