### ISSUE TITLE
change web address for application traccar web

### ISSUE THREAD

**Issue by bhrochdi** [traccar/traccar-web#283]
Hello,
I successful to run  web application traccar in installed on a dedicated server, assuming www.domaine-name.com, what I want to do is to change the default web address www.domaine-name.com to www.domaine-name.com/app/. I changed the setting in the following way `<entry key='web.address'></entry>` *\* =>*\* `<entry key='web.address'>/app</entry>` but it's not working. help me.

**Comment by tananaev** [comment]
Are you using `traccar-web` project? I has been deprecated for a long time and not supported any more. If you have a question about Traccar server, you should ask here:

https://github.com/tananaev/traccar/issues

**Comment by bhrochdi** [comment]
yes I use web-traccar agree I will ask my questions in isssues montionné section above.

**Comment by tananaev** [comment]
Where did you get traccar-web? Which version are you using?

**Comment by bhrochdi** [comment]
I use the zip version of downloaded Package from here. [https://github.com/tananaev/traccar-web]() file name traccar-web-master.zip

**Comment by tananaev** [comment]
Did you build it yourself? Any particular reason for using this old project? Traccar main repo includes new web interface that is better, faster and has more features than this one.

**Comment by bhrochdi** [comment]
I have no particular reason it just did happen to run the traccar is not working and tried traccar-web is works.

**Comment by tananaev** [comment]
`traccar-web` is just a web interface for `traccar`. You can't run it on it's own, so your answer doesn't actually many much sense. Basically you are saying that `traccar` doesn't work, but `traccar` with `traccar-web` does. How is it even possible? I think there is some misunderstanding.

**Comment by bhrochdi** [comment]
I wanted to say that I can not run a traccar + traccar-web in path www.domain-name.com/app

**Comment by tananaev** [comment]
In one of the previous comments you said that `traccar` doesn't work and `traccar-web` does. My point is that you shouldn't use `traccar-web` at all because it's out of date and not supported any more.

**Comment by spacecabbie** [comment]
This is really a install/support question. If issue still exist please open a topic on the forum.
@tananaev 

Issue can be closed.
