### ISSUE TITLE
Generating report

### ISSUE THREAD

**Issue by poobaisle** [traccar/traccar-web#284]
Hello Tananaev, 
Thank you for spending time to make your application able to compete with commercial apps. I am completely new to this world of open source and my skills are under zero as far as coding is concerned. I am just a user of those GPS tracking services applications for my professional trucking activity.
So far, I am using a commercial web based application. In fact, 2 web based applications from 2 different companies. Each one of them cover 10 trucks as an experimentation to see what is exactly my requirement. I have read in a recent interview that you are not a user of your application so I'll try to bring my feed back as much as I can.
I am based in Thailand by the way. It is important to say because most of the sensor available on tracking devices are very accurate and very specific but on my perspective I need only to focus on driver's behaviours I can change like "overtime parking engine on" or "overspeed". If I know where my trucks go, how long do they stay at registered delivery spots (which are always the same) and how many kilometers they run, 90% of the job's done as far as monitoring is concerned. The balance 10% remaining uncovered is the uncompressable space of freedom I have to deal with on another ground than with technical devices.
In order to find a open source application to cover my needs, I checked first OpenGTS. I had it running on Ubuntu server but it appears that the standard version doesn't allow to generate trip reports or geofence in/out reports... Even though it is open source, I don't have the skill to enable these reports. So I came to traccar hoping that these reports would be available. However, from your demo web server, I couldn't see where to get them.
Could you please help me with that ? Basically, what I need is a date to date reports showing 1/ time of arrival - time of departure from registered area (geofence) by truck and by selected group of trucks 2/ non moving truck for a certain period of time whether engine is on or off 3/ overspeed. 
Are these reports easy to configure on traccar ? Is there a kind of webmin application for traccar that would give access to the core of the application to configure these reports ?
Thank you for your feedback or any feed back from this community.
Best regards
Poobaisle

**Comment by tananaev** [comment]
Thank you for feedback. Currently Traccar only supports a single very basic report, but I plan to implement better report generation very soon.

P.S. This repository is no longer active, so you should use following issue tracker:

https://github.com/tananaev/traccar/issues

**Comment by poobaisle** [comment]
Sorry, I am a bit lost with the different repository... I think I left my initial message on traccar then it was moved to traccar-web no ? Traccar-web is no longer active ? Does it mean the server d.traccar.litvak.su is no longer a project ? I found there very interesting reports I should say. Is this new development already over ??

**Comment by vitalidze** [comment]
Its still active. You just posted to a wrong issue tracker. Please use this
one https://github.com/vitalidze/traccar-web/issues

I am on vacation currently. My colleague may help you though.

четверг, 14 июля 2016 г. пользователь poobaisle написал:

> Sorry, I am a bit lost with the different repository... I think I left my
> initial message on traccar then it was moved to traccar-web no ?
> Traccar-web is no longer active ? Does it mean the server
> d.traccar.litvak.su is no longer a project ? I found there very
> interesting reports I should say. Is this new development already over ??
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tananaev/traccar-web/issues/284#issuecomment-232606332>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACMCNf5fu6gkXjD4a0tjGcGWhMj6PSdoks5qVflsgaJpZM4JMFaQ>
> .
>


-- 
Kind regards, Vitaly Litvak

**Comment by spacecabbie** [comment]
We have lots of improvements since nice to see a fellow trucker to use this nice system.
I hope you have since found the forum and website. If you have any other questions feel free to open a post there. https://www.traccar.org/forums/ Cleaning up the old issues list here.

@tananaev can be closed.
