### ISSUE TITLE
Another Tomcat issue in same machine

### ISSUE THREAD

**Issue by sugarpramana** [traccar/traccar-web#288]
Hello . i have problem with my tomcat **(another tomcat for my web-app )** in same machine with traccar installation. Traccar & 'my tomcat' use same JVM.
Traccar port is **'8082'** & 'my tomcat' port is **'8181'**
I can not run 'my tomcat' when traccar is running ?

Please help me with this issue.
Thank you.

**Comment by tananaev** [comment]
Well, you need to find out what the error is.

**Comment by spacecabbie** [comment]
This is not a Issue or Feature request please make a post on the forum.
https://www.traccar.org/forums/

@tananaev
