### ISSUE TITLE
Captcha image on Webpage Login

### ISSUE THREAD

**Issue by JohnnyDevine** [traccar/traccar-web#289]
Good Morning, it would be nice to have  Captcha image security on the login page to prevent bot attacks. Many thanks

JD

**Comment by tananaev** [comment]
Thanks. We'll consider adding it.

**Comment by JohnnyDevine** [comment]
This didn't make it into 3.8 then :(

**Comment by tananaev** [comment]
No, it didn't. I would consider this lower priority than some other work. It's nice to have, but there is too much other important items in the backlog.

**Comment by JohnnyDevine** [comment]
if this is not being implemented in the near future, can anyone help me configure fail2ban on port 8082 for web login attacks please?

**Comment by spacecabbie** [comment]
@JohnnyDevine there are many ways to fix this issue outside of traccar .htaccess for one. firewall etc.
I can understand it's not a priority atm. By all means create a post on the forum and i'll give some links to simple solutions. If you have the option to compile the web java it's quite easy to implement a basic captcha check.

@tananaev Can be closed is in feature request issue and rest is support for forum.
