### ISSUE TITLE
Auto Zoom Feature

### ISSUE THREAD

**Issue by JohnnyDevine** [traccar/traccar-web#293]
Is it possible to have an auto zoom checkbox on the webpage so if a device is selected, the map auto zooms to something useful?

JD

**Comment by tananaev** [comment]
Currently it's not possible, but we can consider implementing this option. In current version you can select default zoom level though.

**Comment by brycefisher** [comment]
I'd love to see this implemented

**Comment by cesarserafim** [comment]
This and other functions work in Web.ui Mod, although the project does not follow the updates and new functions of the original Traccar. Besides the auto zoom, I miss the Map Layer Selector and the report format of webui. It is suggested that both developers can join forces in the development of this excellent solution.

**Comment by tananaev** [comment]
Official version of Traccar has auto-zoom when you first open the app. It automatically zooms to the device or devices. It's also possible to select map layers.

Not sure what you mean by report format. You should probably provide more details.

**Comment by jon-stumpf** [comment]
I have not seen the "auto-zoom" behavior referenced.  Is this an option that must be set by the user?

And, does this behavior center on the devices associated with the user as described in #439?

**Comment by tananaev** [comment]
It works if you don't set default map location for the user and server.

**Comment by jon-stumpf** [comment]
Thanks.

**Comment by 2SI3NX** [comment]
https://github.com/tananaev/traccar-manager-android/issues/62

This would be great if it can be implemented. I haven't found a way to auto zoom.
The point would be that when the user selects a device, or switches between devices, the view automatically zooms in the device.

**Comment by TecSeguridad** [comment]
Excuse me. About auto-zoom when you first open the app. This feature works when yo access trough a token? Thank You

**Comment by tananaev** [comment]
Yes, should work with token as well.

**Comment by TecSeguridad** [comment]
I apologize, the question is whether it should work with the token in "/simple/" mode.  Thanks again

**Comment by tananaev** [comment]
No, it won't.

**Comment by spacecabbie** [comment]
Currently implemented.

@tananaev can be closed.
