### ISSUE TITLE
How add google map to UI

### ISSUE THREAD

**Issue by mehdisn65** [traccar/traccar-web#298]
Hello dear Natan
First i wanna appreciate you for this amazing free service and it's kind of you to put it free and make a lot of lifes better, god blest you

This is my website: www.sanagps.ir:8082

How can i add google map to interface
It's just open street map.
User farid@sanagps.ir
Pass 4520

**Comment by mehdisn65** [comment]
Sorry mistake in name, auto correct problem
Dear Anton Tananaev

**Comment by tananaev** [comment]
Please read this page:

https://www.traccar.org/map-layers/

**Comment by mehdisn65** [comment]
Dear, i read that before, but i didn't understand where i can use this:
http://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}&s=Ga

Where i have to copy this?

**Comment by tananaev** [comment]
Into the server settings. Login as admin, then go into Settings -> Server. Put it into the custom map URL field there.

**Comment by mehdisn65** [comment]
Oh, thanx, i made it 
Really thak you
Dear Anton, is it possible to add some option, like key for cut off the car, or play back the route report, or changing the interface ? 
How i can do it?

**Comment by tananaev** [comment]
Commands to stop the engine are already available for some protocols.

If you want to change the interface or add new features, you have to modify source code.

**Comment by mehdisn65** [comment]
Where can i find the souce code?

**Comment by tananaev** [comment]
Please do some research before asking questions like that.

https://www.traccar.org/source-code/

**Comment by mehdisn65** [comment]
Ok 
But i researched and still .didn't find what file have the information about the interface, and where i can change the detail of page.
Any way, thanks

**Comment by tananaev** [comment]
What kind of information are you looking for?

**Comment by mehdisn65** [comment]
The color of the frame, changing the text of panel, adding a text in the page,  the monitoring and managing page and login page

**Comment by tananaev** [comment]
That's all user interface parts, so here is the source code:

https://github.com/tananaev/traccar-web

**Comment by paraisotech** [comment]
Here are some important parameters to change the google maps layers:
URL: http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}&s=Ga (this example we're using the satellite only layer)
In order to select other layer, change the lyrs=**?** parameter(find it in the URL above) with one of the options below:
h = roads only
m = standard roadmap
p = terrain
r = somehow altered roadmap
s = satellite only
t = terrain only
y = hybrid

**Comment by tananaev** [comment]
Thanks for the information.

**Comment by hikmat30ce** [comment]
@leontino use below tile server for traffic layer
https://mt0.google.com/vt/lyrs=m@221097413,traffic&x={x}&y={y}&z={z}&s=Ga

**Comment by leontino** [comment]
@hikmat30ce sorry but where's "tile server "? ahaha

**Comment by leontino** [comment]
@hikmat30ce where I can put this?

**Comment by hikmat30ce** [comment]
![image](https://user-images.githubusercontent.com/12110040/44731000-a8c81c00-aafb-11e8-8f18-4a846d924d77.png)

Please check this image, you can put the url by Going to Setting icon on left top corner and then Server.

Let me know if it doesnot work, I will send more screenshots

**Comment by macano13** [comment]
Well guys I am using the same google map but Google can ban our IP and Domain for using that without API key, that is not legal ! So is there any other legal free satellite layer Map for Traccar same like google ? 

Regards

**Comment by spacecabbie** [comment]
This is not a Issue or Feature request please make a post on the forum.
https://www.traccar.org/forums/

@tananaev can be closed.
