### ISSUE TITLE
[enhancement] Tabs

### ISSUE THREAD

**Issue by vkrastanov** [traccar/traccar-web#3]
Hello,
It would be great if the web panel is organized in tabs (http://www.sencha.com/products/gxt/examples/#sample-11).
For example:
Tab for current positions of all devices (with auto update option)
Tab for historical position of specific device (archive frame can be moved here)
Tab for reports (mileage, distance, speed, etc.)
Cheers.

**Comment by spacecabbie** [comment]
> With new architecture it shouldn't very hard, because each panel is as independent as possible from others, but I am not sure if it will be a good idea because it will slow down everything (especially if you have several tabs with map)... Anyway, I'll think about it, maybe there will be option to enable tabs or something like that...

If i may humbly suggest: Perhaps mark the issue as Feature request?

**Comment by tananaev** [comment]
We have this with the modern app.
