### ISSUE TITLE
How to install Traccar web UI mode.? 

### ISSUE THREAD

**Issue by sdip025** [traccar/traccar-web#307]
How to install Traccar web UI mode?

**Comment by tananaev** [comment]
Traccar comes with web interface by default.

If you are talking about web mod from Litvak, you are asking in the wrong place.

**Comment by sdip025** [comment]
No No.My question  is I wants to change Openstreet map to google map with api key.After installing version 3.7 there are no war file and no traccar.html.So please tell me how to change this map and where i will change?Please reply

**Comment by tananaev** [comment]
Please check official website:

https://www.traccar.org/map-layers/

**Comment by shueb786anwer** [comment]
Hi, I want to create a web app frontend on Angular and want to consume your API. Is it possible. If yes, please share me the getting started and API documentation.

**Comment by tananaev** [comment]
@shueb786anwer, please next time create a new issue for your question instead of commenting on unrelated thread.

As for API documentation, you can find it here:

https://www.traccar.org/traccar-api/

**Comment by spacecabbie** [comment]
This is not a Issue or Feature request please make a post on the forum.
https://www.traccar.org/forums/

@tananaev
