### ISSUE TITLE
I want to consume the web API from AngularJS

### ISSUE THREAD

**Issue by shueb-anwar** [traccar/traccar-web#309]
I was looking for the Web api by traccer i.e. https://www.traccar.org/traccar-api/
But there is no API documentation. 

What should I understand with this JSON
https://raw.githubusercontent.com/tananaev/traccar/master/swagger.json

**Comment by tananaev** [comment]
It's a standard Swagger documentation. There is a countless number of tools that can understand it and show in human readable format or even generate code for you.

Some tools can be found here:

http://swagger.io/tools/

**Comment by tananaev** [comment]
We have had proper API documentation for a while now:

https://www.traccar.org/api-reference/
