### ISSUE TITLE
Google maps error

### ISSUE THREAD

**Issue by vijaemanlapaz** [traccar/traccar-web#310]
Google maps not showing, it's just saying
"Sorry! Something went wrong."
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by tananaev** [comment]
Traccar doesn't use Google Maps.

**Comment by chrystianmartins** [comment]
I'm using Custom Map (with Google Maps address): https://mt0.google.com/vt/lyrs=y&hl=en&x={x}&y={y}&z={z}&s=Ga

For anyone who wants to save some time while looking for specific tile types:

h = roads only
m = standard roadmap
p = terrain
r = somehow altered roadmap
s = satellite only
t = terrain only
y = hybrid
