### ISSUE TITLE
Triton theme's OpenSans fonts does not have the 'embeddable' bit set

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar-web#319]
There are warnings in console and FF and IE fallback to Arial. Chrome is OK.

Here is open issue https://www.sencha.com/forum/showthread.php?310472-Triton-theme-s-OpenSans-fonts-does-not-have-the-embeddable-bit-set

Just to know, don't think we should do something with it.

**Comment by tananaev** [comment]
I don't think we would be able to do anything about it. Hopefully they'll just fix it in the ExtJS eventually.

**Comment by tananaev** [comment]
Closing as it's not relevant for the modern app.
