### ISSUE TITLE
Reports - Alarm event doesn't show the alarm type

### ISSUE THREAD

**Issue by paraisotech** [traccar/traccar-web#329]
![image](https://cloud.githubusercontent.com/assets/18488078/20458298/050d1366-ae88-11e6-9cd7-5ea5027353d9.png)
as you see in the picture, the report only shows that there was an alarm, but it doesn't show what kind of alarm it was. In this example, it was an SOS alarm...
What am i doing wrong?
By the way, i'm using the new 3.8 traccar server...

**Comment by tananaev** [comment]
What do you see if you request same report in the web interface?

**Comment by paraisotech** [comment]
![image](https://cloud.githubusercontent.com/assets/18488078/20458921/bcebbff4-ae98-11e6-85fb-c9cf31e48259.png)
the same report in web interface.

**Comment by tananaev** [comment]
Looks like we don't include any additional information with alarm events. @Abyss777, is that correct?

**Comment by Abyss777** [comment]
Yes, we don't. All information stays in connected `position`

**Comment by tananaev** [comment]
This is already fixed.
