### ISSUE TITLE
Add New report

### ISSUE THREAD

**Issue by jboscosimj** [traccar/traccar-web#343]
Hello, Can I add a new report? As?

**Comment by tananaev** [comment]
Sure, I don't see why not. You would have to write some code though.

**Comment by jboscosimj** [comment]
Could you tell me how I can write a new report to appear in Traccar Web Client reports, how should I do it?

**Comment by jboscosimj** [comment]
I would need a report that would give me the time to stop the vehicle

**Comment by tananaev** [comment]
You should look at the code for existing reports and implement your one in a similar way.

**Comment by jboscosimj** [comment]
I could indicate some web address with the example of a modification of a report. Thanks

**Comment by tananaev** [comment]
I don't have any examples of modification, but you can just look at the original source code in this repository and in the repository for back-end as well.

**Comment by jboscosimj** [comment]
You could indicate where it is, for example the route report? Thanks

**Comment by tananaev** [comment]
Back-end:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/reports/Route.java

Front-end:

https://github.com/tananaev/traccar-web/blob/master/web/app/view/ReportController.js

**Comment by jboscosimj** [comment]
Thanks

**Comment by jboscosimj** [comment]
I have the need to make a new report that gives us stop times for each point. Could you help me describe how to develop it?

**Comment by tananaev** [comment]
If you need help with actual implementation, send me an email and we can discuss it.

**Comment by jboscosimj** [comment]
ok
