### ISSUE TITLE
Traccar-web X SSL

### ISSUE THREAD

**Issue by Turbovix** [traccar/traccar-web#348]
Hello, I have the Apache + Let's Encrypt service, it works fine until the Traccar login screen, after logging in the url continues https, but not green (secure).
If I leave the session it is green again (safe).
So I ask you if the settings at this link: https://www.traccar.org/secure-connection/ are still valid for the current version of Traccar?

Where do I find this location? /api/socket

**Comment by tananaev** [comment]
I think they are still valid.

> Where do I find this location?

It's a path. It is a location itself. I don't even know what you mean by this question.

**Comment by Turbovix** [comment]
I mean that ssl does not work after login, and as for the path I know it is a path, but I can not find that path inside the Traccar.

**Comment by tananaev** [comment]
What's the error exactly? Have you looked at the browser console.

If by path "inside the Traccar" you mean source code, it's here:

[WebServer.java#L133](https://github.com/tananaev/traccar/blob/master/src/org/traccar/web/WebServer.java#L133)

**Comment by Turbovix** [comment]
In the terminal I have this error:

> 

ol-debug.js:68593` Mixed Content: The page at 'https://turbotrack.com.br/' was loaded over HTTPS, but requested an insecure image 'http://mt0.google.com/vt/lyrs=s&hl=pt&x=25425&y=36566&z=16&s=Ga'. This content should also be served over HTTPS.ol.source.TileImage.defaultTileLoadFunction @ ol-debug.js:68593
ol-debug.js:68593 Mixed Content: The page at 'https://turbotrack.com.br/' was loaded over HTTPS, but requested an insecure image 'http://mt0.google.com/vt/lyrs=s&hl=pt&x=25425&y=36565&z=16&s=Ga'. This content should also be served over HTTPS.ol.source.TileImage.defaultTileLoadFunction @ ol-debug.js:68593

>

**Comment by Turbovix** [comment]
Thank you for clarifying my mind.
Https was missing from the url.

Https // mt0.google.com / vt / lyrs = s & hl = pt & x = {x} & y = {y} & z = {z} & s = Ga

**Comment by Turbovix** [comment]
Can you put this remark here (https://www.traccar.org/secure-connection/)?
Maybe interested someone in the future

**Comment by tananaev** [comment]
What I did instead is update URLs to point to HTTPS versions:

https://www.traccar.org/map-layers/

**Comment by Turbovix** [comment]
@tananaev , Thank you !
