### ISSUE TITLE
notification table issue

### ISSUE THREAD

**Issue by izmadev** [traccar/traccar-web#350]
Hi
Settings>notifications 
notification model shows an empty table. the continent appears and disappears quickly

**Comment by tananaev** [comment]
Are you using latest official release without any modifications?

**Comment by izmadev** [comment]
in fact it's the last version from github. i compiled the code sources with eclipse. I have changed nothing except configuration file

**Comment by tananaev** [comment]
Last source code is always work in progress. Unless you know what you are doing, you should be either using installation package or stable code from a tag.

**Comment by izmadev** [comment]
ok thanks

**Comment by izmadev** [comment]
I didn't found any release tag in the git repository, Could you help me please

**Comment by tananaev** [comment]
Here is a tag for the latest release:

https://github.com/tananaev/traccar/releases/tag/v3.8

It has "traccar-web" as a git submodule with correct commit.
