### ISSUE TITLE
No display for my device

### ISSUE THREAD

**Issue by duckysec** [traccar/traccar-web#353]
Hi

I get the logs from my device that uses the Traccar Android application but I do not have any display on the map. The data is correct and present in my MySQL database. 

Moreover, I am obliged to authenticate each time I update the web page.
For information, I am under CentOS and I tried the zip Linux and Source.

But I don't have these problems under Windows.

B.

**Comment by tananaev** [comment]
Sounds like you have some problems with cookies in your browser.

**Comment by peugnezb** [comment]
I have the same problem with Internet Explorer, Mozilla Firefox and Google Chrome. Mozilla Firefox is my only navigator without saved cookies.

At the first login with the browser, I am asked for login and password, then I get a pop-up "api" that asks me for these logins.

**Comment by tananaev** [comment]
That's definitely a cookies issue.

**Comment by peugnezb** [comment]
I disabled private browsing and I still have the same problem. BUT : On Windows, with Traccar for Windows, i don't have this problem with localhost:8082 (with Firefox private navigation) and my smartphone on WIFI network. So I think the problem comes from my server.

I opened the ports:
80: web interface (with nat redirection on port 8082)
5055: Traccar Client (with nat redirection on port 5055)
[Web front server :80 :5055] ----> [Traccar back-end server :8082 :5055]

![no device traccar](https://cloud.githubusercontent.com/assets/10615876/21073831/2f8b649a-beea-11e6-871a-da07d41454e6.jpg)

**Comment by tananaev** [comment]
Check browser console for errors.

**Comment by peugnezb** [comment]
**On the login page**
The last GET command returns an error.
```GET https://mywebsite.fr/folder/l10n/en.json?_dc=1481448607719
200 OK 9ms ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/server?_dc=1481448608084
200 OK 11ms ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/session?_dc=1481448608117
404 Not Found 10ms ext-all.js (ligne 22)```
    Reponse: HTTP 404 Not Found - WebApplicationException (SessionResource:86 < ...)

**After the login page, the API asks me credentials.**
```
POST https://mywebsite.fr/folder/api/session
200 OK 51ms ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/groups?_dc=1481448774926&page=1&start=0&limit=25
401 Unauthorized 193ms	ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/geofences?_dc=1481448774932&page=1&start=0&limit=25
401 Unauthorized 104ms	ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/attributes/aliases?_dc=1481448774936&page=1&start=0&limit=25
401 Unauthorized 110ms	ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/devices?_dc=1481448774945&page=1&start=0&limit=25
401 Unauthorized 116ms	ext-all.js (ligne 22)
10 Firefox ne peut établir de connexion avec le serveur à l’adresse wss://mywebsite.fr/folder/api/socket.
app.min.js (ligne 218, col. 372)
```

So, i try to replace ws://mywebsite... by wss://mywebsite... But it doesn't work :( I think this comes from the reverse proxy. Why ? I don't know.

**Comment by tananaev** [comment]
It looks like all API calls fail as unauthorized. Not sure what the problem is, but I guess it's something with your proxy.

**Comment by peugnezb** [comment]
Let's go to resolve the problem. I will keep you informed of the research.

**Comment by peugnezb** [comment]
After reloading the page, I no longer have errors "400" on some pages. 

**On the login page**
The last GET command returns an error.
```GET https://mywebsite.fr/folder/l10n/en.json?_dc=1481448607719
200 OK 9ms ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/server?_dc=1481448608084
200 OK 11ms ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/session?_dc=1481448608117
404 Not Found 10ms ext-all.js (ligne 22)
    Reponse: HTTP 404 Not Found - WebApplicationException (SessionResource:86 < ...)
```

**After the login page, the API asks me credentials.**
```
POST https://mywebsite.fr/folder/api/session
200 OK 51ms ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/groups?_dc=1481448774926&page=1&start=0&limit=25
200 OK 30ms	ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/geofences?_dc=1481448774932&page=1&start=0&limit=25
200 OK 30ms	ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/attributes/aliases?_dc=1481448774936&page=1&start=0&limit=25
200 OK 30ms	ext-all.js (ligne 22)
GET https://mywebsite.fr/folder/api/devices?_dc=1481448774945&page=1&start=0&limit=25
200 OK 30ms	ext-all.js (ligne 22)
10 Firefox cannot connect to the server at wss://mywebsite.fr/folder/api/socket.
app.min.js (ligne 218, col. 372)
```

I still have : 
- Error "404" : https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.1/ext-all.js "HTTP 404 Not Found - WebApplicationException (SessionResource:86 < ...)"
- Error "Firefox cannot connect to the server at wss://mywebsite.fr/folder/api/socket.  app.min.js (ligne 218, col. 372)"
<pre>
a=new WebSocket(a+"//"+window.location.host+b+"api/socket")
</pre>

I'm sure it's a small mistake, but it annoys me. I don't want to go back on OpenGTS.

**Comment by tananaev** [comment]
It looks like the only remaining problem is with WebSocket connection. Do you have `proxy_wstunnel` module enabled?

**Comment by peugnezb** [comment]
Yes and SeLinux is in Permissive mode on both servers.
```
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
```

**Comment by peugnezb** [comment]
I try to replace 
<pre>a=new WebSocket(a+"//"+window.location.host+b+"api/socket")</pre>
by
<pre>a=new WebSocket(a+"//"+window.location.host+b+"folder/api/socket")</pre>
.. but is not that.

I have : 
- 404 Not found : api/session?_dc=1481565433552 (non blocking)
- 404 Not found : fake-login.html (non blocking)
- 405 HTTP method GET is not supported by this URL : api/socket

I keep looking...

**Comment by tananaev** [comment]
I don't have any other ideas. If you find an answer, please share it here.

**Comment by moraus** [comment]
@peugnezb did you find a solution for this issue? 
I have the same problem, and have been looking all around for the solution, but so far not found it.
Please let me know if you found something.
