### ISSUE TITLE
Automatically registered devices not visible in web

### ISSUE THREAD

**Issue by pimvdnoll** [traccar/traccar-web#369]
When a device is automatically is registered (based on config database.registerUnknown = true) 
the log shows correct INFO: Automatically registered device ..

the API delivers also the json string correct http://<server>/api/devices?all=true&userid=admin:admin

but in the interface they are not shown. Any solutions?

**Comment by Abyss777** [comment]
They linked to nobody. You can open Users - Yourself - Devices and link them to yourself.

Also in the 3.9 available 2 new config keys:

- `database.registerUnknown.defaultGroupId` - group ID that new device will be in. If you linked to this group you will see new devices straight away (after page update actually)

- `database.registerUnknown.defaultCategory` - category that new device will have

**Comment by pimvdnoll** [comment]
thanks for the quick response!

**Comment by pimvdnoll** [comment]
Created a group, checked with the API what Id the group got and set the default groupId config database.registerUnknown.defaultGroupId

I do not see the device until I connect it via Account->Devices.

**Comment by Abyss777** [comment]
Have you linked that group to yourself?

**Comment by pimvdnoll** [comment]
Yes via Users-> select admin -> Groups and is checked.

On 22 Dec 2016, at 14:57, Andrey Kunitsyn <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you linked that group to yourself?

-

**Comment by tananaev** [comment]
If it still doesn't work, I would recommend to link device to your account manually and check if it was assigned to the group.

Also, are you sure you that you are using correct "defaultGroupId"?

**Comment by pimvdnoll** [comment]
Is there another way to check the GroupId? this is my response of the api
http://localhost:9090/api/groups/

[{"id":**1**,"attributes":{},"name":"Default","groupId":0}]

**Comment by tananaev** [comment]
That's the easiest way to get group id.

**Comment by pimvdnoll** [comment]
So, the group is correctly linked to the device when  I check the API at http://<server>/api/devices it returns [{"id":9,"attributes":{},"name":"<name>","uniqueId":"<uniqueId>","status":"online","lastUpdate":"2016-12-24T18:38:41.776+0000","positionId":370,"groupId":1,"geofenceIds":[],"phone":null,"model":null,"contact":null,"category":"Mobile"}]

it's visible after a restart so I think it's the caching/refresh mechanism?

**Comment by tananaev** [comment]
It should be visible without restart, unless you modified something directly in the database.

**Comment by pimvdnoll** [comment]
I got some more info: in the console when refreshing (when the device is automatically created) the marker is not shown for this device. I did not modified anything in the database.

```
**app.min.js:195** Uncaught TypeError: Cannot read property 'get' of null
    at getImageSvg (app.min.js:195)
    at getImageIcon (app.min.js:197)
    at getMarkerStyle (app.min.js:208)
    at getLatestMarker (app.min.js:209)
    at g.updateLatestMarker (app.min.js:203)
    at g.updateLatest (app.min.js:202)
    at F.fire (ext-all.js:22)
    at F.dispatch (ext-all.js:22)
    at g.a.doFireEvent (ext-all.js:22)
    at g.fireEventArgs (ext-all.js:22)
```

**Comment by tananaev** [comment]
Looks like you are missing some files. You should get a debug version stack. Use `debug.html` file.

**Comment by pimvdnoll** [comment]
yeah found it, was wrong Category.
