### ISSUE TITLE
Loss of track data, long compile error appeared.

### ISSUE THREAD

**Issue by Blade888** [traccar/traccar-web#37]
Hi I installed Traccar last night on my server with MySQL it worked great. I watched a vehicle move around for about an hour but then when I tried to replay all of last nights movements a long compile error came up and there is no data since the start time of the request. 
UPDATE: I now have realized it is not showing any history data since that point, all others are fine. It is saving the data to the positions tbl. for the correct unit id.

**Comment by aryansingh9909** [comment]
sir,
   Please clear the meaning of the command "GMT,E/W,hours,minutes#".
