### ISSUE TITLE
Color Devices Status

### ISSUE THREAD

**Issue by jboscosimj** [traccar/traccar-web#370]
When it goes from green to yellow and how this time setting is changed

**Comment by tananaev** [comment]
It can be configured using "status.timeout" parameters. Value is in seconds. Default timeout is 10 minutes.

**Comment by jboscosimj** [comment]
Thanks,
Where can I find all the configuration parameters? Because this is not included in the web: https://www.traccar.org/configuration-file/

**Comment by tananaev** [comment]
I have updated the page. All or most of the configuration parameters should be there.

**Comment by ivanfmartinez** [comment]
@tananaev do you have any idea to put this configurable as per device or per group ?

For some Android phones that sleep I want to have greater timeout, and for devices that does not sleep I want lower value.

**Comment by tananaev** [comment]
It's not possible at the moment. Timeout is global.

**Comment by gustavofcalmeida** [comment]
I noticed the parameter "status.timeout" is not present in default.xml.
When this happens, where does the system get the default value?

**Comment by tananaev** [comment]
Default timeout us 10 minutes, if I remember correctly.

**Comment by gustavofcalmeida** [comment]
ConnectionManager.java:
	
```
private static final long DEFAULT_TIMEOUT = 600;
...
deviceTimeout = Context.getConfig().getLong("status.timeout", DEFAULT_TIMEOUT) * 1000;
```
