### ISSUE TITLE
Adding a static marker in / web / simple

### ISSUE THREAD

**Issue by BenRoeves** [traccar/traccar-web#381]
Hi,

I am trying to add a static marker to the simple web app to show up a bus stop and have not had much luck yet. My JS knowledge is small, so go easy on me please :)

Attempt so far was to set a static lat/long variable, rather than it coming from a tracked device
`var stopBSP = new ol.geom.Point(ol.proj.fromLonLat([-1.3045279, 51.8172225]));`

From there I have been trying to work out what data is held within the variable 'marker' during the event function. Using the assumption that i could then hard code that data into a new variable, also calling stopBSP e.g. 
`source.addFeature(stopBSP);`
or
`marker.setGeometry(stopBSP);`

That hasn't worked at all. 
Any pointers in the right location would be much appreciated.

Thanks,
Ben

**Comment by BenRoeves** [comment]
Or if easier to add them in a map layer, i'd be more than happy with that too. 
/B

**Comment by tananaev** [comment]
Take a look at this simple web app:

https://github.com/tananaev/traccar-web/tree/master/web/simple

**Comment by BenRoeves** [comment]
Hi Tananaev,

That's exactly what I am building from as my base code. But I would like to add a static marker to the map shown by that code.

Thanks,
Ben

**Comment by tananaev** [comment]
Just looks at the code and do the same thing for your static markers.

**Comment by BenRoeves** [comment]
Sorry if I wasn't very clear with my problem, that is what I am trying to do, but am failing to manage as my experience in JS is limited. Any help would be appreciated, but understand if you're not able to do so.
Thanks

**Comment by tananaev** [comment]
I'm not sure what kind of help you are expecting. Do you want someone to write code for you? That can be arranged if you want. Send me an email if you are interested.
