### ISSUE TITLE
Different colors for car markers when car is moved/stopped

### ISSUE THREAD

**Issue by unky23** [traccar/traccar-web#389]
Is it possible to configure WebGUI in such a style that when I report ROUTE when car is stopped (0 km/h) then marker is in red colour? Actually markers are always the same and there is no difference on map when car speed is more than zero and where car speed is zero. It would be very usefull on the map displaying route to make difference colours for stop and move.

**Comment by tananaev** [comment]
Next version won't have markers for reports. It's done for performance reasons.

**Comment by unky23** [comment]
Markers would decrease performance?

**Comment by tananaev** [comment]
Yes, they do, especially when there are a lot of them.

**Comment by unky23** [comment]
But there are already markers but all of them are in the same colour, changing some of them to RED color would decrease performance?

**Comment by tananaev** [comment]
Please read my comments more carefully.
