### ISSUE TITLE
OpenStreetMap stays low res after zooming in

### ISSUE THREAD

**Issue by brycefisher** [traccar/traccar-web#391]
This project is amazing and beautiful! I can't believe I only discovered this week.

I've setup my own private traccar server with the default map provider. Sadly, after zooming in, the tile never seems to load in a higher resolution image, so I end looking at somethig like this most of the time:

![pixelated](https://cloud.githubusercontent.com/assets/220106/22354623/f219ca96-e3da-11e6-9269-863f5e167442.png)

**Comment by tananaev** [comment]
What's the location? Also, check browser network console to see if there are any errors or warnings.
