### ISSUE TITLE
Geofence attributes

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar-web#393]
while creating geofence i am not getting way to add attributes there is no option available to add attribute for geofence.
i want to add some attributes for my custom use.
![geofence](https://cloud.githubusercontent.com/assets/23626544/22396505/363cedb4-e581-11e6-94d7-c3b6768a79d6.png)

**Comment by tananaev** [comment]
I believe there is no way to add attributes to geofence at the moment.

**Comment by Abyss777** [comment]
Correction, attributes was enabled in https://github.com/tananaev/traccar-web/pull/376
And will be available in next release.

**Comment by d33pak-s1ngh** [comment]
@Abyss777  i can see an extra field call calender what is use of that also how i can enable this new geofence in to my current traccar 3.9 version.

**Comment by Abyss777** [comment]
I would recommend you wait for the next release. Or compile server yourself.

**Comment by d33pak-s1ngh** [comment]
that seems fine waiting for release.
