### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by ninioe** [traccar/traccar-web#398]
Hi Anton,
In some networks WebSocket is blocked.
Is the any way to bypass this using AJAX every few sec in case WebSocket is not working?

Thanks
Erez

**Comment by tananaev** [comment]
There is and the fallback option is already implemented on GitHub.

**Comment by ninioe** [comment]
Hi Anton,
This is great news, I will check it...

Thanks

**Comment by ninioe** [comment]
Hi Anton,
The fallback is not working for me behind proxy.

Thanks
Erez

**Comment by ninioe** [comment]
Hi Anton,
If was an older version of chrome not  supporting WebSocket.
I think we could add try block to catch the exception in nonsupporting browsers for the fallback.

Regards
Erez

**Comment by ninioe** [comment]
more details:

I think it is network issue.

chrome (ver 51.0.2704.106 ) behind proxy at office
error:
websocket connection to 'ws://www.xxx.com/api/socket' failed: websoket opening handshake timed out

(after a few minutes the socket is closed and fallback is working every 60 seconds with the toast error message )

IE (ver 11.0.9600.1824) on same computer and is working fine

**Comment by tananaev** [comment]
It sounds like everything is working as expected.
