### ISSUE TITLE
Disabling the register button is not working.

### ISSUE THREAD

**Issue by chrystianmartins** [traccar/traccar-web#403]
Disabling the register button is not working.
I'm going on Server-> I uncheck the CheckBox, but when I open the checkbox again it is still marked.
I downloaded the latest version of SenchaCmd-6.2.1-windows-64bit
But the path that is in the minify.bat file does not match the current files.
In my case I'm using windows 10, how to proceed?

Thank You

**Comment by tananaev** [comment]
It's a known issue - #399.

Bat file is not maintained. You would have to adjust paths if you want to use it.
