### ISSUE TITLE
http://trac.dev/web/app.min.js not found

### ISSUE THREAD

**Issue by hengsoheak** [traccar/traccar-web#404]
I have install traccar-web on my local computer with below environment 

WampServer 3.0.4
window 8.0.

When i vew on http://trac.dev/web/release.html I got 
error app.min.js not found
When I access to http://trac.dev/web/debug.html
Error  http://trac.dev/web/api/server not found.
How can I get those api?

**Comment by tananaev** [comment]
You have to install full Traccar, not just web interface.

**Comment by hengsoheak** [comment]
So mean that I have to install traccar-setup.exe first?

**Comment by tananaev** [comment]
Depends on what you are trying to do. If you just want to install official version of Traccar, download an installation package and follow instructions. It already includes everything your need.

**Comment by hengsoheak** [comment]
I will if everything going well,
But now I'm try to install end testing in my local marchine (window) and if it get the approval from them I will install it in my real server(hosting)
However I've clone from https://github.com/tananaev/traccar.git this repositry and try to run in Netbeans IDE (https://www.traccar.org/build-in-netbeans/).But I'm simply not much understand about Database Do i need to install any Database manager for JAVA app or this app?

**Comment by tananaev** [comment]
You don't need to install any database manager or driver. Everything comes with the server. Make sure you provide path to the config file as a command line argument.

**Comment by hengsoheak** [comment]
I found this in the debug.xml

<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <entry key="config.default">./setup/default.xml</entry>

    <entry key='web.path'>./traccar-web/web</entry>
    <entry key='web.debug'>true</entry>
    <entry key='web.console'>true</entry>

    <entry key='geocoder.enable'>false</entry>

    <entry key='logger.file'>target/tracker-server.log</entry>

    <entry key='database.driver'>org.h2.Driver</entry>
    <entry key='database.url'>jdbc:h2:./target/database</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'></entry>

    <entry key='intellitrac.port'>6037</entry>

</properties>
So I have to install mysql Database or using any database service provider right?

**Comment by tananaev** [comment]
By default it will use embedded H2 database. if you want to, you can install MySQL, but it's not a requirement.

**Comment by hengsoheak** [comment]
and if I follow the https://www.traccar.org/build-in-netbeans/ official website but got this result 


cd D:\heng_sopheak\project\T&Go\Traccar\traccar; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_121" cmd /c "\"\"C:\\Program Files\\NetBeans 8.2\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath org.traccar.Main debug.xml\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_121\\bin\\java.exe\" -Dexec.workingdir=D:\\heng_sopheak\\project\\T&Go\\Traccar\\traccar -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.2\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 0.094s
Finished at: Wed Feb 08 15:42:38 ICT 2017
Final Memory: 6M/123M
------------------------------------------------------------------------
No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
The system cannot find the path specified.

**Comment by tananaev** [comment]
I would recommend to use IntelliJ IDEA. If you want to use NetBeans, please check your problem on relevant NetBeans resources or StackOverflow.

**Comment by hengsoheak** [comment]
OK Thanks

**Comment by hengsoheak** [comment]
If I choose to build with dependencies 

it will success 
--- maven-install-plugin:2.3.1:install (default-install) @ traccar ---
Installing D:\heng_sopheak\project\T&Go\Traccar\traccar\target\tracker-server.jar to C:\Users\hengsoheak\.m2\repository\org\traccar\traccar\3.9-SNAPSHOT\traccar-3.9-SNAPSHOT.jar
Installing D:\heng_sopheak\project\T&Go\Traccar\traccar\pom.xml to C:\Users\hengsoheak\.m2\repository\org\traccar\traccar\3.9-SNAPSHOT\traccar-3.9-SNAPSHOT.pom
Installing D:\heng_sopheak\project\T&Go\Traccar\traccar\target\tracker-server-jar-with-dependencies.jar to C:\Users\hengsoheak\.m2\repository\org\traccar\traccar\3.9-SNAPSHOT\traccar-3.9-SNAPSHOT-jar-with-dependencies.jar
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 32.070s
Finished at: Wed Feb 08 15:48:23 ICT 2017
Final Memory: 109M/762M


After run 

cd D:\heng_sopheak\project\T&Go\Traccar\traccar; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_121" cmd /c "\"\"C:\\Program Files\\NetBeans 8.2\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath org.traccar.Main\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_121\\bin\\java.exe\" -Dexec.workingdir= -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.2\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building traccar 3.9-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ traccar ---
Exception in thread "main" java.lang.RuntimeException: Configuration file is not provided please configure your server
	at org.traccar.Context.init(Context.java:183)
	at org.traccar.Main.main(Main.java:35)

**Comment by tananaev** [comment]
It seems like you haven't provided the config file.

**Comment by hengsoheak** [comment]
Where is it?

**Comment by tananaev** [comment]
It's wherever you create it. You can choose to use `debug.xml` as well, if you want.

**Comment by bilalcs** [comment]
In netbeans, r/click project. Go to properties->Run, and in arguments, specify debug.xml. Usually it is on root of the project. Please check attached image.
![netbeans-4](https://cloud.githubusercontent.com/assets/25174133/22733772/a13eed5e-ee0c-11e6-9dbe-3b24fc220eda.png)

**Comment by hengsoheak** [comment]
Now 

`
--- maven-assembly-plugin:3.0.0:single (assemble-all) @ traccar ---
Building jar: D:\heng_sopheak\project\T&Go\Traccar\traccar\target\tracker-server-jar-with-dependencies.jar

--- maven-install-plugin:2.3.1:install (default-install) @ traccar ---
Installing D:\heng_sopheak\project\T&Go\Traccar\traccar\target\tracker-server.jar to C:\Users\hengsoheak\.m2\repository\org\traccar\traccar\3.9-SNAPSHOT\traccar-3.9-SNAPSHOT.jar
Installing D:\heng_sopheak\project\T&Go\Traccar\traccar\pom.xml to C:\Users\hengsoheak\.m2\repository\org\traccar\traccar\3.9-SNAPSHOT\traccar-3.9-SNAPSHOT.pom
Installing D:\heng_sopheak\project\T&Go\Traccar\traccar\target\tracker-server-jar-with-dependencies.jar to C:\Users\hengsoheak\.m2\repository\org\traccar\traccar\3.9-SNAPSHOT\traccar-3.9-SNAPSHOT-jar-with-dependencies.jar
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 50.899s
Finished at: Wed Feb 08 17:46:17 ICT 2017
Final Memory: 65M/377M
------------------------------------------------------------------------
**The system cannot find the path specified.**`

**Comment by hengsoheak** [comment]
Now 

`cd D:\heng_sopheak\project\T&Go\Traccar\traccar; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_121" cmd /c "\"\"C:\\Program Files\\NetBeans 8.2\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath org.traccar.Main debug.xml\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_121\\bin\\java.exe\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.2\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 -Prelease-profile org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...

Some problems were encountered while building the effective model for org.traccar:traccar:jar:3.9-SNAPSHOT
'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing.
'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing.
'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing.

It is highly recommended to fix these problems because they threaten the stability of your build.

For this reason, future Maven versions might no longer support building such malformed projects.

                                                                        
------------------------------------------------------------------------
Building traccar 3.9-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ traccar ---
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO 2/8/17 6:04 PM: liquibase: Clearing database change log checksums
INFO 2/8/17 6:04 PM: liquibase: Successfully acquired change log lock
INFO 2/8/17 6:04 PM: liquibase: Successfully released change log lock
INFO 2/8/17 6:04 PM: liquibase: Successfully acquired change log lock
INFO 2/8/17 6:04 PM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO 2/8/17 6:04 PM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO 2/8/17 6:04 PM: liquibase: ./schema/changelog-master.xml: changelog-3.8::changelog-3.8-dropuniquetoken::author: Change set changelog-3.8::changelog-3.8-dropuniquetoken::author failed, but failOnError was false.  Error: Constraint "UK_USER_TOKEN" not found; SQL statement:
ALTER TABLE PUBLIC.users DROP CONSTRAINT uk_user_token [90057-193] [Failed SQL: ALTER TABLE PUBLIC.users DROP CONSTRAINT uk_user_token]
INFO 2/8/17 6:04 PM: liquibase: Successfully released change log lock
[main] INFO org.eclipse.jetty.util.log - Logging initialized @2191ms
[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.19.v20160908
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@602ae7b6{/api,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@4d8286c4{/console,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@7a7cc52c{HTTP/1.1}{0.0.0.0:8082}
[main] INFO org.eclipse.jetty.server.Server - Started @3433ms
`

**Comment by bilalcs** [comment]
Check this stackoverflow answer, may be it will help.
http://stackoverflow.com/questions/4123044/maven-3-warnings-about-build-plugins-plugin-version

**Comment by gutitoni** [comment]
I have the same problem as you solved it.
