### ISSUE TITLE
Create static location on the map

### ISSUE THREAD

**Issue by infinitsolutions** [traccar/traccar-web#409]
Hi, I need to create  static locations on the map similar to the "drop pin" feature in Google maps. This location represent the destination of each device. Does this feature exist? If not can this be implemented by code?

**Comment by tananaev** [comment]
There is no such feature at the moment. Anything can be implemented by code.

**Comment by infinitsolutions** [comment]
Hey, Thank for the reply.
What is the Lat, Lon fields in the create user form? Will that be displayed on the map?
Thanks Again!

**Comment by tananaev** [comment]
That's a default map location. That point would be centered when you open the app.

**Comment by infinitsolutions** [comment]
Hi Anton, Thanks again. I am setup to build the project now. I am trying to add an additional static marker to the map.. thats it.. Could you point me to where I should start?

**Comment by tananaev** [comment]
You can start with `MapController` class.

**Comment by satisharalkar** [comment]
@infinitsolutions , I have a similar requirement. Did you find the solution? if yes, can you please share.

**Comment by tananaev** [comment]
We have POI layer for this.
