### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by zadkiel123jose** [traccar/traccar-web#412]
Install the traccar server and my client drive but I could not see my device on the server, besides I got a message from websoket error that's all, what ports should I open on my router or is it only 8082 my server is in linux debian.

**Comment by tananaev** [comment]
Traccar Client should be configured to use port 5055. Not sure how you expect to see anything if you didn't even open that port.

WebSocket error means that you have some network issue which prevents WebSockets from functioning properly. Possibly it's blocked by the internet provider or a firewall.

**Comment by zadkiel123jose** [comment]
Thanks for the reply, the problem was the port can already receive the data
