### ISSUE TITLE
Grouping fields in dialogs 

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar-web#423]
I want to discuss how to group fields in edit dialog, let's start from User:

![image](https://cloud.githubusercontent.com/assets/5688080/23740437/628aefc0-04c5-11e7-916d-be6d4804b766.png)

Obligatory fields (red)
"Permissions" (blue)
"Map and Units" (green)

Do not know where to put "Phone" and "Token"

Possible future User timezone also put in "Map and Units"

**Comment by tananaev** [comment]
I propose similar split:

1. "Required" field. Same as your red.
2. "Other" or "Preferences". Green plus phone.
3. "Permissions". Blue plus token. Token is kind of related to permissions.

**Comment by Abyss777** [comment]
Here is draft, just grouped fields and reordered a bit
![image](https://cloud.githubusercontent.com/assets/5688080/23748675/6cea00ca-04e6-11e7-9b30-5505deebe0e7.png)

![image](https://cloud.githubusercontent.com/assets/5688080/23748723/a446664e-04e6-11e7-8174-97bfa52eaf5a.png)

![image](https://cloud.githubusercontent.com/assets/5688080/23748792/e12be4c6-04e6-11e7-847f-3a968412666d.png)

Faced with few problems

As you can see on screenshots, first 3 fields last not to the right border if one fieldset is expanded.
My suggestion is also group them in "not-collapsable" fieldset and name like "General"

Like this
![image](https://cloud.githubusercontent.com/assets/5688080/23748954/a3330c70-04e7-11e7-8592-1d2a87894fec.png)
![image](https://cloud.githubusercontent.com/assets/5688080/23749022/f379d308-04e7-11e7-9730-cec04f4dd5ab.png)

Another problem is by default if we expand fieldset the parent window will grow down and bottom buttons will be hidden out of browser window.
I see two options:
- center window on every expand/collapse [(window.center()).](http://docs.sencha.com/extjs/6.2.0/classic/Ext.window.Window.html#method-center) It looks nice, but if windows was previously moved somewhere it will jump to the center, then it looks like bug. We need also disable window dragging to look consistent.
- implement some function to center window only vertically

**Comment by tananaev** [comment]
I think instead of "General" we can call it "Required". I don't think it should be non-collapsable. Just make it expanded by default.

As for centering, maybe we can calculate the size of the window and re-center it only if it doesn't fit after expand.

**Comment by Abyss777** [comment]
OK.

Found better solution for buttons out of browser: http://docs.sencha.com/extjs/6.2.0/classic/Ext.window.Window.html#cfg-constrain

It will prevent move/expand window outside parent container (document.body)

**Comment by Abyss777** [comment]
Collapsed "Required" looks not very good
![image](https://cloud.githubusercontent.com/assets/5688080/23783110/c9fc0954-057a-11e7-82c7-2181350a226b.png)

**Comment by tananaev** [comment]
OK, I guess then it's better to make required category non-collapsable.

**Comment by Abyss777** [comment]
I was thinking about Server dialog next
![image](https://cloud.githubusercontent.com/assets/5688080/23795195/0d093678-05b6-11e7-83f8-4d445a28aebb.png)

Green - Permissions
Blue - Preferences

But there is no "noncollapsable" part

Device is simple

![image](https://cloud.githubusercontent.com/assets/5688080/23795270/7631304c-05b6-11e7-8c55-3cddf0e01933.png)

Red - Required
Blue - Preferences

**Comment by tananaev** [comment]
Agree. For server we can make permissions non-collapsable, so we don't get an issue with dialog size.

**Comment by Abyss777** [comment]
Not very good again

![image](https://cloud.githubusercontent.com/assets/5688080/23820237/5ec36f44-0636-11e7-8d80-f0618b565718.png)

![image](https://cloud.githubusercontent.com/assets/5688080/23820239/6539d2fa-0636-11e7-8543-d636198e5272.png)

**Comment by tananaev** [comment]
Maybe make preferences on top an not collapsable?

**Comment by Abyss777** [comment]
Looks good and initial size is OK

![image](https://cloud.githubusercontent.com/assets/5688080/23820368/9a6966aa-0638-11e7-9d34-f331a23dc265.png)

![image](https://cloud.githubusercontent.com/assets/5688080/23820371/a5cb52d8-0638-11e7-8bb4-6b3b008e6de3.png)

**Comment by Abyss777** [comment]
Do not think we need group fields in other dialog. Closing this.

A lot of place now for new fields :)

**Comment by tananaev** [comment]
What other dialogs do we have? I was thinking to add grouping to all of them for consistency. It can be a single non-collapsable group. I think it would just look nicer if they all look the same.

**Comment by Abyss777** [comment]
Group
Geofence
Calendar

Will we add groups to "Attribute" and "Attribute Alias" dialog?

**Comment by tananaev** [comment]
How about adding it to dialogs with more than 2 fields?

**Comment by Abyss777** [comment]
I like it, also because for group only name is Required and Group is optional. Two groups for two fields would look not very good.

Then only Geofense is left.

**Comment by tananaev** [comment]
Group has 3 fields.

**Comment by Abyss777** [comment]
What is third?
![image](https://cloud.githubusercontent.com/assets/5688080/23820877/8150de8a-0644-11e7-9d4c-c8e66748bf15.png)

**Comment by tananaev** [comment]
Sorry, I was thinking geofence... it has 3 fields. But now I'm thinking it would be nice to do group as well, to split required and optional fields. Does it look too bad?

**Comment by Abyss777** [comment]
Not perfect, but fine I think.

![image](https://cloud.githubusercontent.com/assets/5688080/23820964/3a34b6b8-0647-11e7-95bb-44411d239c2f.png)

![image](https://cloud.githubusercontent.com/assets/5688080/23820965/43ffca16-0647-11e7-90ea-6338662279a2.png)

**Comment by Abyss777** [comment]
Looks like we grouped all dialog with rule "more than two fields", closing this?

**Comment by tananaev** [comment]
I'm still thinking maybe we should make an exception for Group dialog, so we can highlight which fields are required and optional. What do you think?

**Comment by Abyss777** [comment]
Looks better than i thought 

![image](https://cloud.githubusercontent.com/assets/5688080/23830626/16545876-0731-11e7-9416-3a49a42be7ca.png)

![image](https://cloud.githubusercontent.com/assets/5688080/23830628/2668a92e-0731-11e7-999f-8b28cbb08016.png)

I think we can make it. OK?

And then for consistence make grouping for Calendar
![image](https://cloud.githubusercontent.com/assets/5688080/23830656/bb01951e-0731-11e7-941e-541618cfbb3c.png)

**Comment by tananaev** [comment]
Sounds good to me.
