### ISSUE TITLE
UI State Field

### ISSUE THREAD

**Issue by wolfbgn** [traccar/traccar-web#433]
Hi, Mr. Tananaev.
Is it possible to remove some  items in State field? For example VALID or IP.
Which files should I modify?
Also I have translated all lines in Bulgarian. Do you want me to upload the file somewhere for your use?

**Comment by tananaev** [comment]
Your should modify `StateController` class.

If you want to help with translation, please do it through Transifex:

https://www.transifex.com/traccar/traccar/

**Comment by wolfbgn** [comment]
I tried hard to do that but to no avail. Thank you anyway for the quick responce.
Still I think that this info is very usefull for the Admins but it should be possible to select in settings to hide or show it for the users by some user friendly way. Check box is good for dum persons like me.

**Comment by tananaev** [comment]
Let's keep it as a feature request. Maybe we can add some parameter to user attributes to list parameters that we want to show.

**Comment by wolfbgn** [comment]
I am sorry to bring that up again. I finally was able to remove some info from STATE pannel following your instructions and modifying StateController class . Thank you. The only thing I can not remove is IP Address. Please advise how to stop showing that info in state panel.
Thanks for your great work.

**Comment by tananaev** [comment]
It's all in the same class. IP address is in "attributes".

**Comment by wolfbgn** [comment]
Traccar displays time in "YYYY-MM-dd HH:mm:ss" format. Can I change it to "dd/MM/YYYY HH:mm:ss" and if possible where is to look?
Thank you.

**Comment by tananaev** [comment]
You can change date format in the `Style.js` file.

**Comment by wolfbgn** [comment]
Thanks
