### ISSUE TITLE
image backgroung for login

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar-web#436]
hello i would say is possible insert the image backgroung for login?

**Comment by tananaev** [comment]
It is possible. You would have to modify some HTML and possibly JavaScript code.

**Comment by netluca1** [comment]
You can kindly explain better what I have to edit html files and what should I put in the javascript code.

**Comment by tananaev** [comment]
Sorry, but I'm not going to teach you web development. You have to have certain technical skill and knowledge to do it.
