### ISSUE TITLE
Timezones list

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar-web#437]
There is no way to get list of timezones neither from ExtJS nor from pure JavaScript

I see two options:

- Implement some utility API in backend to get list via https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html#getAvailableIDs()
- Use some external source, like https://github.com/dmfilipenko/timezones.json 
May be not in runtime, just update it in every release

**Comment by tananaev** [comment]
We can probably hardcode a list somewhere. I don't think it's a very big list and it probably doesn't change that often.

**Comment by Abyss777** [comment]
At least 384 https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
It is not so hard to hardcode it, but it will be really hard to select it in interface.

We can use some shorter list:
- Microsoft https://msdn.microsoft.com/en-us/library/ms912391(v=winembedded.11).aspx
- Or just take one for every GMT+ and GMT- timezones

**Comment by tananaev** [comment]
Yes, I think we can start with a shorter list, and then add more if someone requests.

**Comment by tananaev** [comment]
Never versions have an API that gets timezone list direction from Java.
