### ISSUE TITLE
Feature request: Auto select device

### ISSUE THREAD

**Issue by wrobi** [traccar/traccar-web#439]
I'd like to automatically select device(s) after login.
I have only one device per user. After login (or app started) have to select device to follow.
Maybe it would be more convenient, auto select (all) device(s), and align center on map.
When it works, maybe it's possible to hide "Devices" title at bottom toolbar on Mobile view.

**Comment by tananaev** [comment]
I'll add my comment that it would be better to make it more generic and center all user devices. Similar like we do with report.

**Comment by Abyss777** [comment]
What should be main lat/lon/zoom or center to all devices?

**Comment by tananaev** [comment]
Good question. I'm thinking that if lat/lon/zoom are not specified, center devices automatically. What do you think?

**Comment by Abyss777** [comment]
Agree, good logic.

**Comment by Abyss777** [comment]
@tananaev 
It is not so simple, we do not have way to determine the first `positions` frame in the websocket at the moment. And I do not see a solution without some global variable.

**Comment by tananaev** [comment]
I don't think we need a global variable. Root controller can fire an event first time it receives the location data. Map would subscribe to the event.

**Comment by tananaev** [comment]
We already center/zoom device/devices by default.
