### ISSUE TITLE
Fuel Level not showing on trip report

### ISSUE THREAD

**Issue by jalvaradejo** [traccar/traccar-web#444]
I'm using the gps103 protocol and I've connected the tracker to the fuel sensor and I see the fuel level value in the device state but I don't see it in any of the reports, do I have to do something else to see it the reports ??

**Comment by tananaev** [comment]
What do you see in the state? As far as I know, GPS103 doesn't include a special fuel level field.

**Comment by jalvaradejo** [comment]
I'm using the TK103A and the TK103B, you activate what is called protocol 18 and it sends the fuel level. The data is placed in the position table of the DB under the attributes field this is an example ({"io1":"0","io2":"0","io3":"57.95%","ip":"187.210.247.26","distance":0.0,"totalDistance":31.49}) the "io3":"57.95%" is the one that indicates the fuel level, and in the report al i get is a dash ( - ). also when the fuel level drop rapidly it sends this message (alarm":"oilLeak",) also in the attributes field ({"alarm":"oilLeak","io1":"0","io2":"0","io3":"50.00%","ip":"187.210.247.26","distance":0.0,"totalDistance":3695.41}) but its not stored in the events, what can i do so i can se the fuel level in the reports ?

thanks for your time

**Comment by tananaev** [comment]
That's and IO field, not a dedicated fuel field, so Traccar doesn't include it in the report.

**Comment by jalvaradejo** [comment]
Could the IO fields be added to they report?

**Comment by tananaev** [comment]
I don't think it makes sense to add IO to the report. Instead we should implement some mapping from IO fields to appropriate sensors.

**Comment by jalvaradejo** [comment]
how could I map the 3 IO fields to a field in the DB ??

**Comment by tananaev** [comment]
What do you mean by "map"? Do you mean store?

**Comment by jalvaradejo** [comment]
So I found the class Gps103ProtocolDecoder, I can modify it there so I can store the 3 IO fields from the tracker in 3 different fields in the position table of the DB ??

**Comment by tananaev** [comment]
You would have to modify SQL queries, not protocol decoder.

**Comment by jalvaradejo** [comment]
Ok, if I add aditional fields to the position table in the DB will that generate problems else where ??

**Comment by tananaev** [comment]
I think it should not generate any problems.

**Comment by mosisgreat** [comment]
Hi Anton, 
I have a xexun XT008 tracker with a fuel sensor. I need help about how to display the fuel level at every position update. 

Here is what i get after decoding:
170425114837,+221774380381,GPRMC,114837.000,A,1443.4265,N,01726.6519,W,000.0,216.5,250417,,,D*7A,F,,imei:861508033264888,09,30.1,F:4.25V,1,140,33586,608,01,0084,51FE,Oil=100%,T=100,RFID=

Regards,

**Comment by tananaev** [comment]
@mosisgreat, your comment is completely off topic. Please create a separate thread. Also, if you want to support additional Xexun attributes, we would need protocol documentation.

**Comment by mosisgreat** [comment]
Thank you Anton,

I have edited the default.xml and added the oil property on 
<entry key='database.insertPosition'>...</entry>

I have also added the it in the position table.

Which additional files need to be edited please.?

**Comment by tananaev** [comment]
@mosisgreat, I asked you to not comment on this thread.

**Comment by mosisgreat** [comment]
Sorry did'nt notice i was on the wrong page.
