### ISSUE TITLE
"Attributes" meaning?

### ISSUE THREAD

**Issue by wolfbgn** [traccar/traccar-web#450]
I understand the function of  "Attribute Alias"
I can not understand the "Attribute" function which appears after selecting device and pressing Edit button.  In the little window left bottom corner is a button called "Attributes".
What it does?

**Comment by Abyss777** [comment]
Do you mean this button?
![image](https://cloud.githubusercontent.com/assets/5688080/24354297/a2807228-130a-11e7-9b66-1e4ab13e32cc.png)

All traccar objects has attributes. They used to store some additional parameters. Some of them listed here https://www.traccar.org/configuration-file/ with location "device" some only in the code.

**Comment by wolfbgn** [comment]
That is the button.
You mean that is the place to set Speed Limit for example?

**Comment by Abyss777** [comment]
Yes.

**Comment by wolfbgn** [comment]
Thank you
