### ISSUE TITLE
Traccar mobile view

### ISSUE THREAD

**Issue by wolfbgn** [traccar/traccar-web#451]
Hi, Mr. Tananaev.
This is not an issue rather questions.
1. Is it possible in mobile view when I select a device to see the address of the current position? It is much easier than to zoom to position and try to read the address from the map.
2. I see your point in adding a search box in the mobile interface if you have hundreds of devices but most of users have one or several devices at the most. What I mean is if it is possible to switch on and off this feature.
3. I could not get notification sound on iPhone 6s. That is what I tried. On other phones it might be heard. I do not know. As a matter of fact the sound is weak even on PC.
Thank you

**Comment by tananaev** [comment]
1. You can see address in the state panel. It's the one on the right. Collapsed by default.

2. This is already fixed. In the next release search will be available from column header and won't take any extra space.

3. There is no way to control sound volume from the app. You have to use regular volume settings on your phone.

**Comment by wolfbgn** [comment]
I tried iPhone 5, iPhone 6s, Samsung A5, HTC m8.
None of the above phones play the notification sound. On computer every thing is OK.
I even replaced the original beep.wav provided by you with another sound. No efect.
?

**Comment by tananaev** [comment]
Are you using app or mobile browser?

**Comment by wolfbgn** [comment]
Mobile browser

**Comment by tananaev** [comment]
Then it's most likely not possible. Mobile browser doesn't allow any sounds without touch events. I would recommend using Traccar Manager app.

**Comment by wolfbgn** [comment]
I just tried Traccar Manager on iPhone 6s. No sound.

**Comment by tananaev** [comment]
I guess it's not fixed on iOS version yet, but it should definitely work on Android.

**Comment by jon-stumpf** [comment]
Can you explain where the audio limitation presents itself when using Traccar Manager on iOS?

And, on Android, are there specific states when sound does not work?  E.g.,
- when app is in background
- when phone is locked

**Comment by tananaev** [comment]
There is no specific state. Android Manager should work. Android browser doesn't play sounds. On iOS I believe neither work.
