### ISSUE TITLE
Creating New User Problem

### ISSUE THREAD

**Issue by CCPlusIT** [traccar/traccar-web#460]
I am using the script below to create a new user on the traccar database version traccar-linux-3.10 when a customer registers on our website. Using curl we pass the Name, Email and Password. The code below is then used to add to user to the database, that is does successfully. The issue I face is that when you then try to login to the user account I get this error https://www.screencast.com/t/xeX7FJd63f Can you point me in the right direction as to why this error issue is occurring. 
Thanks in advance

<?php
$user_jason=file_get_contents('php://input');
$newuser = json_decode($user_jason,true);
	
$name=$newuser['name'];
$email=$newuser['email'];
$password=$newuser['password'];	

$string = mcrypt_create_iv(24, MCRYPT_DEV_URANDOM);
$salt = strtoupper(bin2hex($string));

$hash = hash_pbkdf2("sha1", $password, $string, 1000, 24, true);
$hash = strtoupper(bin2hex($hash));

mysqli_query($con,"INSERT INTO users (name, email, hashedpassword, salt, readonly, admin, map, distanceunit, speedunit, latitude, longitude, zoom, twelvehourformat, attributes, coordinateformat, pw) VALUES ('$name', '$email', '$hash', '$salt', '0', '0', 'osm', 'km', 'kmh', '0', '0', '15', '1', '{}', 'ddm', '$password')");
?>

**Comment by tananaev** [comment]
How do you add user to the database? You have to use API.

**Comment by CCPlusIT** [comment]
I sent the information from our website using curl as jason and chaptered in to a file and added with the mysql insert query

**Comment by tananaev** [comment]
Well, as I said, you should be using API for registering new users, not direct SQL queries.
