### ISSUE TITLE
Valid Column meaning?

### ISSUE THREAD

**Issue by joepr** [traccar/traccar-web#461]
Hello everyone

Sorry for this simple question I have been searching on the forum but not quite find a response yet.  What does Valid column stands for? Sometimes I get a Valid **No** under reports. 

![image](https://cloud.githubusercontent.com/assets/10345032/24523067/cf6ca0ac-155f-11e7-804d-e22270a11d94.png)

**Comment by tananaev** [comment]
It's a flag returned by GPS module directly. "No" means that GPS location is outdated, inaccurate or not available at all yet.

**Comment by joepr** [comment]
Thanks Anton.  I have a clear understanding now.

 Is there a way to disable this No Valid Data to be displayed or recorded on the server?

Do you think is a good practice to omit this information?

**Comment by tananaev** [comment]
You can enable filtering.

**Comment by joepr** [comment]
Thanks.  That option is located at traccar config file?

**Comment by tananaev** [comment]
Yes.

**Comment by joepr** [comment]
Anton

Sorry to ask. When I edit the file on /opt/traccar/conf/traccar.xml  my linux VPS  I cant find any of the filtering options shown on this link https://www.traccar.org/configuration-file/

Does all those options are not included by default on the traccar.xml file?

Thanks!

**Comment by tananaev** [comment]
Filtering is not in the config file by default. You have to add it to the config.

**Comment by joepr** [comment]
**Anton** 

Thanks for the reply. I was able to add the following info on the traccar.xml . I save the file and restart traccar. After a few hours I'm still getting the Valid False as you may see on the pic below

**Here is what I added to the config file**

```
<entry key='filter.enable'>true</entry>
<entry key='filter.duplicate'>true</entry>
<entry key='filter.invalid'>true</entry>
```
**Screenshot**

![image](https://cloud.githubusercontent.com/assets/10345032/24593677/bade3164-17f3-11e7-877e-517451e37cdc.png)

**Comment by tananaev** [comment]
It should work. Are you sure those locations were received after restart?

**Comment by joepr** [comment]
I will verify it tomorrow morning. 

Once again thanks!
