### ISSUE TITLE
Events in the event report  generated for groups not showing on the map

### ISSUE THREAD

**Issue by DanSkytrack** [traccar/traccar-web#464]
When generating an events report for a group,  clicking the individual events in the report does not show the position on the map.
Events report generated for individually selected vehicles  are OK.

**Comment by tananaev** [comment]
@Abyss777, can you please take a look.

**Comment by Abyss777** [comment]
Hello,
I can't confirm that.
It does not matter actually device or set of devices or group.
The only assumption is you have too much positions related to events and request fails.
Please check browser developer console.

**Comment by DanSkytrack** [comment]
Hi,
Yes, you are right; server responded: "Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)"
Thanks !
