### ISSUE TITLE
Web Interface Update Frequency

### ISSUE THREAD

**Issue by wolfbgn** [traccar/traccar-web#468]
I have a clean install of Traccar 3.10 on my test server. No modifications whatsoever.
I have an iPhone 6s connected to the Server with update frequency set to 10 seconds. I also have connected chinese GT06 device  with update frequency set to 30 seconds.
Server log shows that both devices send data correctly. The iPhone every 11 seconds, the chinese device every 31 or 32 seconds.
The time in UI window does not refresh at that rate. It changes very 61 seconds. That is for both devices. Also when it refreshes I get "Web Socket Connection Error".
I can refresh window manually every 10 seconds and then I get the correct time and position but still every time I get "Web Socket Connection Error". 
What is the problem?

**Comment by tananaev** [comment]
The problem is with WebSocket connection. It's blocked on some networks. If you are on corporate network, check with your IT department. If it's a home network, check with ISP if they block it.

**Comment by wolfbgn** [comment]
Thank you. Actually I realised that I get this error bacause my test server is proxied by Nginx and I have missed the configuration for WebSocket.

**Comment by alexportrj** [comment]
@wolfbgn Do you mind to share your nginx websocket config?

**Comment by wolfbgn** [comment]
location / {
         proxy_pass http://localhost:8082;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";

**Comment by gpproton** [comment]
Hi Anton, i've been trying for weeks and i have done lot of test but no success, i'm currently testing it on my windows server with http://localhost:8082 still no luck on stopping the error.
I'd appreciate any help.

**Comment by tananaev** [comment]
@gpproton, you should check browser developer console for more information on what's happening to the connection.

**Comment by gpproton** [comment]
Ok thanks @tananaev it was my mistake i did not enable <entry key='web.origin'>*</entry>

**Comment by ellinco** [comment]
Pls @**gpproton** where can i find web.origin and how can i eneable it

**Comment by gpproton** [comment]
<entry key='web.origin'>*</entry>

**Comment by gpproton** [comment]
But if you're using it on windows, and you also utilize reverse proxy you also need to install IIS module for web sockets and perform some settings to make it work.
