### ISSUE TITLE
SMS event configuration file sample

### ISSUE THREAD

**Issue by RobertoVillegasA** [traccar/traccar-web#469]
Hello Anton.

I'm trying to configure SMS but I'm not Sure how to, do you have some sample configuration in  config file for correct send sms notifications

regards and thanks a lot for all..

**Comment by tananaev** [comment]
What version of Traccar are you using?

**Comment by RobertoVillegasA** [comment]
3.10 last code compilation

**Comment by tananaev** [comment]
If you build it from master branch, it's not 3.10 anymore.

@Abyss777, do we have some SMS configuration example?

**Comment by Abyss777** [comment]
All possible parameters listed in https://www.traccar.org/configuration-file/ start from `sms.smpp.*`
Here is example:
````xml
 <entry key='sms.smpp.enable'>true</entry>
 <entry key='sms.smpp.host'>smpp.example.com</entry>
 <entry key='sms.smpp.port'>2345</entry>
 <entry key='sms.smpp.username'>systemId</entry>
 <entry key='sms.smpp.password'>password</entry>
 <entry key='sms.smpp.notificationsCharset'>GSM</entry>
 <entry key='sms.smpp.notificationsDataCoding'>0</entry>
 <entry key='sms.smpp.sourceAddress'>+79000000000</entry>
````

**Comment by RobertoVillegasA** [comment]
THANKS a lot ...
Regards.
