### ISSUE TITLE
Adding Xexun xt008 tracker's Oil attribute to traccar

### ISSUE THREAD

**Issue by mosisgreat** [traccar/traccar-web#478]
Hi Anton, 

I am using a Xexun Xt008 tracker that works perfectly on my server.
I have bought fuel sensor but  which displays correctly the percentage when i decode a position's information.

I need your help on how i can display the Oil attribute on traccar-web.
I am using Xexun protocol port 5006.

Here is a sample position:
```
2017-05-02 11:26:03 DEBUG: [0D220F69: 5006 < 41.82.2.152] HEX: 3137303530323130303335332c2b3232313737353033353138332c4750524d432c3130303335332e3030302c412c313434332e343234352c4e2c30313732362e363531352c572c3030302e302c3232352e302c3032303531372c2c2c412a37432c462c2c20696d65693a3836313530383033333236343838382c30392c33352e342c463a342e3234562c312c3134302c36343838312c3630382c30312c303038342c353230302c4f696c3d3138252c543d2d31362c524649443d0a0d
```
```
170502100353,+221775035183,GPRMC,100353.000,A,1443.4245,N,01726.6515,W,000.0,225.0,020517,,,A*7C,F,, imei:861508033264888,09,35.4,F:4.24V,1,140,64881,608,01,0084,5200,Oil=18%,T=-16,RFID=
```
Thanks in advance,
Regards,

**Comment by tananaev** [comment]
See https://github.com/tananaev/traccar-web/issues/444#issuecomment-297552371.

**Comment by mosisgreat** [comment]
Thank you Anton,

I have edited the default.xml and added the oil property on

<entry key='database.insertPosition'>...</entry>
I have also added it in the position table.

Which additional files need to be edited please.?

**Comment by tananaev** [comment]
It's not implemented in the protocol decoder. That's the first thing you need to do if you want to add support for those additional parameters.

**Comment by mosisgreat** [comment]
Thanks again Anton,

I am actually trying to add the regex in XexunProtocolDecoder.java as follow
` private static final Pattern PATTERN_FULL = new PatternBuilder()
            .any()
            .number("(d+),")                     // serial
            .expression("([^,]+)?,")             // phone number
            .expression(PATTERN_BASIC.pattern())
            .number("(d+),")                     // satellites
            .number("(-?d+.d+)?,")               // altitude
            .number("Oil=(d+)%,")               // Fuel level my line
            .number("[FL]:(d+.d+)V")             // power
            .any()
            .compile();`
But it keeps failing with the error:

`<testcase classname="org.traccar.protocol.XexunProtocolDecoderTest" name="testDecode" time="0.007">
    <failure message="position is null" type="java.lang.AssertionError">java.lang.AssertionError: position is null`

What is the problem please.

**Comment by tananaev** [comment]
Some unit test is failing.

**Comment by mosisgreat** [comment]
Hi Anton,
i have found that it is a problem with the matcher in the decode() method that returns null.

Parser parser = new Parser(pattern, (String) msg);
if (!parser.matches()) {
          return null;
}

The new pattern doesnt match with the String object. 

[PN]RMC,(?:(\d{2})(\d{2})(\d{2}))?\.?\d*,([AV]),(\d*?)(\d?\d\.\d+),([NS]),(\d*?)(\d?\d\.\d+),([EW])?,(\d+\.?\d*),(\d+\.?\d*)?,(?:(\d{2})(\d{2})(\d{2}))?,[^*]*\*[0-9a-fA-F]{2}(?:\r\n)?,([FL]),(?:([^,]*),)?.*?imei:(\d+),Oil=(\d+)%

GPRMC,.000,A,0.000000,S,0.0000,W,0.00,0.00,,00,0000.0,A*55,L,,imei:353579010727036,

How can i add the Oil property to make it match with the pattern?

**Comment by tananaev** [comment]
If you need to support messages without old property, then you need to make it optional in the pattern.

**Comment by mosisgreat** [comment]
Thanks this solved the problem. I am now able to position.setOil and position.getOil. 
What is the next step please?
How can i store it in the database now ?
How to display it on the web interface?

**Comment by tananaev** [comment]
Usually we store additional data in the attributes. If you want to store it in separate columns, you need to modify database and also add it to the SQL queries in the config.

**Comment by mosisgreat** [comment]
I have added the additional columns on the sql query and database.
Locally i can getOil from the position object but after building and uploading the tracker-server.jar on my server i get null values.

 
2017-05-06 20:24:05  INFO: com.mysql.jdbc.JDBC42PreparedStatement@32a82c4b: INSERT INTO positions (deviceId, protocol, serverTime, deviceTime, fixTime, valid, latitude, longitude, altitude, speed, course, address, attributes, accuracy, network, oil, temp, rfid)
        VALUES (2, 'xexun', '2017-05-06 20:24:05', '2017-05-06 21:02:30', '2017-05-06 21:02:30', 1, 14.730683333333333, -17.473108333333332, 0.0, 18.5, 164.2, null, '{"signal":"F","ip":"41.82.3.77","distance":114.46,"totalDistance":14901.02}', 0.0, 'null', null, null, null)

what can be the problem please?

**Comment by tananaev** [comment]
The problem can be anywhere. Compare to existing properties and find what's missing or different.
