### ISSUE TITLE
Web traccar does not load, it stays in the blue circle and at the end it opens connection error

### ISSUE THREAD

**Issue by junca15** [traccar/traccar-web#481]
I'm sorry for my English
First of all thank you very much.

My problem is that my web page does not load, it appears circling the circle and at the end a message says "connection failure" and I check the browser console and I get this error message "Uncaught TypeError: Can not read property 'mapCarto' Of undefined at app.min.js: 23 "

I need help, please.

Thank you

**Comment by tananaev** [comment]
Looks like you have some issue with your web app. I would recommend using official release.

**Comment by bamartinezd** [comment]
Hi,  @tananaev ... I have the same issue, the traccar service back-end runs successfully, but the traccar-web module in the project stays loading...
![traccarwebnotrun](https://user-images.githubusercontent.com/12103718/32256027-83e07716-be7a-11e7-97e9-6270274576d8.PNG)
![traccarwebnotrunlog](https://user-images.githubusercontent.com/12103718/32256028-83f5e5ba-be7a-11e7-8b28-ce1d85dc5258.PNG)

**Comment by tananaev** [comment]
Have you downloaded `traccar-web` git submodule?

**Comment by bamartinezd** [comment]
How can I proceed to do it? Is it necessary to clone "traccar-web" as a separate project?

**Comment by tananaev** [comment]
I would recommend you to study read about git submodules before you ask any further questions.

**Comment by bamartinezd** [comment]
Ok, Thanks
