### ISSUE TITLE
Admin account could all data

### ISSUE THREAD

**Issue by paraisotech** [traccar/traccar-web#483]
I was thinking here that it wouldn't it be a good idea if the admin account be able to see all data from the database? Geofences for example, the admin account(maybe only the one named admin) see all geofences created by all users, all atributes created by all other users, etc. I'm asking that because it would help so much in cases of users making some mistake on configuring them, being careless with case sensitive attributes, wrong geofences polygon...
Just an suggestion

**Comment by tananaev** [comment]
Admin does have access to all the data.

**Comment by paraisotech** [comment]
I know, but as I mentioned in my example I think it would be great if all
set geofences that were created by regular users,  the admin account see
them in available geofences list, maybe a checkbox to enable or disable see
all or only the ones who were created by the admin account.

Em 10 de mai de 2017 7:43 PM, "Anton Tananaev" <notifications@github.com>
escreveu:

**Comment by tananaev** [comment]
I don't think it's a good idea. On real servers you can have tens of thousand of geofences in total.

**Comment by paraisotech** [comment]
I agree with you. So is it possible to edit a geofence or an attribute
created by common user while logged as admin?

Em 10 de mai de 2017 10:28 PM, "Anton Tananaev" <notifications@github.com>
escreveu:

**Comment by tananaev** [comment]
Yes, you just need to temporarily link it to yourself.

**Comment by paraisotech** [comment]
Great.
Sorry for all my questions. My intention is to collaborate with you and
make Trac car better and better.

Em 10 de mai de 2017 11:09 PM, "Anton Tananaev" <notifications@github.com>
escreveu:
