### ISSUE TITLE
Identify my location (Geolocate)

### ISSUE THREAD

**Issue by joepr** [traccar/traccar-web#485]
I will like to know if there is a way to let Traccar show my location on the map by using the Geolocate-me option we have on many GPS systems. This will help many users to identify his location compare to the device he is tracking. 

Hope make sense my recommendation. 

![image](https://cloud.githubusercontent.com/assets/10345032/26073852/fa99ae22-397d-11e7-96b6-b06f3c0f4d2c.png)

**Comment by tananaev** [comment]
This information might be useful for implementation:

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

**Comment by N0RoM** [comment]
Any news about this?

**Comment by tananaev** [comment]
This is already available.
