### ISSUE TITLE
Position attributes formatting

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar-web#488]
I have some things to discuss...

I'm going to implement `PositionAttributes` store that will contain all known attributes from [Position.java](https://github.com/tananaev/traccar/blob/master/src/org/traccar/model/Position.java)
Also improve [AttributeFormatter.js](https://github.com/tananaev/traccar-web/blob/master/web/app/AttributeFormatter.js) and [StateController.js](https://github.com/tananaev/traccar-web/blob/master/web/app/view/StateController.js) to use this store.

For this purposes we need detailed type, like `distance`, `speed`, `voltage` etc. , but for the `ComputedAttributes` we need to know that it is only number. Split it to `type` and `subtype` or just assume that not-boolean and not-string is number?

Also I do not like that [KEY_BATTERY]([Position.java#L44](https://github.com/tananaev/traccar/blob/master/src/org/traccar/model/Position.java#L44)) can be number of volts and string with percents. I would split it to `KEY_BATTERY_VOLTAGE` and `KEY_BATTERY_PERCENTS` but we will have to shovel up all protocols again.

What do you think?

**Comment by tananaev** [comment]
Maybe we can have `dataType` (for `distance`, `speed` etc) and `valueType` (for `string`, `number` etc)?

As for battery, I think we should use `KEY_BATTERY` for voltage as most protocols report voltage and have separate `KEY_BATTERY_LEVEL` or something like that for percentage. It should be fairly easy to find which protocols report a string for battery value.

**Comment by Abyss777** [comment]
May be we also will not add `%` to `KEY_BATTERY_LEVEL` on the server side? It will be just number from 0 to 100. And format it on the web side.

**Comment by tananaev** [comment]
Totally agree. There is no point of adding percents on the server side if we know that it's battery percentage.
