### ISSUE TITLE
Add new option to see the last messages

### ISSUE THREAD

**Issue by chrystianmartins** [traccar/traccar-web#496]
Hello!

When we receive a "POP-UP" message it disappears in 3 seconds.
Sometimes we can not see this message.
So..

Could create a new option, to put the last messages .. can be the last 5 messages .. can be on the right side .. or together with the reports ...

Just an idea .. It would help a lot!

Thank you so much! Congratulations on the project!

**Comment by tananaev** [comment]
Good idea. I have been thinking about it for some time. We'll consider it for one of the next releases.

**Comment by tananaev** [comment]
We've implemented this some time ago.
