### ISSUE TITLE
Add "save custom commands" option,show stationary time and create sensors

### ISSUE THREAD

**Issue by bizkit1** [traccar/traccar-web#497]
Hello. 
It would be great to be able to save custom commands to the list, for later usage. 
Also it would be nice to show in the unit's status windows, for how long is stationary. I believe that this can be accomplished by adding some options for each unit like: Minimum Parking Time, so that you can differ parking from regular stops.
Another option would be to be able to create sensors for units based on incoming parameters. For example Teltonika devices + lv-can, to be able to create mileage sensors, fuel level sensors.....etc.

**Comment by tananaev** [comment]
Saving custom commands is definitely a good idea. I have heard this suggestion before.

Stationary time is probably lower priority.

As for the sensors, if I understand correctly, it's the feature that @Abyss777 is working on. Basically converting incoming raw IO data into something useful.

**Comment by bizkit1** [comment]
Yes, is what @Abyss777 is doing. Maybe this will also be useful for adding sensor data to reports, like for example if you have a mileage sensor, you can add Initial and Final Mileage for reports. Or fuel sensors, initial and final...etc.

**Comment by Abyss777** [comment]
Currently, for Trip Report `odometer` and `fuel` attributes are already used. You'll see not initial/final but difference.

**Comment by tananaev** [comment]
We have had saved commands for a while now.
