### ISSUE TITLE
ability categorize or group the devices list

### ISSUE THREAD

**Issue by HaniTetouha** [traccar/traccar-web#502]
Hello Dears,

First of all thank you for your hard work, I have noticed that when log in as admin and try to attach a device to a user account  all the devices on the server appear on the list that makes it very confusing and hard to maintain if you have hundreds of devices isn't it? 

Thanks again.

**Comment by tananaev** [comment]
You can filter by group or by keyword from column headers in the devices list.

**Comment by HaniTetouha** [comment]
Thank you for your reply, I can find what you have pointed out  but I am referring to the other device list tha modal thats pops up when try to attach a device to a user.
![screenshot 28](https://user-images.githubusercontent.com/16355884/26956384-7b732fa8-4cbd-11e7-93bd-df04e6281026.png)

**Comment by tananaev** [comment]
I see. Yes, there is no search functionality in that list at the moment. It would be a good idea to add it to all lists.

**Comment by HaniTetouha** [comment]
Yea that would be great thanks, I shall make a feature request for this?

**Comment by tananaev** [comment]
We can just keep this thread as a feature request.
