### ISSUE TITLE
Better error Presentation

### ISSUE THREAD

**Issue by HaniTetouha** [traccar/traccar-web#514]
Hello Dears,
Is it possible to make the error dialog more convenient by removing the second part of the message (like the SecurityException part in the screenshot), its a bit confusing  for normal user (none programmer).

![screenshot 24](https://user-images.githubusercontent.com/16355884/27647461-ca37b2b2-5c2b-11e7-8dd2-8717d0236cb3.png)

Thank you very much for this awesome work
best regards

**Comment by tananaev** [comment]
In the next version error dialogs will look different.

**Comment by HaniTetouha** [comment]
Great thanks :D
