### ISSUE TITLE
How connect traccar server to web UI 

### ISSUE THREAD

**Issue by neroshin** [traccar/traccar-web#515]
Hello folk how can I able to connect the traccar web to traccar server . I have already of both file but not sure how to communicate these server and web UI , could you help me?

-romano

**Comment by neroshin** [comment]
I am using window 10 and nebeans IDE compliler.

**Comment by neroshin** [comment]
I figure out the attach debugger have JPDA , last question I get the JPDA of the traccar but it said "handshake failed - unrecognized message from target VM" here the image of JPDA configuration http://prntscr.com/fpi651

**Comment by tananaev** [comment]
I'm confused with what you are trying to do. To debug Java code just click debug in NetBeans.

**Comment by neroshin** [comment]
I am trying to connect the server to web app. I several time to connect the JPDA of traccar it alway failed. really not sure what is mistake in step.
I tried to debug first the server, get the JPDA Address and Port for socket connector listener then put to the "attach the debugger" of traccar web but failed in my end.

**Comment by tananaev** [comment]
Official web app is written in JavaScript, so it doesn't make sense to try to connect to it using Java debugging tools.

**Comment by rodrigocastrillon** [comment]
@neroshin:
1. Copy the contents of traccar-web/web into traccar folder.
2. Start the server.
3. In browser, connect to https://traccarIP:8082/debug.html

The debug file renders the uncompressed JS files from web folder.

**Comment by gnkafridi** [comment]
i am copy these files into new directory called traccar and then run the command node and see in browser localhost:8080 nothing to happen anything. is there missing anything in these steps?
