### ISSUE TITLE
New Feature Suggestion

### ISSUE THREAD

**Issue by Turbovix** [traccar/traccar-web#516]
Anton if there was a way to save a list of custom commands would be great, especially if it were possible to assign a given command to a particular vehicle entering or leaving a particular geofence fence.
Would it be feasible for future versions?

**Comment by tananaev** [comment]
I remember someone already asked about something similar. Was it you or someone else?

**Comment by Turbovix** [comment]
Regarding the possibility of saving a custom list of commands, it was someone else.
As for using this list of custom commands and linking to a virtual fence (geofence) is mine!

**Comment by Abyss777** [comment]
It is also mentioned here https://github.com/tananaev/traccar-web/issues/497

I want to discuss this a bit.
On the one hand it should not be very complex feature, but on the other hand if we decide store them on server side such "CustomCommands" should have relations to both devices and users I would say have `ExtendedObjectsManager`

@tananaev  how do you see this feature? Any thoughts appreciated.

**Comment by tananaev** [comment]
I think commands should definitely be per user. Most users will have devices of the same model, or small variation of models, so there is a good chance that commands will be the same for all their devices, unless command also includes device unique id.

I guess linking commands to devices/groups and users will solve both problems. If commands are the same, they can be assigned to group of devices. If command includes some device-specific information, it can be linked to a specific device.

**Comment by Abyss777** [comment]
Remembering we shortened "Computed Attribute" to just "Attribute" inside how will we call "Custom Command" object? "Command" is busy.

**Comment by tananaev** [comment]
Can we re-use same command object? It's basically pre-populated command, right?

**Comment by Abyss777** [comment]
You are right. I think we can. It has attributes for everything and even has mark for if it is SMS.

Oh, I have an idea. We can go further. And implement some way of limiting users to send commands for example:

- Implementing `CommandsManager` based on `ExtendedObjectManager` for store and control (now it will be really easy)
- Add to server/user flag like "Commands Limited". Such user can not create new commands and send custom. but only send commands he has access and only to devices the command linked.
- With default behavior user can create new commands and store them and link to everything he has access, or just send without saving.

**Comment by tananaev** [comment]
If you think it's really easy, then I don't see why not.

**Comment by Abyss777** [comment]
After refactoring amount of code will be not big, much less then before.

**Comment by Abyss777** [comment]
@tananaev 
I've almost finished this feature, stuck in choosing icon for buttons

Now a have this, on device panel left one for linking command to device, right one to send command. Not very clear.
![image](https://user-images.githubusercontent.com/5688080/30316640-548cf8d4-97c1-11e7-84dd-ce5d93a40608.png)

Any suggestions are welcome

**Comment by tananaev** [comment]
Do we really need a separate button for it?

**Comment by Abyss777** [comment]
Unfortunately yes, we have to split linking commands to device from sending command.
List of commands that can be sent absolutely different from list of linked to device.

Just thought, may be a dropdown menu (like settings menu) with two items "Send" and "Link" ?

**Comment by tananaev** [comment]
Can we add extra button to the "send command" dialog? That would save space on toolbar and it seems like a good place for it.

**Comment by Abyss777** [comment]
Like this
![image](https://user-images.githubusercontent.com/5688080/30318407-776c09d0-97c6-11e7-8097-f60ae17f60c0.png)

What caption will fit more?

**Comment by tananaev** [comment]
What do we call this feature in other places? Maybe "Saved Commands" or "Custom Commands"?

**Comment by Abyss777** [comment]
I used just "Commands". We might call it "Saved Commands". I think "Custom Commands" is not fit, because it might intersects in mind with commands with type `TYPE_CUSTOM`

**Comment by tananaev** [comment]
Sounds good to me. Let's call it saved commands.

**Comment by tananaev** [comment]
It's already implemented.
