### ISSUE TITLE
Field 'radius' doesn't have a default value

### ISSUE THREAD

**Issue by neroshin** [traccar/traccar-web#517]
Hello folk, I have eccountered some error from web, MySql is correct username and password but it said  "Field 'radius' doesn't have a default value - SQLException". 
 somebody can help me to solve this issues check the image here http://prntscr.com/fqwyp3

**Comment by tananaev** [comment]
Are you sure you are using official Traccar release without any modifications?

**Comment by neroshin** [comment]
yes @tananaev it's no modifications , the location update of device is working to my end but I can't add a goefence from setting, im using the latest web traccar-web-3.11

**Comment by tananaev** [comment]
Official version doesn't have a `radius` column. So, either you are not using official version or you modified the database schema.

**Comment by neroshin** [comment]
Thanks @tananaev it's working now I drop the database and re run it , last question @tananaev I'm looking for API request I want to add a geofence for user with area circle in location via http request  ,do you think it possible?

**Comment by tananaev** [comment]
Official web app allows you to do that, which means it's possible.

**Comment by neroshin** [comment]
Thank you very much @tananaev
