### ISSUE TITLE
Feature Request : API & Web access to Media Files

### ISSUE THREAD

**Issue by jaimzj** [traccar/traccar-web#518]
With the support of media files for certain protocols including gt06/x1.

If not already done, It would be nice to have API access to the media files.

Additionally even ability on web to view the media content

Wasn't sure if this post should go on web or app, so posted it here.

**Comment by tananaev** [comment]
Good idea. We just need to make sure to check permissions, so that user can only access media files from the devices they own.

**Comment by tananaev** [comment]
I believe it's already available.
