### ISSUE TITLE
Impossible to Know full Address (when its a bit lengthy) in Web and mobile views.

### ISSUE THREAD

**Issue by sebdigo** [traccar/traccar-web#522]
All items under STATE (including address) has exactly one row. I think, if lengthy addresses could automatically take more rows, it will be fixed..
![address](https://user-images.githubusercontent.com/13304351/27950055-7ee74888-631d-11e7-9cd4-cdfbb747a17d.PNG)

**Comment by tananaev** [comment]
I think there can be a tooltip with full text, but I don't like an idea of expanding the cell.

**Comment by sebdigo** [comment]
Addrees, Speed, Event, Time . These are the FIrst things one needs to know. Making these instantly visible (Full address is very essential) and all others inside an 'More Details' button was a very good thing in my opinion.

The present setup with all details is very much confusing for a normal user.

**Comment by tananaev** [comment]
That's your opinion. Some users care more about additional sensor information, so I don't see much reason for hiding it.

**Comment by sebdigo** [comment]
Then how about an editable arrangement and possibility to hide unwanted items,
 drag and arrange upon one's priority.

**Comment by tananaev** [comment]
That makes more sense.

**Comment by sebdigo** [comment]
Thank you for considering :) 

Now how to make that possible. ?

**Comment by tananaev** [comment]
Basically there are 3 options:

1. You can implement it and send a pull request
2. You can wait till we implement it
3. You can sponsor the work to make it faster

**Comment by tananaev** [comment]
This issue doesn't exist in the modern app. We wrap text as needed.
