### ISSUE TITLE
send failed

### ISSUE THREAD

**Issue by bilalsaeed18** [traccar/traccar-web#523]
when i am testing traccar server from my android device, it consistently showing send failed in android app, and map doesn't updating on server. need help

**Comment by tananaev** [comment]
It means that your phone can't connect to your server, or server doesn't acknowledge the message. Possible causes:

1. Wrong configuration in the app
2. Some network config issue (route or firewall)
3. Device is not registered on the server

**Comment by bilalsaeed18** [comment]
so how would I connect my phone to server ? help me out 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Anton Tananaev <notifications@github.com> Date: 08/07/2017  12:40  (GMT+05:00) To: tananaev/traccar-web <traccar-web@noreply.github.com> Cc: bilalsaeed18 <bilalsaeed18.bs@gmail.com>, Author <author@noreply.github.com> Subject: Re: [tananaev/traccar-web] send failed (#523) 
It means that your phone can't connect to your server, or server doesn't acknowledge the message. Possible causes:

Wrong configuration in the app
Some network config issue (route or firewall)
Device is not registered on the server


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tananaev/traccar-web","title":"tananaev/traccar-web","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tananaev/traccar-web"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tananaev in #523: It means that your phone can't connect to your server, or server doesn't acknowledge the message. Possible causes:\r\n\r\n1. Wrong configuration in the app\r\n2. Some network config issue (route or firewall)\r\n3. Device is not registered on the server"}],"action":{"name":"View Issue","url":"https://github.com/tananaev/traccar-web/issues/523#issuecomment-313840875"}}}

**Comment by tananaev** [comment]
Please carefully read my previous comment. You need to find what the problem is first.
