### ISSUE TITLE
Idea: options to disable certain features

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar-web#525]
We have a lot of features that are domain specific. For example, fuel-related, drivers (coming soon) and other that are relevant to vehicle tracking only. Customer that wants to track other people or animals is not interested in those features. It would be nice to make an option to disable/hide those features.

**Comment by Abyss777** [comment]
Something like server/user option "Disable vehicle features" ?

We need to make a list what should be disabled...
- Drivers
- Spent Fuel and Engine Hours columns in reports (should it be spread on Export?)
- Device Distance ? (it is for admins, do not thing should be disabled)
- Commands ? (it might be used for device configuration, not for start/stop engine)
- Events: `deviceOverspeed`, `deviceFuelDrop`, `ignitionOn`, `ignitionOff`, `maintenance`
Should they just be ignored on web side or even not produced on server?
- ...

**Comment by tananaev** [comment]
I think it can probably be server-wide, but per user might be useful as well. I think we can think of meaningful pieces of functionality that can be disabled. For example, Calendars might not be useful for everyone. Then any vehicle-related (fuel, distance?). Reports in general as well. In many cases people just want to see live data and don't need or don't want user to be able to see history. Basically we can make all major features configurable. What do you think?

**Comment by sebdigo** [comment]
The above things are good.
I would suggest the following too.

- Option To add More columns like Speed, Ignition, other sensor etc to 'Devices Tab' , So that its possible to sort running units, overspeeding vehicles,units that have switched on A/C or other sensors .

- Option to hide some tabs completely from 'State tab'. like Protocol, IP, lat long or any other sensor values
 (If admin/user hides it all users under him wont even know of such a row).

**Comment by tananaev** [comment]
First point should be a separate feature request.

Second point totally makes sense. Maybe we can have a way to black-list and/or white-list state parameters. In many cases end user only want to see basic information like speed, address etc, not IP address or protocol name.

**Comment by Abyss777** [comment]
@tananaev totally agree. We should make all things configurable and invent some mechanism to notify web client about capabilities available. May be separate API request or pass it with Server object.

**Comment by tananaev** [comment]
I think it can be server attributes. This way we can make them configurable per-user as well.

**Comment by Abyss777** [comment]
Disable user access to some features in his attributes not very convenient. It is hard to split attributes he can change and he can not. I think only admin/manager will be able change them. The security check will be monstrous.
May be better add some additional field to Server/User like "Capabilities" that will be also JSON (like attributes)

**Comment by tananaev** [comment]
No, we should allow user to change all attributes. It's just for feature-related attributes server settings will take precedence. Basically if server attribute is set to disabled, it's disabled no matter what user attribute says.

**Comment by tananaev** [comment]
Kind of opposite of how other attributes work, but it should be very easy to implement.

**Comment by tananaev** [comment]
Just want to clarify, I think it should not be server-side security check. It's mostly for user convenience some features can be hidden. I think implementing checks on server side would be too much effort and it will complicate things too much.

**Comment by Abyss777** [comment]
I was thinking about 
>  don't want user to be able to see history
This feature should be switchable by admin/manager only.

**Comment by tananaev** [comment]
I guess it would make sense in some rare cases, but I just don't want to complicate server permissions any more. In most cases customers just want to hide unnecessary complicated or irrelevant data from end users.

**Comment by Abyss777** [comment]
OK. Got it.

**Comment by sebdigo** [comment]
If a USER disable some features, will the Readonly/Device Readonly users under him be able to see those features.? 

If it will be hidden from all of his subusers, when a user hides features, then it is better to make these changes from user side .

Else i think it wont be of any use, unless it could be changed from server side.

**Comment by jon-stumpf** [comment]
+1 I am interested in this capability.

**Comment by thiagoaraujo84** [comment]
This is an interesting discussion. It's important to remember that there are user-level and other device-level features. For example:

Use Case 1: I am a user who monitors only people, animals and objects. For me it's not interesting to see driver's features and commands (maybe).

Use Case 2: I am a user who monitors vehicles and people. For me it is interesting to see the features of drivers, fences, commands. But the attributes and commands are distinct for vehicles and people. For example, it does not make sense for a portable tracker to have the command "block" in the list of commands.

Use Case 3: I am a user who only monitors vehicles. For me it is interesting to see all the features.

As a suggestion, I imagine that one possibility to implement this functionality visualization treatment could be through the use of user attributes, just as it is done with device attributes. Perhaps a set of true / false attributes would only be resolved on the client side of the application.

**Comment by tananaev** [comment]
This thread is mostly about Case 1, which I think is the most important.

Case 2 - I think this is both rare and minor issue.

Case 3 - This is now it's already working.

**Comment by SiddiqueAhmad** [comment]
any plan to hide reports users wise?

**Comment by tananaev** [comment]
We are considering it.

**Comment by tananaev** [comment]
This is already implemented.
