### ISSUE TITLE
Modifications to 'Device list'

### ISSUE THREAD

**Issue by sebdigo** [traccar/traccar-web#526]
Hi , Creating a new thread as suggested by Anton.

- Add More columns like Speed, Ignition, any other sensor to 'Devices' tab.

- Possibility to sort devices based on Speed and  other sensors. So that users can find the fastest/slowest vehicle, running vehicles, vehicles that have switched on a/c.

- Show time since last change for digital sensors like ignition, di1,di2 etc.

**Comment by discofrenzy** [comment]
hi there ! 
i am looking for the same as sebdigo , looking to add more columns mainly ignition on/off , current address , and speed .
thankyou

**Comment by tananaev** [comment]
I remember this was asked somewhere before. The problem is that all that information is in "position" model, not "device" model.

**Comment by gpproton** [comment]
But really there should be a way to get these, and i think most recent address column would be very helpful.

**Comment by tananaev** [comment]
Of course there is. I'm just saying that it's not as easy as it might seem.

**Comment by Shragel** [comment]
Any update on this. Would be very helpful.

**Comment by tananaev** [comment]
Modern app has some additional information in the list.
