### ISSUE TITLE
I would be enquiring, that 1 VPS 2 traccar server it's possible?

### ISSUE THREAD

**Issue by BRTAXI** [traccar/traccar-web#530]
Hello Anton!

I would be enquiring, that 1 VPS 2 traccar server it's possible?

Thank you.

**Comment by tananaev** [comment]
It's possible, but you would need to modify wrapper configuration.

**Comment by BRTAXI** [comment]
Thank you for the answer, possibly an example config?

**Comment by tananaev** [comment]
I don't have an example, but you can find full documentation here:

http://yajsw.sourceforge.net/YAJSW%20Configuration%20Parameters.html

**Comment by BRTAXI** [comment]
I am not an expert this much :-D Thank you.
