### ISSUE TITLE
Suggestion: view position currently displayed in state panel on Google Maps.

### ISSUE THREAD

**Issue by gustavofcalmeida** [traccar/traccar-web#541]
The state panel shows a single position be it the last from the currently selected device, or a random point selected from the report panel. On the top right of the state panel there is a tag icon. Next to it there could be a "View on Maps" icon that simply launches a new tab with a [URL](https://developers.google.com/maps/documentation/urls/guide#search-action) like:
https://www.google.com/maps/search/?api=1&query=55.752986,37.611347

This would be useful because the user could easily benefit from changing layers and street view. Plus, no need for license keys or maps api calls.

**Comment by oliv3** [comment]
+1, already suggested such a feature but no skills on my side for that yet 

Le 5 août 2017 17:46:23 GMT+02:00, gustavofcalmeida <notifications@github.com> a écrit :
>The state panel shows a single position be it the last from the
>currently selected device, or a random point selected from the report
>panel. On the top right of the state panel there is a tag icon. Next to
>it there could be a "View on Maps" icon that simply launches a new tab
>with a
>[URL](https://developers.google.com/maps/documentation/urls/guide#search-action)
>like:
>https://www.google.com/maps/search/?api=1&query=55.752986,37.611347
>
>This would be useful because the user could easily benefit from
>changing layers and street view. Plus, no need for license keys or maps
>api calls.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tananaev/traccar-web/issues/541

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by oliv3** [comment]
Was thinking of opening a new tab with Google street view at first, especially for riders that go to unfamiliar locations, for an example 

Le 5 août 2017 17:46:23 GMT+02:00, gustavofcalmeida <notifications@github.com> a écrit :
>The state panel shows a single position be it the last from the
>currently selected device, or a random point selected from the report
>panel. On the top right of the state panel there is a tag icon. Next to
>it there could be a "View on Maps" icon that simply launches a new tab
>with a
>[URL](https://developers.google.com/maps/documentation/urls/guide#search-action)
>like:
>https://www.google.com/maps/search/?api=1&query=55.752986,37.611347
>
>This would be useful because the user could easily benefit from
>changing layers and street view. Plus, no need for license keys or maps
>api calls.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tananaev/traccar-web/issues/541

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tananaev** [comment]
This is already implemented in the modern app.
