### ISSUE TITLE
Admin unable to assign device to user account

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar-web#544]
Admin user is unable to assign/remove device from another user account.

When I try it comes up with 404 error in GUI.

>URI: /api/permissions/devices
>Method: DELETE
>Status: 404

It would be good if device could be created from user interface instead of having to add it first to your own and also an overall device management window..

**Comment by tananaev** [comment]
What version are you using?

I don't understand your suggestion. Devices can be created from user interface, obviously, so I'm not sure what you mean. What is "overall device management window"?

**Comment by tsmgeek** [comment]
Using latest git build for server jar and the webinterface was from latest release, im just updating the jar?
Have the two diverged the api? If so then ile need to setup a ext builder on my system to merge app.min.js.

What I meant was a single dialog that shows all registered devices on the system with some basic info (online, registered, last updated etc) and allows creating new devices before they are assigned to a user.
If someone wanted to register a device for someone else they would have to create it on their own account then go into users and find user then assign it to them and remove it from their own account.

**Comment by tananaev** [comment]
I wouldn't recommend mixing master branch with last release. There were some significant modifications.

OK, so you are asking to have an option to register devices from device permissions dialog. Am I understanding it correctly?

**Comment by tsmgeek** [comment]
Option in settings menu 'Devices'. For admin this would be all devices in the system, searchable.
-- in that dialog it would allow adding new devices using same dialog that exists for creating them
-- also allows viewing and assigning this tracker to registered users

I can see that there may be enough APIs to do this through the web interface but a few things in the API are are missing, things like pulling back a single device/user record by ID or search on a device, I may expand that a little as without it searching though large amount of devices will be a faf without it, ext supports remote sorting/filtering etc quite easy i like it but ive been stuck on 3.4 at work for several years now.
