### ISSUE TITLE
gps306 fuel level and others obd values

### ISSUE THREAD

**Issue by ekofficiel** [traccar/traccar-web#547]
Hi Anton. Thank you for your excellent job. I want to know if fuel level and others obd values of gps 306 tracker are stored in the db and how to recover them through api. Thanks.

**Comment by tananaev** [comment]
Model number doesn't tell me much. Do you see those values in the web app? If yes, then they are stored in the database. All additional data, like fuel info, is stored in `attributes` column.

**Comment by ekofficiel** [comment]
Thank you for your quick answer. It's an obd gps tracker from coban (a chinese brand). I don't see the values in the web app. So is there a column for each additional data in attributes. How to recognize each of them?

**Comment by tananaev** [comment]
All additional values are stored in JSON format in a single column. If you don't see them in UI, you won't see them in the database either.

**Comment by ekofficiel** [comment]
Ok I see thank you.
So one last question. I'm not so good i java, but i want to customize the web app. So, according to you, what's the best language to iteract with traccar api from my website. Thanks.

**Comment by tananaev** [comment]
Web interface is written in JavaScript, not Java. And I think it's pretty much the only option for a dynamic website.

**Comment by ekofficiel** [comment]
Is there a particular library you can advice me for fast and easy rest api consumption in js?

**Comment by tananaev** [comment]
Pretty much any library, or even pure browser API should do.

**Comment by ekofficiel** [comment]
I can easily use gmap or osm to display devices locations. but how to give to the user the choice between them. I mean is there a unique library that can interact with all those map providers?

**Comment by tananaev** [comment]
You can use Leaflet or OpenLayers, but your questions are getting off-topic. If you have any Traccar-specific questions, feel free to ask them here. For any other questions there are plenty of resources where you can get help.

**Comment by ekofficiel** [comment]
I know there is somethig like leaflet.js, but what did you use as unique map provider especially in version 3 please.

**Comment by tananaev** [comment]
We are using OpenLayers.
