### ISSUE TITLE
Ajax cross domain request to traccar api

### ISSUE THREAD

**Issue by ekofficiel** [traccar/traccar-web#549]
Hello Anton. I want to use traccar as backend and i have some problems with Ajax cross domain request to traccar api for realtime tracking. What can id do to bypass this restriction?

**Comment by tananaev** [comment]
Are you sure you configured origin?
```xml
<entry key='web.origin'>*</entry>
```

**Comment by ekofficiel** [comment]
I kept all the default vaulues.

**Comment by tananaev** [comment]
Well, default values don't allow CORS, so you need to configure it.

**Comment by ekofficiel** [comment]
Can you tell me how please?

**Comment by tananaev** [comment]
What do you mean? I have provided configuration parameter in the first comment.

**Comment by ekofficiel** [comment]
So you mea that is the only config to make an ajax call from my domain?

**Comment by tananaev** [comment]
Yes, as far as I know.

**Comment by ekofficiel** [comment]
Ok i'll it try and will let you know. Thanks.

**Comment by LucasBSC** [comment]
Hello Anton,

I added this parameter on the server side but the ajax request still returns CORS error. Following is the snippet on the client side and the error below:

```
const getDevices = () => {
    $.ajax({
        type: 'get',
        url: 'https://xxx.xxx.com/api/devices/',
        headers: {
            "Authorization": "Basic " + btoa("USER" + ":" + "PSW" )
        },
        xhrFields: {
            withCredentials: true
        },
        crossDomain: true,
        success: function (response) {
            console.log(response);
        }
    });
}
```

ERROR:

> Failed to load https://monitoramento.interakt.com.br/api/devices/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access.

What could I try different?

**Comment by LucasBSC** [comment]
Still stucked on this issue 👎

Follows the actual request/response headers. No response available, same error logged in console as mentioned before

![troublerequests](https://user-images.githubusercontent.com/32658387/46168341-93671e80-c26e-11e8-8b40-7dbbedcc0229.PNG)

If someone has solved it, would appreciate to know how.

Thanks

**Comment by LucasBSC** [comment]
I used the same code but with the 'demo.traccar.org/api/devices' url and it worked normally!

The only difference between my version and the demo I believe it is the SSL. Should it have something to do with?

**Comment by LucasBSC** [comment]
Sorry for the long time with no response. I got to do this using axios

[https://github.com/axios/axios](url)

I used a really simple code to return devices from Traccar, if anyone needs it follows sample:

```
usingAxios() {
        axios({
            method: 'get',
            url: "https://xxxx.xxxx.com/api/devices/",
            auth: {
                username: 'fgmuricy@giron.com.br',
                password: '123456'
            }
        }
        ).then(function (response) {
            console.log(response)
        })
    }
```

Thanks.

**Comment by mujeebasif** [comment]
For windows i downloaded traccar server & web (v4.6). 
even after adding 
`<entry key='web.origin'>*</entry>`
in traccar.xml & restarting traccar service
i was unable to by pass CORS error
exact error was:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8082/api/server?_dc=1568715535428. (Reason: missing token ‘x-requested-with’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

as mentioned in error, header named
> ‘x-requested-with'

being sent automatically by browser, which is not allowed by server
https://github.com/traccar/traccar/blob/v4.6/src/main/java/org/traccar/api/CorsResponseFilter.java
> private static final String HEADERS_ALL = "origin, content-type, accept, authorization";

so my temp solution was
add param 
`useDefaultXhrHeader: false,`
in `Ext.Ajax.request({`
https://docs.sencha.com/extjs/6.0.2/modern/Ext.Ajax.html#cfg-useDefaultXhrHeader
e.g.
`
Ext.Ajax.request({
scope: this,
            url: 'http://localhost:8082/api/server',
            useDefaultXhrHeader: false,
            callback: this.onServerReturn
        });
`
because  i can't mess up with server code, for which i need java sdk, maven,.. e.t.c to build.
