### ISSUE TITLE
FR: Fallback cartography

### ISSUE THREAD

**Issue by 9662** [traccar/traccar-web#563]
User story:

> As a user of a custom map[(s)](https://github.com/tananaev/traccar/issues/3490) with local coverage only, I would need the ability to designate a fallback map that would be shown in areas not covered by the custom local map.

**Comment by 9662** [comment]
Note: this can be generalised to a list of tile servers instead of a single fallback, which case would provide for redundancy even in cases of maps with global coverage.

**Comment by tananaev** [comment]
I believe this can be done use a tile server outside of Traccar. There doesn't seem to be enough interest to implement it directly in Traccar.
