### ISSUE TITLE
Tooltips for the options of "Account" and "Server" menu

### ISSUE THREAD

**Issue by gustavofcalmeida** [traccar/traccar-web#564]
Most of the icons that perform actions have tooltips.
The "Account" and "Server" menus have some of the most important settings for the server and user. But it's not always clear what is at stake when you change something.

I think "force setting", "registration", "read only" and "device read only" are the ones in more need for a tooltip.

About "force settings". I don't get it. I thought that server settings were always "forced" into users with default value. Then I thought that maybe "forcing" means the user can't change the setting to some custom value. But no, I could change the coordinate format, for example, to a different value than server. So I don't know what it does.

**Comment by tananaev** [comment]
It sounds like you want some documentation. I don't understand what tooltips have to do with it.

**Comment by gustavofcalmeida** [comment]
A tooltip is a type of inline documentation. Not as simple as the word "Readonly" but not as complex as an entire paragraph in an user manual.

A simple tooltip like "Only admins can add devices" to a checkbox labeled "device readonly" is worth an entire manual page.

**Comment by tananaev** [comment]
At the moment we only use tooltip as titles for icon-only buttons. What you are proposing would require to change it everywhere. I can see a value in it, but it's a big change. UI has to be consistent. I don't want to add long tooltips selectively in a few places only.

**Comment by tananaev** [comment]
That's a standard tooltip from ExtJS library. We didn't add it there.

**Comment by tananaev** [comment]
Eventually we'll add more documentation. I don't think it makes sense to add more help directly into the app. It will cause localization headaches.
