### ISSUE TITLE
Equal tooltips and icons for different actions confuse the user.

### ISSUE THREAD

**Issue by gustavofcalmeida** [traccar/traccar-web#565]
![sem titulo](https://user-images.githubusercontent.com/11458901/29853877-cde761aa-8d18-11e7-8ae6-8feaf76e66a2.png)

In a single screen the user can see 3 times the geofences icon with the same tooltip or caption. But each one does a different thing.
Sure the icon has to be the same (or small variations) to create some kind of cue for the user. But I think the tooltip could be more detailed.

In the first one I would put "assign geofences". In the second, "show geofences". In the third (menu), "Manage geofences".

**Comment by tananaev** [comment]
There is documentation explaining how to use the system.

**Comment by gustavofcalmeida** [comment]
Your compiler could just say "Compilation failed. Error code 345". Then you go to the manual and check what 345 means. Or, it could say "Failed: unexpected keyword at line 10."

Simple words like "assign", "manage" and "show" in a tooltip save the user from guessing or clicking the button just to know what it does. Imagine a user that has not created any geofences. He can click on the "[show] geofences" icon and nothing is going to happen. He doesn't know why.

> There is documentation explaining how to use the system.

[Is there](https://www.traccar.org/documentation/geofences/)? How is the user supposed to find this documentation? The user is probably not even aware he is using Traccar because somebody changed the logo. Maybe he get that "Powered by Traccar" that flashes for 2 seconds and after a while lands on traccar.org. Then he realizes he doesn't speak English.

**Comment by tananaev** [comment]
You example is not relevant. We are not talking about error messages here. If you take any IDE, there will be buttons that look same or similar, with minimal tooltips that don't explain much. With any complex system it's like this.

I agree that things can be improved, but I don't agree with selectively changing a few things. It has to be consistent approach across the app.

**Comment by tananaev** [comment]
Not relevant for the modern app.
