### ISSUE TITLE
FR: Shareable links with expiration date

### ISSUE THREAD

**Issue by jgaurilo** [traccar/traccar-web#570]
I would like to see shareable links implemented in traccar. Basically it would be live view map with follow and "tail" force-enabled, without any other elements or selections. It would be useful if you could share link with family before long drive for example.

Expiration date for links would be nice feature as well.

**Comment by tananaev** [comment]
It's already possible using read-only user and token access. Even expiration date can be set.

**Comment by jgaurilo** [comment]
Thank you so much! I didn't even think of this solution. I should have read the documentation for the new version before writing. Now if I could only figure out way to disable the reports for the new user, they reveal bit too much...

**Comment by tananaev** [comment]
You can disable reports in user attributes.

**Comment by jgaurilo** [comment]
Hello @tananaev 

I'm so sorry to bother you with this but I have tried to disable the reports for a while now and I simply cannot figure out how to do this. 

In User Attributes there is only bunch of email settings and 2 web settings, nothing to disable reports. I have done everything like the documentation part "Embedded or public view" in user management documentation says. It works fine with token but I just can't disable reports.

I'm using latest (3.14) version of Traccar with MySQL database and apache2 ssl proxy setup.

**Comment by tananaev** [comment]
![screen shot 2017-09-21 at 11 59 04 pm](https://user-images.githubusercontent.com/1161863/30694623-e3a4c7ae-9f28-11e7-9c79-98277dbd0e18.png)

**Comment by jgaurilo** [comment]
Okay now this is just strange. When I tried to disable reports I used Finnish locale and option above was not available. I changed locale to English and now the option to disable report is available even after I change locale back to Finnish. Before it was not there. This may be a bug.

Thank you so much Anton, you are the best! :)
