### ISSUE TITLE
Fuel problem

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar-web#577]
![sommario1](https://user-images.githubusercontent.com/23439828/30216572-bb3d2628-94b3-11e7-93e4-c277a3059573.jpg)

![sommario](https://user-images.githubusercontent.com/23439828/30216567-b75a8a82-94b3-11e7-94a2-34da5af5d601.jpg)

![fermate1](https://user-images.githubusercontent.com/23439828/30216551-ae929d36-94b3-11e7-801f-d4bf276c6ba7.jpg)
Hello Anton I upgraded to the latest version of 3.14 software.
I'm saying I'm using the Teltonika FMxx devices with canbus which also provide me with the fuel level values%; fuel consumed: etc. in the status panel.
When I ask for a report for stops, summary, travel, in the fuel column I always get 0.
why?
Also, if I export the table of contents to the exel table, you see only a white square
![fermate](https://user-images.githubusercontent.com/23439828/30216548-a96e6092-94b3-11e7-90b1-ad76c6216b9a.jpg)

**Comment by tananaev** [comment]
Because Traccar doesn't know how to decode fuel information for Teltonika. You have to provide documentation. Also, we can only add something that's applicable for all Teltonika device models.

**Comment by netluca1** [comment]
Hello Anton, maybe I was wrong.
If you see the images, both the fuel percentage and consumed fuel is displayed in the status panel.
So I can assume that the data arrives correctly. Which tracings can not bring them back to the report since the data is present in the db?
As far as canbus teltonika data uses only two modules for all of its devices, LV-can200 and allcan300 send you the documentation to your email address

**Comment by tananaev** [comment]
I think you configured attribute aliases. It's not the same.

**Comment by netluca1** [comment]
yes i have configured attribute aliases the in db e route is show in attributes tables

![attribute](https://user-images.githubusercontent.com/23439828/30250707-6f17a9f2-9653-11e7-8c9f-7b95f70117a4.jpg)

**Comment by tananaev** [comment]
Exactly. Traccar doesn't know about the fuel, so it doesn't show it.

**Comment by netluca1** [comment]
so I can imagine that driving hours have the same problem

**Comment by tananaev** [comment]
Engine hours are usually calculated on the server based on ignition value.

**Comment by netluca1** [comment]
in fact teltonika sends this data in 3 different ways:
1) Power Voltage (if voltage is between High Voltage and Low Voltage
    Level of ignition is considered to be turned on);
2) Digital Input (DIN1 ON - ignition on, DIN1 off - ignition off);
3) Movement (if accelerometer / movement sensor detects movement then
ignition is on, if movement stops - ignitin is off).
and send this with ID239 or DIN1 (traccar is Power) and this value is present in route is show in attributes tables
So in this situation do you know these ignition values to calculate driving hours or can not calculate them as unknown?

**Comment by netluca1** [comment]
![ignition](https://user-images.githubusercontent.com/23439828/30254495-11e597fc-969a-11e7-8d10-e2597e797cfc.jpg)

**Comment by tananaev** [comment]
Ignition is ignition. Movement sensor is not the same thing. Power voltage is not the same thing either.

**Comment by lukashaaa** [comment]
@netluca1 Were you able to solve the fuel problem? I also use teltonika.
