### ISSUE TITLE
edit report 

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar-web#580]
Hello Anton I have a problem.
I tried to customize the template with character and logo colors.
For the first there were no problems but the logo in the template seemed correct but when it is compiled from the traced logo it disappears.
this happens with trips, routes, events while x summay function complete.
Because?

**Comment by tananaev** [comment]
I have no idea.

**Comment by netluca1** [comment]
so I can imagine that driving hours have the same problem

**Comment by tananaev** [comment]
What? Why?

**Comment by netluca1** [comment]
sorry i have confused issue

**Comment by netluca1** [comment]
I think I have found why the template erases the logo.
The template report used JXLS is correct?

**Comment by tananaev** [comment]
Are you asking if your template is correct? How would I know? I never seen it.
