### ISSUE TITLE
Feature Request: Add option to hide device names on map

### ISSUE THREAD

**Issue by socstur** [traccar/traccar-web#591]
I couldn't find this discussed anywhere but it'll be nice to hide the device names on the map. Similar to how you can hide the geofences on the maps.

**Comment by socstur** [comment]
Hey guys...anyone has feedback on this feature request?

**Comment by tananaev** [comment]
I think the feature is pretty clear.

**Comment by socstur** [comment]
Sorry Anton...I don't get that. It's clear as in it's already possible to do that?

**Comment by tananaev** [comment]
No, it means that we will consider implementing it.

**Comment by socstur** [comment]
Ok thanks.

**Comment by tananaev** [comment]
In the modern app we have clustering which solves a problem of too much noise on the map. Closing it for now, but if you think it's still needed, please provide additional information on why it's needed.
