### ISSUE TITLE
UI: Hide Position Attributes usage

### ISSUE THREAD

**Issue by socstur** [traccar/traccar-web#597]
Hi Guys...is the implementation of "UI: Hide Position Attributes"  complete? I tried giving it a list of attributes that shows in the "State" window but it doesn't seem to hide them for the user. For example I added "Accuracy" to the list but it still shows for the user. If its implementation is complete please let me know the proper usage.

Thanks in advance.

**Comment by tananaev** [comment]
All attribute keys start with lower-case letter.

**Comment by socstur** [comment]
Thanks...I made the change to lower case but not all the attributes are disappearing. I have given it this list "accuracy , address , altitude , battery , blocked , charge , distance , fuel , ignition , ip , protocol , rssi , speed , status , totalDistance , total distance , valid , VALID , Valid , Protocol , PROTOCOL , ALTITUDE , Altitude , ACCURACY , Accuracy". 

But the image below shows some have disappeared while others still show.

**Comment by tananaev** [comment]
The ones that didn't disappear are not "attributes". Those are part of position model.

As for hiding other panels, you can create a feature request for it.

**Comment by socstur** [comment]
Thanks Anton

**Comment by gustavofcalmeida** [comment]
Where do you put this list of attributes to be hidden?

**Comment by tananaev** [comment]
In user attributes.

**Comment by gustavofcalmeida** [comment]
Where did you get this "UI: Hide Position Attributes" attribute name? It's not in the list of pre-configured user attributes.

Also where to get the possible values "for UI: Hide Position Attributes"?

**Comment by gustavofcalmeida** [comment]
Nothing changed after I set
**UI: Disable Compute d Attributes** and **UI: Disable Calendars** to true. Are the top-left buttons supposed to hide?

**Comment by tananaev** [comment]
Have you refreshed the page?

**Comment by gustavofcalmeida** [comment]
I logged out and logged in again.

**Comment by tananaev** [comment]
Please provide a screenshot of the attributes that you have configured

**Comment by gustavofcalmeida** [comment]
All the boolean valued attributes worked, differently from what I reported before. Sorry. The  **UI: Disable Vehicle Fetures** didn't make any noticeable diference.

Concerning the "UI: Hide Position Attributes", I used this as value: **"accuracy, protocol, latitude, longitude"**. Nothing changed. Maybe because all of them are _"part of position model."_.

**Comment by tananaev** [comment]
Yes, you can only hide additional attributes, not base position information.

**Comment by gustavofcalmeida** [comment]
@socstur  where did you learn about  _UI: Hide Position Attributes_?

**Comment by socstur** [comment]
@gustavofcalmeida  the UI: Hide Position Attributes is probably not in the released version of the code. I found it in the master copy of the github code. It'll probably show up in the next release.

**Comment by johnichan** [comment]
Hi I wanted to hide the speed. is that part of position model?

**Comment by tananaev** [comment]
Yes.

**Comment by johnichan** [comment]
Thanks Tananaev. Your response was swift..
