### ISSUE TITLE
Feature request: UI: Hide Panels options

### ISSUE THREAD

**Issue by socstur** [traccar/traccar-web#598]
Hi All
           I see in the latest code there’s a user option to hide the reports panel. Can similar options be created for hiding Devices, State, and Events panels?

**Comment by Abyss777** [comment]
Hiding Events panel was implemented in #615 
What about using "simple" interface if you want hide all panels and get just map?

**Comment by socstur** [comment]
Hi...can the "simple" interface be configured per user? From my understanding if used it'll be for the whole server and not on a per user basis.

**Comment by tananaev** [comment]
It's always per user.
