### ISSUE TITLE
Geofence labels problem

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar-web#600]
There is a couple of FR about hiding geofence labels. I believe, people just do not want to see mess of labels when map zoomed out.

There is new release of openlayers https://github.com/openlayers/openlayers/releases/tag/v4.4.0 that partially solves the problem. Labels more than polygon now not rendered by default. Also there is `placement` config to render text along of lines.
I've filled FR about same feature for circles https://github.com/openlayers/openlayers/issues/7317

also here is my code to use new features:
```diff
diff --git a/web/app/view/map/MapController.js b/web/app/view/map/MapController.js
index 75796f9..347dcf1 100644
--- a/web/app/view/map/MapController.js
+++ b/web/app/view/map/MapController.js
@@ -79,10 +79,12 @@ Ext.define('Traccar.view.map.MapController', {
         this.getView().getGeofencesSource().clear();
         if (this.lookupReference('showGeofencesButton').pressed) {
             Ext.getStore('Geofences').each(function (geofence) {
-                var feature = new ol.Feature(
-                    Traccar.GeofenceConverter.wktToGeometry(this.getView().getMapView(), geofence.get('area')));
+                var feature, geometry;
+                geometry = Traccar.GeofenceConverter.wktToGeometry(this.getView().getMapView(), geofence.get('area'));
+                feature = new ol.Feature(geometry);
                 feature.setStyle(this.getAreaStyle(
-                    geofence.get('name'), geofence.get('attributes') ? geofence.get('attributes').color : null));
+                    geofence.get('name'), geofence.get('attributes') ? geofence.get('attributes').color : null,
+                    geometry instanceof ol.geom.LineString));
                 this.getView().getGeofencesSource().addFeature(feature);
                 return true;
             }, this);
diff --git a/web/app/view/map/MapMarkerController.js b/web/app/view/map/MapMarkerController.js
index c46faac..c12c04e 100644
--- a/web/app/view/map/MapMarkerController.js
+++ b/web/app/view/map/MapMarkerController.js
@@ -82,7 +82,7 @@ Ext.define('Traccar.view.map.MapMarkerController', {
         this.selectZoom = Traccar.app.getAttributePreference('web.selectZoom', 0);
     },
 
-    getAreaStyle: function (label, color) {
+    getAreaStyle: function (label, color, linePlacement) {
         var fillColor, strokeColor, styleConfig;
         if (color) {
             fillColor = ol.color.asArray(color);
@@ -104,6 +104,7 @@ Ext.define('Traccar.view.map.MapMarkerController', {
         if (label) {
             styleConfig.text = new ol.style.Text({
                 text: label,
+                placement: linePlacement ? 'line' : 'point',
                 fill: new ol.style.Fill({
                     color: Traccar.Style.mapGeofenceTextColor
                 }),
diff --git a/web/load.js b/web/load.js
index cb5defd..72028af 100644
--- a/web/load.js
+++ b/web/load.js
@@ -145,7 +145,7 @@
 
     extjsVersion = '6.2.0';
     fontAwesomeVersion = '4.7.0';
-    olVersion = '4.3.2';
+    olVersion = '4.4.0';
     proj4jsVersion = '2.4.3';
 
     if (debugMode) {
```
It's too early to make pull request, because circle label have old looking.

**Comment by Abyss777** [comment]
Looks like "labels-fits-circle" will not be implemented to our next release. I think we should revert old behavior for poligon labels, to make captions consistent with all geofences types. Of course if we are going to update openlayers.

**Comment by tananaev** [comment]
Please remind me what behaviour you are talking about? We do plan to update OpenLayers, unless there are some issues.

**Comment by Abyss777** [comment]
This how geofences captions looks like with openlayers before 4.4.0 if map zoomed out
![image](https://user-images.githubusercontent.com/5688080/33594250-fe7548c6-d9b4-11e7-8418-2c4fd84e2703.png)

This is how they look after 4.4.0 by default
![image](https://user-images.githubusercontent.com/5688080/33594264-1199eb46-d9b5-11e7-817c-152bac07d8a8.png)

By default poligon captions hidden if it is not inside the poligon (ref. yellow geofence)
It is very good, but looks inconsistent with circle and line geofences.
There is solution for line described in first message, but there is no solution for circles.

We can change default behavior to not hide poligon labels for consistence.

**Comment by tananaev** [comment]
Yes, I guess we need to make them consistent for now.
