### ISSUE TITLE
DOUT Custom Commands

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar-web#604]
Ability to support Digital out pin control on devices though custom command panel though two options PIN (can this be controlled somehow as some devices have none, one or more pins, ie eelink devices show 4 but on some there are no DOUT pins and on others only 2) and Enabled/Disabled toggle.

**Comment by tananaev** [comment]
There is already a command to control digital output. Not sure what exactly you mean by this.

**Comment by tsmgeek** [comment]
TYPE_OUTPUT_CONTROL = "outputControl"
Is this the command you are talking about? Then it seems that eelink protocol does not have it implemented, ile alter my update to handle it.

Not sure how many devices out there take a string for this vs just 1/0, are there?
Eelink has an odd way to send the pins, PORT,[DOUT],[MASK], it allows setting multiple pins at the same time which is odd for some to understand, it may just be easier to have a toggle flag
If there is could we have a different output **outputControlDin** type then just have a toggle instead of string in the dialog.

**Comment by tananaev** [comment]
Yes, that's the command. It takes output index and boolean value.
