### ISSUE TITLE
Dialog boxes to be modal

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar-web#610]
Some of the problems caused on mobile devices (windows jumping behind others) is due to dialog boxes not being modal.
Sometimes when selecting menu options the dialog it will go behind the previous dialog box etc, if it was modal it would not happen as it stays on top.

**Comment by tananaev** [comment]
Please provide steps to reproduce the issue.

**Comment by tsmgeek** [comment]
Open any dialog box ie notifications, then add, then click on original
notification window. Dialog goes behind.

Or

On mobile, try adding a user attribute like speed, when I try and select
mph as the menu extends below dialog boundary when you tap on it the dialog
goes behind.

**Comment by tananaev** [comment]
I don't see how modal dialogs would solve anything. If you don't like how windows behave just close the dialog before opening the menu.

**Comment by tsmgeek** [comment]
Modal dialogs with a mask in extjs prevent clicking the window behind, it
will always stay on top. In webview it's next to impossable to change some
parameters.

On 24 Oct 2017 21:12, "Anton Tananaev" <notifications@github.com> wrote:

I don't see how modal dialogs would solve anything. If you don't like how
windows behave just close the dialog before opening the menu.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tananaev/traccar-web/issues/610#issuecomment-339116575>,
or mute the thread

**Comment by tananaev** [comment]
Not relevant for the modern app.
