### ISSUE TITLE
The caption "Close dialog" for all dialogs is not in the I10n resources and can't be translated.

### ISSUE THREAD

**Issue by gustavofcalmeida** [traccar/traccar-web#611]
Every dialog has this "Close dialog" caption that can't be i10nalized.

**Comment by tananaev** [comment]
It can be translated and it is translated, but it's part of the Sencha ExtJS framework.

**Comment by gustavofcalmeida** [comment]
I doesn't seen translated to me.

**Comment by tananaev** [comment]
What language?

**Comment by gustavofcalmeida** [comment]
![sem titulo](https://user-images.githubusercontent.com/11458901/32149102-aeae2c38-bcde-11e7-824a-767dc111dcd7.png)

I'm using japanese here just to make a point. But I've tried spanish, french, german, portuguese.

**Comment by tananaev** [comment]
It should be translated. See the `code` value here:

https://github.com/tananaev/traccar-web/blob/master/web/load.js#L54

Check developer console to see what extjs locale file is loaded for you.

**Comment by tananaev** [comment]
Also, check if calendar is translated.

**Comment by gustavofcalmeida** [comment]
To make sure it's nothing I changed in my own server, I've just registered in demo server 5, changed to Spanish, and it's the same.

![sem titulo](https://user-images.githubusercontent.com/11458901/32149315-099ebd68-bce1-11e7-9eee-63ca127b8aed.png)

**Comment by tananaev** [comment]
What about calendar?

**Comment by gustavofcalmeida** [comment]
Seems the same. Now in french:

![sem titulo](https://user-images.githubusercontent.com/11458901/32149357-dfda749e-bce1-11e7-9a03-ba0e95f77a13.png)

**Comment by tananaev** [comment]
Not that calendar. When you select from and to dates for reports there is a calendar popup. Is it localised?

**Comment by gustavofcalmeida** [comment]
It is localised.

**Comment by tananaev** [comment]
Then my guess is that it's an ExtJS problem. Tooltip for close button is probably hardcoded somewhere in their code.

**Comment by tananaev** [comment]
Not relevant for the modern app.
