### ISSUE TITLE
Email Notifications Links

### ISSUE THREAD

**Issue by wolfbgn** [traccar/traccar-web#616]
1. Device Moving, Stopped, etc. notifications display a link with the address of the event. I am able to click on it and I get forwarded to my account. I can see the Device on the map colored but without the name I assigned to it (registration number). Since I have 10 trucks and I am kind of dumb when I look at the Device I have already forgotten wuich Device is this. Is it possible to see the name of the Device?
2. Device online and offline notifications display a link with my server domain and event ID rather than the address of the event. Clicking on it opens Events panel on my account. Is it possible those two notifications to display the address like the others and clicking on the link to see the Device on the map colored ? Most of offline events occur because vehicle enters underground parking and if I can see it on the map it is faster to realise whats is going on.
Actually this is not an issue. Sorry if this is not the place to bring it up.

**Comment by tananaev** [comment]
1. It should show device information in the report or event panel.
2. It's not possible because those events don't have positions associated with them.

**Comment by wolfbgn** [comment]
Thanks
