### ISSUE TITLE
How to click add button directly from URL

### ISSUE THREAD

**Issue by zeeworld** [traccar/traccar-web#622]
I have created a autologin. 

I want to open directly the ADD button from URL or tell me the javascript link.

**Comment by mhuzqu** [comment]
You ahould uae traccar API

**Comment by mohamedfadol** [comment]
i want to login from another place how can use api for ,  possible example @mhuzqu  pls

**Comment by mhuzqu** [comment]
> i want to login from another place how can use api for , possible example @mhuzqu pls

Please read documentation in here
https://www.traccar.org/traccar-api/
Access token chapter

You can send token as parameter, then you can do all you need.
