### ISSUE TITLE
courseValues (['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW']) need translation

### ISSUE THREAD

**Issue by ckrey** [traccar/traccar-web#628]
I am not sure whether this should be done via `i10n` or as a preference. 

This would be e.g. `['N', 'NO', 'O', 'SO', 'S', 'SW', 'W', 'NW']` for German,
or `['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO']` in French

<img width="726" alt="bildschirmfoto 2017-12-11 um 12 30 11" src="https://user-images.githubusercontent.com/4027289/33829147-4c30f5f6-de6f-11e7-8158-fccb76e768be.png">

**Comment by tananaev** [comment]
I guess it should be localised through i10n, but it seems like a relatively minor issue. I believe most people, even if they don't know English, would understand English version of directions.

**Comment by Turbovix** [comment]
@ckrey 
you can make direct change in the code and then compile, after that, you must generate a new app.min.js to later generate the installer!
In my case mine looked like this:

 `   var courseValues = ['Norte', 'Nordeste', 'Leste', 'Sudeste', 'Sul', 'Sudoeste', 'Oeste', 'Noroeste'];`

**Comment by ckrey** [comment]
Thanks @Turbovix I know, but this would mean I have to re-do this step with each release
