### ISSUE TITLE
baidu-map error

### ISSUE THREAD

**Issue by ghost** [traccar/traccar-web#633]
hello,
I test the openstreetmap and baidu map by the same road.
The result is that openstreetmap is perfect, but the baidu-map has error.
like these picture , the baidu-map is deviation.
Could you fix the error of the baidu-map,please?
The baidu-map picture.
![baidumap1](https://user-images.githubusercontent.com/3096591/34397627-95f40a02-ebb2-11e7-906a-c1aa77491adb.png)
![baidumap2](https://user-images.githubusercontent.com/3096591/34397629-96d6cf04-ebb2-11e7-8b36-eba877b015d1.png)
openstreetmap:
![openstreetmap](https://user-images.githubusercontent.com/3096591/34397631-a552d3ac-ebb2-11e7-88a5-d24a1d33fa91.png)
![openstreetmap2](https://user-images.githubusercontent.com/3096591/34397632-a61eb6c0-ebb2-11e7-9d57-472abeb4a9f3.png)

**Comment by tananaev** [comment]
I believe this is the reason:

https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China

**Comment by tananaev** [comment]
We now use AutoNavi map for China coverage. Baidu had some issues, so we had to stop using it.
