### ISSUE TITLE
wish to integrate the gaode map into the traccar

### ISSUE THREAD

**Issue by ghost** [traccar/traccar-web#635]
In China, the biggest 2 map is baidu map and gaode map.
Now the baidu map on the traccar has problem , cann't to be use correctly.
So wish to integrate the gaode map into the traccar.
I already research, the gaode map is not same as baidu map about coordinate， So it will not have problem.
The gaode map URL is http://gaode.com/
And the develop guide URL is http://lbs.amap.com/api
Sorry ,only have Chinese version website.

**Comment by tananaev** [comment]
You would need to research tile server details.

**Comment by sznova** [comment]
Thanks

**Comment by tananaev** [comment]
We're already using AutoNavi / Amap.
