### ISSUE TITLE
StateController.js url to external map coordinates

### ISSUE THREAD

**Issue by mihailtudoran** [traccar/traccar-web#637]
It will be nice that coordinates shown into the State window of each device to have a link ( URL ) to external map, something like:

https://www.google.com/maps/place/44.478944,26.111047

I think it is very easy to implement and good to have if we want to get directions or calculate ETA to destination.

Thanks!

**Comment by tananaev** [comment]
Feel free to send a pull request.

**Comment by tananaev** [comment]
This has been recently implemented in the modern app.
