### ISSUE TITLE
Feature Request - multiple maintenances of the same vehicle

### ISSUE THREAD

**Issue by cesarserafim** [traccar/traccar-web#639]
it would be very good to continue to develop the maintenance feature and also a dedicated icon under devices panel and some report for fleet maintenaces status. I use a lot in WEB modification version (traccar-web).
![image](https://user-images.githubusercontent.com/7399657/34946793-5ccf1c94-f9ef-11e7-82f6-f2dc39751709.png).

**Comment by juanjorgebm** [comment]
I need this. Do you think is posible to implement it on traccar?

**Comment by tananaev** [comment]
Anything is possible. Someone just has to do it.

**Comment by juanjorgebm** [comment]
I am a developer but don't have enough expirience to make that quickly. Is there any way to pay for that? How much could be the value for that?

**Comment by tananaev** [comment]
Send me an email to discuss it. Address is in profile.

**Comment by tananaev** [comment]
Possibly. There is already a pull request for it:

https://github.com/traccar/traccar/pull/3842
