### ISSUE TITLE
Feature Request: More Filters to reports and new Geofence Report

### ISSUE THREAD

**Issue by cesarserafim** [traccar/traccar-web#640]
Hello, I have been using the web modification (https://github.com/vitalidze/traccar-web) for a long time, but its development is stopped in version 3.9 of the original. I've been testing the latest versions for a couple of months and it works without any problems, but to migrate my users to the newest original Traccar Server I'm trying to adapt some of the features they use in the modified version.
As I do not have programming skills, I would like to suggest some features that we consider very useful in the modified version:
1 - in the configure report dialog, add options to select a Driver and or Geofence;
2 - Create a Driver Report Jorney, with the total time of daily driving, stoped, totaldistance, overspeed...;
3 - Create a Geofence Report, with total time inside and outside of selecteds geofences.

Examples:
![image](https://user-images.githubusercontent.com/7399657/34949140-67d5ab2e-f9f6-11e7-94ca-b310d2a963e2.png)
![image](https://user-images.githubusercontent.com/7399657/34949286-ce2b54f0-f9f6-11e7-9e03-6b41b76d2a11.png)

I appreciate if someone finds this interesting too and can give me some direction how to do it.
Thank you all for the great project.

**Comment by chrystianmartins** [comment]
César vai ter que fazer na unha jovem ! A base de dados eh totalmente diferente. Exporta tudo pra excel, instala o traccar e cadastra tudo.

**Comment by tananaev** [comment]
Please split into separate tickets per report.
