### ISSUE TITLE
Compatibility with AUTOMILE (OBD2 localization system)

### ISSUE THREAD

**Issue by Pharizna** [traccar/traccar-web#647]
Hi

Don't you think that your project would be very nice working with [AUTOMILE](https://app.automile.com/) or any other ODB2 system with localization)?

**Comment by tananaev** [comment]
You should probably explain what the system does.

**Comment by Pharizna** [comment]
You can here the [API](https://api.automile.com/) for the access to the system: GPS and OBD connecting to a cloud service through 4G

**Comment by tananaev** [comment]
That's not what I asked. I asked what the system actually does. Traccar can work with OBD devices directly. Why do we need some other system.

**Comment by Pharizna** [comment]
I don't very much about your traccar but I suppose that you have to install a 'computer/rpi,etc' in you car to use the info of the gps and from the OBD I'm your system 

In Automile, the OBD include the GPS and process all data sending the info to the cloud...that can recover with API.

It would be interesting to can use this information integrating in Home Assistant, for example
