### ISSUE TITLE
Feature Request: Add Odometer to Summary, Trips, and Stops Reports

### ISSUE THREAD

**Issue by ckrey** [traccar/traccar-web#652]
Use case:

Legal requirements for commercially used vehicles require a vehicle log including
Start and End values for Odometer readings in most countries.

Please add 
- TotalDistance
- Odometer
- OBDOdometer
values for start and end positions to
- SummaryReport
- TripsReport
- StopsReport

Examples:
http://www.ird.govt.nz/resources/4/7/474499e8-8e4c-47c0-ab3d-54334ab8c0f1/vehiclelogbook.xls
https://muster-vorlage.ch/fahrtenbuch-vorlage/
...

**Comment by tananaev** [comment]
Closing as the PR is merged.
