### ISSUE TITLE
Feature Request: Show Summary for device on Mouse Over 

### ISSUE THREAD

**Issue by obbyK** [traccar/traccar-web#656]
Imagine a system with thousands of devices. To check details for each one at a glance, one has to click on each device so that the state panel can be updated. I would like to ask if it's possible that you add a mouseover option so that summary details appear on the map as one hovers a device on the map.

**Comment by conde000011100** [comment]
Something designed for this master @tananaev, would be very helpful and improve the interface, regards

**Comment by mane06** [comment]
I would love this function in future deliveries of Traccar

**Comment by oulfe-lemi** [comment]
ant news on hover future tho?

**Comment by oulfe-lemi** [comment]
any news on this hover future tho

**Comment by tananaev** [comment]
Modern app has a map popup. Not a hover, but a click.
