### ISSUE TITLE
On what language it is written?

### ISSUE THREAD

**Issue by abkiran** [traccar/traccar-web#664]
How do I make UI changes,
What are the prerequisites to go ahead with modifications?
@renaudallard @amenk @tananaev @khfayzullaev @guterresrafael

**Comment by amenk** [comment]
No clue why you mentioning everybody.
I think the UI is written using ExtJS

**Comment by tananaev** [comment]
@abkiran, next time you will get a ban for behaviour like this.

**Comment by abkiran** [comment]
Hello the readme.md doesn't contain special instructions or more details about project, that's why I had to ask here. Sorry!

**Comment by tananaev** [comment]
Asking is fine. Spamming specific people, some of which are not even directly related to the project, is not fine.

**Comment by abkiran** [comment]
Can you please share what is the version of ExtJs is used to build this project?
also please mention what tools are required to make changes to the UI?

with this source code, how can run the project?

Please share an example!
