### ISSUE TITLE
Feature Request (need help) : add Photo On Device and Driver

### ISSUE THREAD

**Issue by mhuzqu** [traccar/traccar-web#678]
Hii Guys,
Currently i can add static (source image harcoded) photo in device dialog.
i am newbie in extjs, i plan to make this device photo dynamically change refer to device identifier (so we have file name with the same device identifier).

i added code below in /web/app/view/dialog/Device.js

```
            ,{
                xtype: 'image',
                src: 'logo.svg',
                alt:'tests alt',
                flex: 1
            }
```

and also i added file upload field form images upload purposed. the result looks like this.

<img width="336" alt="screen shot 2018-06-12 at 11 41 53 pm" src="https://user-images.githubusercontent.com/19386489/41304844-77517776-6e9b-11e8-934a-938814e8ea40.png">

how to make file_name.svg  dynamically change refer to device identifier, i tried using 
`src:'{uniqueId}.svg' `
it doesn't work.

**Comment by tananaev** [comment]
We've added support for device images.
<img width="656" alt="Screen Shot 2022-07-04 at 10 26 16 AM" src="https://user-images.githubusercontent.com/1161863/177198360-848b5057-875b-49e9-9f53-9aeac7199d64.png">
