### ISSUE TITLE
Bad polish translation 

### ISSUE THREAD

**Issue by 0xFACE** [traccar/traccar-web#679]
https://github.com/traccar/traccar-web/blob/29ab3eabfe35aa6ad6d2a8be3d7f7b790623ea1e/web/l10n/pl.json#L156
```
- "settingsVolumeUnit": "Jednostka głośności",
+ "settingsVolumeUnit": "Jednostka objętości",
```

**Comment by tananaev** [comment]
Please fix it on Transifex:

https://www.transifex.com/traccar/traccar/
