### ISSUE TITLE
Hide Device name top of icon

### ISSUE THREAD

**Issue by mrd3691** [traccar/traccar-web#681]
Hi 
I added many device to traccar (about 200) and then it has no good look when show name of device top of icon .
How we can Hide or remove it and show it on state bar .
thanks

**Comment by tananaev** [comment]
I don't think it's possible.

**Comment by mrd3691** [comment]
![untitled2](https://user-images.githubusercontent.com/39646583/41524156-c698b10a-72f1-11e8-9077-18af3928cc37.jpg)

attach file is a photo of my screen 
Do you have any idea about solve it?

**Comment by tananaev** [comment]
I'm assuming that you don't want to see all devices at the same time. If that's the case, you can filter devices to show only subset that you are interested in.

**Comment by mrd3691** [comment]
yeah that is right
but when you want to follow your vehicle , it is problem .

**Comment by tananaev** [comment]
Elaborate please.

**Comment by mrd3691** [comment]
the operator can not filter devices one by one and controll them .
operator has to controll them at a glance .
in this state operator can not sense vehicle moves.

**Comment by tananaev** [comment]
Why "can not filter devices one by one"? It's really easy.

**Comment by mrd3691** [comment]
He can but is difficult
it is more than 200 devices

**Comment by tananaev** [comment]
I don't really understand the difficulty.

**Comment by mrd3691** [comment]
Dear tananaev
operator has to control movement of vehicles
now he has to filter one by one device and control it
but if he see all devices together it is very better
now device name is reason to don not show clearly devices icon on the map

**Comment by tananaev** [comment]
It takes a few seconds to type device name to filter specific device.

**Comment by mrd3691** [comment]
it takes a few seconds for each device

**Comment by spatialsteve** [comment]
@mrd3691 were you able to achieve this?

**Comment by abigdreamer** [comment]
Would you share source to your custom icons?

**Comment by tananaev** [comment]
Modern app does clustering to avoid this problem. If there's still some need for hiding name, please let me know.
