### ISSUE TITLE
"Limit commands" for the server as a whole limits even the admin user

### ISSUE THREAD

**Issue by gustavofcalmeida** [traccar/traccar-web#684]
When you check "limit commands" in the "server" main menu entry, even the admin user becomes unable to access the "Saved commands" entry on both the main menu and device menu, but it still can execute any commands previously saved and linked to a device. Also, the admin becomes unable to use the "new" command entry to send a command on the fly.

~~This behavior causes a security risk, because the admin may use the global "Limit commands" to limit it's users, but anytime he wants to create a nem command it has to temporarily disable the "limit commands". This time window is enough for a user to create and save his own commands.~~

~~To avoid this, the admin has to "limit commands" for each user individually, instead of using the global setting. But, by doing this, the global "Limit commands" has no reason to exist.~~

**Comment by gustavofcalmeida** [comment]
What I'm asking is: the global "Limit commands" is intended to prevent admins too from managing commands, linking commands to devices and sending "new" commands? Or is it a bug?

Why the global "Device read only" doesn't prevent the admin from adding new devices?

I don't even use the "limit commands". I was trying to understand its use, noticed the behavior that seems strange to me and reported. Since this [piece of documentation](https://www.traccar.org/documentation/commands/) says nothing about the global "limit commands" I have two options, guess and ask.

**Comment by tananaev** [comment]
Well, you didn't ask anything. You just criticised what we have done.

**Comment by gustavofcalmeida** [comment]
I didn't criticised what you have done, I was asking if what you have done is working as intended or not. I used a similar global limitation feature (device read only) to illustrate what it seems a bit strange.

If there is a reason for the admin to be able to block himself from being admin regarding to commands it's not clear to me, because I couldn't find it in the documentation and you didn't explain.

**Comment by tananaev** [comment]
I re-read your original post twice and I still don't see any questions. Please help me to find it.

**Comment by gustavofcalmeida** [comment]
I get it, now. Thank you.
