### ISSUE TITLE
Traccar not updating

### ISSUE THREAD

**Issue by MarkPhilippy** [traccar/traccar-web#689]
Traccar is not updating units, last update shows 81 minutes ago, and web site keeps logging itself out when left open on the computer desktop.

**Comment by tananaev** [comment]
You should start with troubleshooting guide:

https://www.traccar.org/troubleshooting/

**Comment by MarkPhilippy** [comment]
thanks but those steps do not help.  We are viewing Traccar on multiple devices and platforms and it is not updating, and we have multiple units in the field.  It is not a workstation or device problem.

**Comment by tananaev** [comment]
OK, if you have done it already please provide detailed explanation of every step that you did and result that you got.
