### ISSUE TITLE
Filter option

### ISSUE THREAD

**Issue by JBFelizberto** [traccar/traccar-web#690]
In the device panel - on web - I propose to have the possibility to filter the 'Identify column' (where we put IMEI) in the same way that 'name column' is filtered today.

JB

**Comment by JBFelizberto** [comment]
Be able to filter this 'device id' column:

https://drive.google.com/file/d/1k4a8ZQbuJLBRHFIngbxpxl7_HgssRKL6/view?usp=sharing

**Comment by tananaev** [comment]
Sorry, I was under the impression it was already there. Added now.
