### ISSUE TITLE
Geolocation with Opencellid, GPS Tracker ST-901 and h02 protocol

### ISSUE THREAD

**Issue by dlajusticia** [traccar/traccar-web#692]
Hi,

We are implementing a Traccar server in our business to use GPS tracking with our vehicle fleet, among other things. We are trying to use LBS geolocation with invalid positions of GPS, so when there isn’t GPS connection the server will use LBS to get the position of the device. For now we have not been able to do it, though the server is receiving data from the device, as we can see the Io fields at the device status window. Our devices use h02 protocol, which sends 4 fields named Io1, Io2, Io3 and Io4 containing MCC, MNC, LAC, and CID, but Traccar is not translating them into coordinates and showing the real position of the device in the map. The status window of the device show other coordinates that not correspond to the LBS data. On the other hand, in our OpenCellid dashboard, user reports doesn’t show any requests at all, so Im thinking maybe there’s a problem with Traccar connecting to Opencellid, or in the protocol.

The lines in the configuration file (traccar.xml) are the following: 
 ```xml
                <entry key='geolocation.enable'>true</entry>
                <entry key='geolocation.type'>opencellid</entry>
                <entry key='geolocation.key'>our_api_token</entry>
                <entry key='geolocation.mcc'>214</entry>
                <entry key='geolocation.mnc'>07</entry>
                <entry key='geolocation.processInvalidPositions'>true</entry>
 ```
Here is an HEX example of one of the positions that the devices send:
```
2a48512c393138303132373231382c56352c3039303632332c562c343133382e323937352c4e2c30303034352e373832382c572c3030302e30302c3030302c3032303831382c46464646424246462c3231342c30372c30353030322c363637312c3331323931363523
```
Which translates to:
```
*HQ,9180127218,V5,090623,V,4138.2975,N,00045.7828,W,000.00,000,020818,FFFFBBFF,214,07,05002,6671,3129165#
```
You can see the 4 fields (MCC, MNC, LAC, and CID) between commas: 214,07,05002,6671

Here is a pastebin of our tracker-server.log:

https://pastebin.com/NjsGadg7

Any help would be appreciated, thank you in advance.

**Comment by dlajusticia** [comment]
Hi again and thank you for responding. As you said we have a couple devices from a different model. So if we wanted LBS to work we'd have to remove these devices and use the same model for every vehicle? Is there some configuration of the h02 protocol that we could modify? Could we confirm which devices are the ones reporting the 'bad' values? Sorry but I'm kinda clueless here. Thanks in advance.

**Comment by tananaev** [comment]
At the moment there is no way to configure behaviour. I don't know which devices send which values.

**Comment by tananaev** [comment]
Closing as it's not really related to the web app. If there's still an issue please create a ticket in the main repo.
