### ISSUE TITLE
Restrict [off] some global attributes to admin users

### ISSUE THREAD

**Issue by JBFelizberto** [traccar/traccar-web#694]
Currently the admin users receive all the restrict attributes when set-up on the server global attributes.
If you agree, I would like propose the [UI disable resources](https://drive.google.com/file/d/15hp5xXGVspSp5Vg9KiAPUAUyVxQyg5hw/view?usp=sharing) be not applicable  to admin users.

Make sense?

JB

**Comment by tananaev** [comment]
Restrictions are not designed to be permissions. They are not enforced on the API level or back-end. They are just UI changes. The idea is that you can adjust UI to match your use same. For example, if your project is designed for tracking people, you are not interested in vehicle-related functionality.

**Comment by JBFelizberto** [comment]
Got it, you are right. 

My concern was, when I set-up the UI on server (global) attributes, these UI changes items visibility for everyone (include admin). 

So, as workaround I am editing files {'edit\DevicesController.js', 'edit\SettingsMenuController.js'} on each new traccar version instead use this functions.

JB
