### ISSUE TITLE
NullPointerException when showing address

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar-web#695]
Hi, on a fresh 4.0 install (no configuration changes):

Device status window shows "Address" with a link "Show address".

When following this link a pop-up appears telling "Invalid parameters or constraints violation", followed by "NullPointerException (ServerResource:56 < ...)"

This can be explained because geocoding is disabled by default, but for first-time users this is no great experience...

Would it be possible to:
* not show the "address" field (or a crashing link) if geocoding is disabled ?
* if not, then server-side, add a 'dummy' geocoder that just returns "No address available" ?

**Comment by tananaev** [comment]
Implemented better error message on the server side (https://github.com/traccar/traccar/commit/16c52142c0a28fbec61125cdad302ae11163096d). Thanks for suggestion.

**Comment by oliv3** [comment]
You're welcome
