### ISSUE TITLE
Add Google Maps layers

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar-web#696]
I found a reasonably good way to integrate Google Maps API:

https://gist.github.com/ThomasG77/21192c7045ab8f50e22e

I can make Traccar display map, but there seems to be some issue with touch events. Possibly ExtJS interferes with map and causes this problem. @Abyss777, are you interested in a challenge? :) Anyone else is also welcome to try.

Patch with my experiment that almost works:

[add_google_maps_layers.txt](https://github.com/traccar/traccar-web/files/2300966/add_google_maps_layers.txt)

**Comment by Abyss777** [comment]
I'll try of course. Is there any place to get API key without registration?

**Comment by Abyss777** [comment]
> but there seems to be some issue with touch events

Do you mean that nothing works until somehow resize map panel?
Also zoom is not synchronized...

**Comment by tananaev** [comment]
Does it actually work after resize?

**Comment by Abyss777** [comment]
Yes. If I for example open events panel or hit F12 it starts working

**Comment by tananaev** [comment]
Interesting. Maybe we just need to trigger some resize callback somewhere.

**Comment by Abyss777** [comment]
I think this related to kinetic zoom https://gist.github.com/ThomasG77/21192c7045ab8f50e22e#file-index-html-L77

**Comment by Abyss777** [comment]
Oh not, it looks like zooming GM starts only after OL finished.

**Comment by dlajusticia** [comment]
Hi, I don't know if this will be useful, but I added the option to select google maps in the server options. I had to add them to web/app/store/MapTypes.js and their respective string names in the json language file in web/l10n:

```javascript
Ext.define('Traccar.store.MapTypes', {
    extend: 'Ext.data.Store',
    fields: ['key', 'name'],
    data: [{
        key: 'googleRoad',
        name: Strings.mapGoogleRoad
	}, {
        key: 'googleRoadTraffic',
        name: Strings.mapGoogleRoadTraffic
	}, {
        key: 'googleSat',
        name: Strings.mapGoogleSat
	}, {
        key: 'googleSatTraffic',
        name: Strings.mapGoogleSatTraffic
	}, {
        key: 'googleHybrid',
        name: Strings.mapGoogleHybrid
	}, {
        key: 'googleHybridTraffic',
        name: Strings.mapGoogleHybridTraffic
	}, {
    }]
});
```

Then add the cases at web/app/view/map/BaseMap.js:

```javascript
        switch (type) {
			case 'googleRoad':
                layer = new ol.layer.Tile({
                    source: new ol.source.XYZ({
                        url: 'https://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}&s=Ga',
                        attributions: ''
                    })
                });
                break;
			case 'googleRoadTraffic':
                layer = new ol.layer.Tile({
                    source: new ol.source.XYZ({
                        url: 'https://mt0.google.com/vt/lyrs=m,traffic&hl=en&x={x}&y={y}&z={z}&s=Ga',
                        attributions: ''
                    })
                });
                break;
			case 'googleSat':
                layer = new ol.layer.Tile({
                    source: new ol.source.XYZ({
                        url: 'https://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}&s=Ga',
                        attributions: ''
                    })
                });
                break;
			case 'googleSatTraffic':
                layer = new ol.layer.Tile({
                    source: new ol.source.XYZ({
                        url: 'https://mt0.google.com/vt/lyrs=s,traffic&hl=en&x={x}&y={y}&z={z}&s=Ga',
                        attributions: ''
                    })
                });
                break;
			case 'googleHybrid':
                layer = new ol.layer.Tile({
                    source: new ol.source.XYZ({
                        url: 'https://mt0.google.com/vt/lyrs=y&hl=en&x={x}&y={y}&z={z}&s=Ga',
                        attributions: ''
                    })
                });
                break;
			case 'googleHybridTraffic':
                layer = new ol.layer.Tile({
                    source: new ol.source.XYZ({
                        url: 'https://mt0.google.com/vt/lyrs=y,traffic&hl=en&x={x}&y={y}&z={z}&s=Ga',
                        attributions: ''
                    })
                });
                break;				
        }`
```

I wanted to have road, satellite and hybrid with/without traffic so I added these 6 options.
I'm trying now to make a menu with a drop down list with map types and put it in the map buttons instead of having to enter in the server options to change map layer, but I had no success.

**Comment by tananaev** [comment]
@dlajusticia, it's not the right place to post your question. It has nothing to do with the change we are trying to make here.

**Comment by dlajusticia** [comment]
Sorry, I deleted it.

**Comment by tananaev** [comment]
We are trying to integrate Google Maps API properly, not just point to Google tile server (which is against Google terms of service).

**Comment by manuel-rodriguez** [comment]
Hi, i'm not sure if you already figured out but i managed to solve the "not responding map" after the page initially loads, i removed this line:

`mapDiv.parentNode.removeChild(mapDiv);`

from the initMap Method on BaseMap.js and it appears to works.
I'm also not sure if affects something else, i'm still testing the change.

**Comment by tananaev** [comment]
Don't remember now. Let us know if everything works.

**Comment by tananaev** [comment]
Closing this as it's not applicable to modern app. It looks like there's no good way to integrate Google Maps with Maplibre framework for now.
