### ISSUE TITLE
Cannot use saved commands for the (linked) device

### ISSUE THREAD

**Issue by timaschew** [traccar/traccar-web#698]
First of all. Thank you for this great project! It works really intuitive! 🙏🤘

Saved Commands are not showing for linked device, see screenshot

<img width="795" alt="screen shot 2018-08-22 at 01 55 51" src="https://user-images.githubusercontent.com/110870/44435099-ad964880-a5ae-11e8-95a9-43411a2c4aff.png">
<img width="324" alt="screen shot 2018-08-22 at 01 56 21" src="https://user-images.githubusercontent.com/110870/44435103-af600c00-a5ae-11e8-9640-8d79decd623c.png">

**Comment by tananaev** [comment]
Have you linked command to the device? Are you sure this command type is supported for that device/protocol?

**Comment by timaschew** [comment]
> Have you linked command to the device?

Yes, as you can see in the first screenshot.

> Are you sure this command type is supported for that device/protocol?

I have a device which is using this protocol: `gt06.port`.
On the built-in server platform (gps903.net) it shows this device information:
`Device model: GT001`

From the instructions I see that there are commands available via SMS:
- `QP#` - Query the current parameters of the device
- `ST#` - Query the current state of the device

I tried both using SMS and they worked, but not sure if it works without SMS.

BTW: the instructions are really shitty, do you know where to find a good one, maybe even a spec for it?

**Comment by tananaev** [comment]
I see that command type is "Get Device Status", which is not supported for GT06. So, you have to use custom command.

**Comment by timaschew** [comment]
Okay, I can can save the custom command, that's working.
Are these commands designed to receive a response?

I tried now to send  `ST#` but neither in the logs nor in the UI I got a response, which I was expecting.

**Comment by tananaev** [comment]
Where is the response?

**Comment by timaschew** [comment]
I see the output I've posted in the `logs/tracker-server.log` file.

**Comment by tananaev** [comment]
I still don't see any responses in what you posted. HEX data is the commands from server to device. You can see direction of the data by angle bracket direction.

**Comment by timaschew** [comment]
Oh, ops, you're right. So there is no response :(

> "Get Device Status", which is not supported for GT06.

How do you know that this is not supported for GT06?

**Comment by tananaev** [comment]
Because when you select new command, it doesn't show it.

**Comment by timaschew** [comment]
Thanks!
