### ISSUE TITLE
Small feature requests

### ISSUE THREAD

**Issue by pbosgraaf** [traccar/traccar-web#70]
Hi,

I have two feature requests.
Unfortunately i'm not a coder but i am willing to donate (in escrow) for the features.

These are the features i had in mind:

1) Make a option (per device or account) that enables a public URL (without password) where people can track your device. My use case is that i have a boat and i want people to be able to hop on once it's close. The public page would allow them to see where the boat is at any given time.

2) Set a default map-type and map-zoomlevel in settings -> account. This would be applicable to the admin web as well as the feature request above.

If your willing to build the feature please let me know payment details.

Thanks,
Peter

**Comment by spacecabbie** [comment]
> 1. Make a option (per device or account) that enables a public URL (without password) where people can track your device. My use case is that i have a boat and i want people to be able to hop on once it's close. The public page would allow them to see where the boat is at any given time.

the above can be achieved with the minimal web template and a public account with token. See current documentation.

> 2. Set a default map-type and map-zoomlevel in settings -> account. This would be applicable to the admin web as well as the feature request above.

This has since be implemented see documentation.
If you still have special request you best bet would be to mail sales@traccar.org

@tananaev Can be closed.
