### ISSUE TITLE
blank fields in route report when "fuel" column is selected 

### ISSUE THREAD

**Issue by lukazi** [traccar/traccar-web#712]
v4.1 Only blank white columns appear behind fuel column if "fuel" column is selected in route report.

**Comment by tananaev** [comment]
It usually means that your device hasn't reported the value.

**Comment by tananaev** [comment]
It probably means that you have an invalid value in the fuel column.

**Comment by lukazi** [comment]
which table in database should I check?

**Comment by lukazi** [comment]
I can't see any record in tc_positions table with fuel value
SELECT * FROM TC_POSITIONS where deviceid = 55 and attributes regexp '.*fuel.*'
