### ISSUE TITLE
problem with selecting columns when opening in android or iphone, cache deleting helps

### ISSUE THREAD

**Issue by lukazi** [traccar/traccar-web#713]
If you open traccar web in android or iphone you can select own device columns only during the first session. After reopening the page it's not possible, hidden rolldown menu with columns checkboxes is not displayed. If you delete the browser cache it works again.

**Comment by tananaev** [comment]
What version of Android are you using? What browser? What version? Please provide screenshots.

**Comment by tananaev** [comment]
Column menu button doesn't seem to be visible for me, but I can still click on the right side of the column header and open the menu. I'm not able to reproduce this issue in Chrome on Android 8.0.

**Comment by lukazi** [comment]
Try it again after closing Chrome and reopening tc web

**Comment by tananaev** [comment]
Yeah, I see now. Unfortunately I don't think we can do anything about it. It's an issue in ExtJS framework. We just need to wait for next version and hope it's fixed there.

**Comment by JBFelizberto** [comment]
I noticed that Firefox Works

JB

**Comment by lukazi** [comment]
Try it again after closing and reopening Firefox.

**Comment by tananaev** [comment]
Did it work on previous versions?

**Comment by lukazi** [comment]
Didn't work in 4.0. Not sure about older ones


st 7. lis 2018 8:30 odesílatel Anton Tananaev <notifications@github.com>
napsal:

**Comment by tananaev** [comment]
Shouldn't be a problem in the modern app. It's much more mobile friendly.
