### ISSUE TITLE
Traccar Web Interface

### ISSUE THREAD

**Issue by aosman3005** [traccar/traccar-web#715]
Hello,

I want to change the current web interface to a customized version of mine.
Has somebody ever tried changing the web interface? If so, can you tell me how?

Thanks and best regards
Akram

**Comment by aosman3005** [comment]
@victorferreira Actually both options sounds interessting but for the time being I would rather try to modify the existing one

**Comment by victorferreira** [comment]
@aosman3005 the existing version in build on top op ExtJs, so you might want look it up. But there's a new version being developed using ReactJS. If you want to contribute, check #592

**Comment by aosman3005** [comment]
@victorferreira okay great thank you! It seems that the new version is far from running so I'm thinking of building one from scratch. Have anyone has some experience with that?

**Comment by greatidea1** [comment]
Hi guys, 
I'm also in need of a new web interface. I like the current one's left pane where it lists tracker devices in different status based colours, but it is less user-friendly and slightly cumbersome to use especially the Report > Configure, then add device(s), start date/time and end date/time.

Anyway that this can be made easier?

**Comment by sem1300000000** [comment]
Привет. Меня тоже интересует изменение интерфейса. А точнее изменения формы отчётов. Хочу убрать всё кроме событий. А лучше сделать возможность настройки отключения нужных строк или столбцов. Если это можно сделать и сейчас, подскажите как?

**Comment by tananaev** [comment]
Можно сделать и сейчас - поменяйте шаблоны.

**Comment by sem1300000000** [comment]
Как поменять шаблон? Пересмотрел папку с программой и не нашёл шаблоны отчётов. Есть ещё вопрос про экспорт. Будут ли столбцы в exel на русском?
