### ISSUE TITLE
ITS & AIS140 Protocol

### ISSUE THREAD

**Issue by GPSIndia** [traccar/traccar-web#718]
[AIS140_message_formats_257.docx](https://github.com/traccar/traccar-web/files/2575196/AIS140_message_formats_257.docx)
We tried using AIS140 on port 5179. but the devices are not getting detected and seems to be offline.  

Below is the hex code we receive on the traccar 5179 port.

```
$,A,MFR,7.0,NR,01,L,869026034780985,PJ09BU1234,1,12112018,121953,12.756974,N,077.800025,E,000.0,318.03,15,794.0,001.3,000.7,TAMIL NAD,0,1,13.08,04.13,0,O,22,404,80,0919,71C1,0919,7168,19,0919,71c3,17,0919,71c2,11,0919,7167,09,0011,00,000173,D8,000000.00,,,* 
```
When we map it to the frame format below is the details :

$  -- Start Character
A -- Packet Identifier
MFR -- Vendor ID
7.0 -- Firmware Version
NR -- Packet Type
01 -- Alert ID
L -- Packet Status 
869026034780985  -- IMEI
PJ09BU1234-- Vehicle Reg No.
1 -- GPS Fix
12112018 -- Date
121953 -- Time
12.756974-- Latitude
N -- Latitude Direction
077.800025 -- Longitude
E -- Longitude Direction
000.0 -- Speed
318.03 -- Heading
15 -- No. of Satellites
794.0 -- Altitude
001.3 -- PDOP
000.7 -- HDOP
TAMIL NAD -- Network Operator Name
0 -- Ignition
1 -- Main Power Status
13.08 -- Main Input Voltage
04.13 -- Internal Battery Voltage
0 -- Emergency Status
O -- Tamper Alert
22 -- GSM Signal Strength
404 -- MCC
80 -- MNC
0919 -- LAC
71C1 -- Cell ID
0919 - MNR
7168 -- Digital Input Status
19 -- Digital Output Status
0919 -- Frame Number
71c3
17
0919
71c2
11
0919
7167
09
0011
00
000173
D8
00 000000.0 
*

Request you kindly update this on priority as AIS140 is implemented in India already. All manufacturers will use the same protocol

**Comment by tananaev** [comment]
Fixed the issue. Please next time create issue in the right place. This problem has nothing to do with the web app.

**Comment by GPSIndia** [comment]
Is the document attached considered completely or only the part of it is fixed. Sorry for posting in the wrong place. I am a nuance to ticketing at traccar. Apologies
