### ISSUE TITLE
TK103 Protocol  Update

### ISSUE THREAD

**Issue by GPSIndia** [traccar/traccar-web#721]
The tk103 protocol working on 5002 port is having certain issues. We are herewith providing updated protocol document for the same.

Kindly process the same.
[Tracker Communication Protocol V1.5.3.pdf](https://github.com/traccar/traccar-web/files/2743658/Tracker.Communication.Protocol.V1.5.3.pdf)

**Comment by GPSIndia** [comment]
Hex Code
283032363938313533373430304252303031313132313356303030302e303030304e30303030302e30303030453030302e303030303030303030302e303030313030303030304c303034314144423629

Decode:
026981537400BR00**111213**V0000.0000N00000.0000E000.0000000000.0001000000L0041ADB6

 
In this 111213 is the time whereas traccar is taking it as date and the entry of device time and GPS fix time is 3rd December, 2011.

**Comment by GPSIndia** [comment]
Sorry by mistake have posted wrongly here. I am not able to shift this to the traccar. Can you pl move this to right place

**Comment by tananaev** [comment]
It's not possible to move it.

**Comment by victorferreira** [comment]
I now this is close already, but since last year it's possible to move issues across repos within the same organization. 

https://help.github.com/articles/transferring-an-issue-to-another-repository/

**Comment by tananaev** [comment]
Thanks. I didn't know. Looks like the feature is still in "beta" :)

**Comment by GPSIndia** [comment]
Thanks Victor, i have created a new ticket in the required repo.
