### ISSUE TITLE
How to Traccar-web (Branch: Modern) authentication RESTApi?

### ISSUE THREAD

**Issue by kritsanaCh57** [traccar/traccar-web#726]
Hi,

I have a problem to authentication api(v4.2) with traccar-web (Branch: Modern)
After POST api/session with username/pwd is ok (status 200) and GET api/session is not found (HTTP 404 Not Found). I have no idea to use JSESSIONID.

**Comment by tananaev** [comment]
For questions you should use forum. As for authentication, you need to include session cookie with your subsequent requests.

**Comment by kritsanaCh57** [comment]
I try to insert `credentials: 'include'` in fetch and it's worked.
Thank you. @tananaev
