### ISSUE TITLE
Baidu maps not loaded over https

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar-web#728]
I have exactly the same problem as described in https://www.traccar.org/forums/topic/when-the-server-use-https-traccar-manager-can-not-show-baidu/

Traccar is sitting behind a SSL-only web server with this `Content-Security-Policy`:

```
Content-Security-Policy "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' cdnjs.cloudflare.com cdn.jsdelivr.net dev.virtualearth.net; style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com cdn.jsdelivr.net; img-src 'self' data: maps.wikimedia.org cdnjs.cloudflare.com *.global.ssl.fastly.net *.tile.openstreetmap.org *.map.bdimg.com *.maps.yandex.net"
```

While maps are correctly loaded for e.g. OpenStreetMap, Yandex, for Baidu nothing is loaded, and browser console doesn't tell about blocked content.

**Comment by tananaev** [comment]
I don't think we can do anything about it at this point. Their HTTPS has an invalid certificate.

**Comment by oliv3** [comment]
Why don't you make them aware of that ?
It breaks the product after all. Or remove this layer, for nobody uses plain HTTP nowadays.

**Comment by spacecabbie** [comment]
Their Certificate is now valid again issue is resolved. fyi
