### ISSUE TITLE
Filters in device panel not working (android mobile)

### ISSUE THREAD

**Issue by PiotrIT** [traccar/traccar-web#729]
Hi,
i found a bug on web browser and traccar ~~client~~ manager for android device.
Filtering in the device panel doesn't work.
Filtering works only once the first time you log in. After log out and re-logging, you can no longer use the filter.
1. in the browser, filtering works again after deleting history
2. in traccar ~~client~~ manager for android filtering works again after stopping the application in the device setting and restarting from the icon.

**Comment by tananaev** [comment]
1. Attach screen recoding of the issue.
2. Traccar Client app doesn't have any filtering.

**Comment by PiotrIT** [comment]
Ok, i will try to record it.
I mean, of course, traccar manager.

**Comment by PiotrIT** [comment]
link to recorded screen: 
https://drive.google.com/open?id=1Q-ebdCgsKTxsh2gMOThuxfr2AaqWIhg9 
When i re-login I can't expand the menu (filters>serach field)
After clearing the history, the menu works again

Filters in other places like geofences, drivers works correctly.

devce: samsung galaxy s7
android 8.0

**Comment by tananaev** [comment]
Looks like ExtJS issue. I don't think we can do anything about it. We would have to wait for a new version.

**Comment by oliv3** [comment]
Opening a bug report might help.
https://www.sencha.com/forum/forumdisplay.php?134-Ext-6-Bugs

**Comment by tananaev** [comment]
Feel free to file a bug report with Sencha.

**Comment by oliv3** [comment]
Why would I ?

**Comment by PiotrIT** [comment]
Filters still do not work in both manager and www on Android devices :(
I noticed that running the browser in incognito mode filters work correctly.
Maybe this information will help solve the problem?

**Comment by tananaev** [comment]
Closing as it's not an issue with the modern app.
