### ISSUE TITLE
Spanish translation issue

### ISSUE THREAD

**Issue by galadtrans** [traccar/traccar-web#736]
Hi, es.json file has a translation issue. Both events geofence exit and geofence enter are translated like enter. On the other hand, low speed is traslated as fast acelleration. 
As a native spanish speaker I propose next traslation:
"eventGeofenceEnter" : "El dispositivo ha entrado en la geocerca"
"eventGeofenceExit" : "El dispositivo ha salido de la geocerca"
"alarmLowspeed": " Velocidad baja",

Another minor changes and no translated items are a attached. 
Hope it usefull
[es.txt](https://github.com/traccar/traccar-web/files/3111484/es.txt)

**Comment by tananaev** [comment]
All translations should be done through Transifex:

https://www.transifex.com/traccar/traccar
