### ISSUE TITLE
HTML entities ( # <'> & ") in MAP display are not decoded. 

### ISSUE THREAD

**Issue by skizzofly** [traccar/traccar-web#737]
Hello, with 4.3 there is a problem with Html Entities not decoded in map display.
this happens with Device names and with geo areas (and probably with all other things that appear as layer on display)
I applied already the fixes found on 

https://github.com/traccar/traccar-web/commit/04a92f0fbae8cee0e88b56e736a6c4178d39ca35

I attach some screen shots

![Igor](https://user-images.githubusercontent.com/49754801/56646047-1292c880-667f-11e9-8c95-edc38d64d5e9.jpg)
![geoarea](https://user-images.githubusercontent.com/49754801/56646074-1d4d5d80-667f-11e9-9ef0-1fab2d4bbb53.jpg)

**Comment by tananaev** [comment]
What other things are you talking about?

**Comment by skizzofly** [comment]
Any other text that user inputs and that can appear on the map
For now i only verified device names and geofences names, but i do not know
if drivers appear as i never used them.
If it's only devices and geofences, then better, less fixes to do ;-)
