### ISSUE TITLE
Mapbox.js

### ISSUE THREAD

**Issue by jcardus** [traccar/traccar-web#745]
Hi Guys,

First, congratulations for your great project.

I already forked the project and started using mapbox instead of open layers. Mapbox is built on top of leaflet and is much more professional and has some fantastic features. And it looks great on Traccar! You can check it out here: 

https://dev.pinme.io/debug.html
(admin / admin)

I know there's a project for a new web interface using leaflet, but that will take a lot of time and replacing OL it's not some much work.

I'm just writing this issue to discuss the change before I make the pull request.

Does it make sense to support different viewers? So you would choose the one you want (OpenLayers, Mapbox, Leaflet) on the configuration file, similar to what you do with the tiles provider (osm, bing, baidu)?

My idea is to abstract every map operation like addMarker, addGeonce, updateMarker and have a class implementing it for each provider. It would be like an interface and implementing classes. I don't know if Ext.js supports this but from what I see it looks like it can be done.

What do you think?

Regards

**Comment by tananaev** [comment]
Can you please provide more details on this:

> is much more professional and has some fantastic features

**Comment by jcardus** [comment]
Actually I meant to say Mapbox GL JS, Mapbox.js is not in actual development anymore

"Mapbox GL JS is a JavaScript library that uses WebGL to render interactive maps from vector tiles <https://docs.mapbox.com/help/glossary/vector-tiles/> and Mapbox styles <https://docs.mapbox.com/mapbox-gl-js/style-spec>. It is part of the Mapbox GL ecosystem, which includes Mapbox Mobile <https://www.mapbox.com/mobile/>, a compatible renderer written in C++ with bindings for desktop and mobile platforms.
“
The custom map styles from mapbox are simply beatiful. Being vector tiles gives the user a completely different (for better) user experience on the map. Not to say that it’s a lot faster than openlayers.
The guy that built leaflet actually works on mapbox.

I think the effort to use mapbox is the same as using leaflet, and I see on the new web interface that you plan to use it. As you must know it’s a lot faster and has a lot of plugins like marker clustering who can also improve the user experience.

The work for implementing leaflet is the same as for mapbox. With that said, being leaflet more consensual, I change my issue, and please consider leaflet instead of mapbox.

**Comment by tananaev** [comment]
I'm confused. Do you want Mapbox GL JS or Leaflet?

**Comment by jcardus** [comment]
Let’s stick with leaflet.
