### ISSUE TITLE
leaflet

### ISSUE THREAD

**Issue by jcardus** [traccar/traccar-web#746]
I'm thinking about implementing leaflet on this project.

I'm just writing this issue to discuss the change before I make the pull request.

Does it make sense to support different viewers? So you would choose the one you want (OpenLayers or Leaflet) on the configuration file, similar to what you do with the tiles provider (osm, bing, baidu)? 

Or just replace OpenLayers with Leaflet?

My idea is to abstract every map operation like addMarker, addGeonce, updateMarker and have a class implementing it for each provider. It would be like an interface and implementing classes. I don't know if Ext.js supports this but from what I see it looks like it can be done.

What do you think?

Regards

**Comment by tananaev** [comment]
It doesn't make sense unless there are some clear benefits.

**Comment by jcardus** [comment]
Yes, you're right. 

OL makes sense if you're building a webbased GIS fronted, which is not the case. 
Leaflet is more oriented to this kind of apps. Leaflet is a lot faster, a lot easier to use, has a smaller footprint, more fancy default icons and controls, has more activity on github so I guess its here to last, and has better plugins for marker clustering (which Traccar needs) and better plugins for moving effects (I want to implement the vehicles moving in uber style) and better route drawing.

I was also looking for a more fancy map style, but that can be done with the custom map. I did configure a custom map with the new mapbox style (which is not yet official on the tiles api) and it simply looks great!
Check it you at https://clientes.fleetrack.cl

**Comment by tananaev** [comment]
Sounds like everything is better in leaflet.
