### ISSUE TITLE
Optional custom CDN urls

### ISSUE THREAD

**Issue by edvalley** [traccar/traccar-web#750]
I, wrongly, started this here: [https://github.com/traccar/traccar/issues/4354](https://github.com/traccar/traccar/issues/4354)

**Comment by edvalley** [comment]
Now, will load.js be replaced on update? I guess it will, sometime, and that's the only problem I see on that approach. Any idea or suggestion? Thanks.

**Comment by tananaev** [comment]
I don't see a big issue with re-applying patch. Load.js rarely changes.

**Comment by edvalley** [comment]
I'm not saying it's an issue, not even big, it is just that it's not straight forward, it's not update and go, it's update and patch. Don't you like the idea of putting all that urls, or at least the `proto://server` part, in a file that won't change on update, or that at least, will allow us to make a backup, update, restore process, similar to configuration? Thanks for your time.

**Comment by tananaev** [comment]
I'm not a fan of this idea. Not a lot of people change these URLs, so I don't think it's worth complicating the code just for this small feature.

**Comment by edvalley** [comment]
Ok, I'm ok with that. Just one more thing, can we rearrange the code, lets say we put that urls on variables, one per line, so it's more patch friendly, and less probable to break patches in a near future? Thanks again.

**Comment by tananaev** [comment]
I think it's pretty patch-friendly already.

**Comment by edvalley** [comment]
Ok. I'll keep it like that. Thank you very much.
