### ISSUE TITLE
List driver assigned to devices

### ISSUE THREAD

**Issue by conde000011100** [traccar/traccar-web#752]
Hi, I am doing some tests to get the driver assigned to a device but I get lost, reviewing the documentation indicates that I have a deviceId, but when reviewing the api that field does not come. (https://www.traccar.org/api-reference/#path--drivers)
https://www.traccar.org/api-reference/#path--drivers--id-

Can you give me a hint please.

**Comment by tananaev** [comment]
Which API are you talking about?

**Comment by conde000011100** [comment]
I could already assign a driver to the device and the changes are reflected by API.

Now what I want is to know how I know what driver each device has.

https://www.traccar.org/traccar-api/

**Comment by tananaev** [comment]
If you want to get current driver, you should use positions API.

**Comment by conde000011100** [comment]
I am reviewing the api of positions but nothing comes concerning drivers, this is what I get.

`[{"id":4644,"attributes":{"distance":0.0,"totalDistance":1.09680378E7,"ip":"187.237.231.32","motion":false,"ignition":false,"hours":62174000},"deviceId":1,"type":null,"protocol":"gps103","serverTime":"2019-07-27T19:02:08.718+0000","deviceTime":"2019-07-27T19:02:08.718+0000","fixTime":"2019-07-27T16:21:55.000+0000","outdated":true,"valid":true,"latitude":19.374018333333332,"longitude":-98.96274,"altitude":0.0,"speed":0.0,"course":0.0,"address":"177 Río Francisco Villa, Los Reyes Acaquilpan, Méx., MX","accuracy":0.0,"network":{"radioType":"gsm","considerIp":false,"cellTowers":[{"cellId":19863,"locationAreaCode":259,"mobileCountryCode":0,"mobileNetworkCode":0}]}},{"id":80,"attributes":{"batteryLevel":43.0,"distance":26.47,"totalDistance":1329.98,"ip":"201.102.187.215","motion":false},"deviceId":2,"type":null,"protocol":"osmand","serverTime":"2019-07-25T18:21:50.000+0000","deviceTime":"2019-07-25T18:20:47.000+0000","fixTime":"2019-07-25T18:20:47.000+0000","outdated":false,"valid":true,"latitude":19.364936666666665,"longitude":-98.98064333333332,"altitude":2239.3,"speed":0.0,"course":0.0,"address":"8 Calle 2, Los Reyes Acaquilpan, Méx., MX","accuracy":0.0,"network":null},{"id":4525,"attributes":{"batteryLevel":37.0,"distance":9.93,"totalDistance":8795.4,"ip":"201.102.187.215","motion":false},"deviceId":4,"type":null,"protocol":"osmand","serverTime":"2019-07-27T17:02:36.165+0000","deviceTime":"2019-07-27T16:02:36.000+0000","fixTime":"2019-07-27T16:02:36.000+0000","outdated":false,"valid":true,"latitude":19.364898333333333,"longitude":-98.98080833333333,"altitude":2234.1,"speed":0.0,"course":151.4499969482422,"address":"22 Calle 2, Los Reyes Acaquilpan, Méx., MX","accuracy":0.0,"network":null},{"id":3568,"attributes":{"Tipo":"LOCK","NOUSADO1":"1","NOUSADO2":"2","NOUSADO3":"3","NOUSADO4":"4","alarm":"sos","NOUSADO5":"5","NOUSADO6":"6","NOUSADO7":"7","index":4000,"distance":0.0,"totalDistance":0.0,"ip":"201.102.187.215","motion":true},"deviceId":5,"type":null,"protocol":"iwatcher","serverTime":"2019-07-27T04:33:07.228+0000","deviceTime":"2013-10-06T11:56:02.002+0000","fixTime":"2013-10-06T11:56:02.002+0000","outdated":false,"valid":true,"latitude":32.155651,"longitude":34.92035,"altitude":0.0,"speed":150.0,"course":0.0,"address":"5 Mevo Kedem, Hod HaSharon, Center District, IL","accuracy":0.0,"network":null},{"id":3567,"attributes":{"Tipo":"MOBILEYE","alarm":"mobileyeTamper","index":24,"distance":0.0,"totalDistance":0.0,"ip":"201.102.187.215","motion":false},"deviceId":6,"type":null,"protocol":"iwatcher","serverTime":"2019-07-27T04:33:07.096+0000","deviceTime":"2015-05-26T05:17:37.037+0000","fixTime":"2015-05-26T05:17:37.037+0000","outdated":false,"valid":true,"latitude":19.3646524,"longitude":-98.980759,"altitude":0.0,"speed":0.0,"course":0.0,"address":"5 Calle 2, Los Reyes Acaquilpan, Méx., MX","accuracy":0.0,"network":null},{"id":0,"attributes":{"Tipo":"POS","status":1,"hdop":3.0,"gps":2.0,"sat":4.0,"tripOdometer":211.9,"totalDistance":0.0,"opcional1":"105","opcional2":"0","index":36252,"distance":0.0,"ip":"201.102.187.215","motion":false},"deviceId":12,"type":null,"protocol":"iwatcher","serverTime":"2019-07-27T04:40:53.879+0000","deviceTime":"2013-01-03T00:01:27.000+0000","fixTime":"1970-01-01T00:00:00.000+0000","outdated":true,"valid":true,"latitude":38.075521,"longitude":23.768787,"altitude":0.0,"speed":0.0,"course":14.1,"address":"7 Sorou, Metamorfosi, GR","accuracy":0.0,"network":null},{"id":0,"attributes":{"Tipo":"POS","status":1,"hdop":3.0,"gps":3.0,"sat":10.0,"tripOdometer":14.1,"totalDistance":146186.12,"index":40,"distance":146186.12,"ip":"201.102.187.215","motion":false},"deviceId":13,"type":null,"protocol":"iwatcher","serverTime":"2019-07-27T04:44:06.275+0000","deviceTime":"2032-01-09T12:56:09.000+0000","fixTime":"1970-01-01T00:00:00.000+0000","outdated":true,"valid":true,"latitude":31.155683,"longitude":35.920255,"altitude":0.0,"speed":0.0,"course":15.5,"address":"Karak Governorate, JO","accuracy":0.0,"network":null}]`

I hope it helps what I am trying to do when we click on a device to show me in a window which driver has the device assigned.

**Comment by tananaev** [comment]
Assigned or current driver?
