### ISSUE TITLE
BingKey Vulnerability?

### ISSUE THREAD

**Issue by rljdavies** [traccar/traccar-web#753]
Hi there, 

Great project well done.

I notice before a session is created the dictionary file is downloaded, which is what I was expecting, and then server config is downloaded too.   This happens before authentication.

Most of the information in the server config is pretty bland and uninteresting, but if a BingKey has been configured it is disclosed in the json response to the api call, again, prior to authentication.  Even if the user were to be authenticated this does not seem right to me.   

I have attached a request timeline from your demo platform to illustrate.

![Screenshot 2019-07-28 at 14 54 58](https://user-images.githubusercontent.com/6506022/62007682-66aebc80-b148-11e9-87c6-c39f0236f788.png)

Thanks
Rich

**Comment by tananaev** [comment]
It's not a vulnerability. Client needs the key to display the map.

**Comment by rljdavies** [comment]
thanks for the reply and yes I understand why the key is required.  I haven't looked at bing maps recently so I'm unsure what the financial risk of other people using this key in their own applications would be.

**Comment by tananaev** [comment]
The solution here is to restrict key to be used only by specific domain and only for displaying map tiles. I know you can do it for Google key. I'm sure Bing has some similar configuration for keys.

**Comment by rljdavies** [comment]
agreed, but is it essential the call to api/server happens before session get or post?

**Comment by tananaev** [comment]
Yes, it has configuration that we need to know for login. For example, if user registration is enabled. Also, potentially in some future version of the web app, we might show map straight away.

**Comment by rljdavies** [comment]
fair enough.....Im building a native iOS app which is heavily feature stripped so I can probably implement differently.

Thanks for your response.
