### ISSUE TITLE
traccar-web/modern Device list shows only active devices after socket message

### ISSUE THREAD

**Issue by dixith** [traccar/traccar-web#755]
![image](https://user-images.githubusercontent.com/7497698/62254926-b4f9df00-b418-11e9-8840-3a1e9d705030.png)

Modern web:
![image](https://user-images.githubusercontent.com/7497698/62255079-55500380-b419-11e9-9418-1e4fe934801e.png)

Modern web uses same state variable for devices(Registered devices and active devices) because of this after the socket message device list shows only active devices.

**Comment by tananaev** [comment]
It must have been fixed at some point.
