### ISSUE TITLE
markers are missing

### ISSUE THREAD

**Issue by iceberg1369** [traccar/traccar-web#757]
markers are not showing on the map. when I click on the device the map location changes but markers are not loaded into map.
![Capture](https://user-images.githubusercontent.com/4116434/63494101-40bfd200-c4d2-11e9-9cd7-a240e866abf1.PNG)

**Comment by garageeks** [comment]
Same here, they disappeared. I don't see missing files from Console Log, however icons are hosted on 3rd party server, maybe they messed up with the font file?

**Comment by tananaev** [comment]
Check browser console. Also use forum for questions instead of GitHub.
