### ISSUE TITLE
Google stellite map, not show street name 

### ISSUE THREAD

**Issue by zawyehtet** [traccar/traccar-web#759]
How can i set street name in google satellite map?

**Comment by zawyehtet** [comment]
Pl, How can i add google satellite on default map layer

**Comment by Turbovix** [comment]
Friend, you should ask for help in the forum!

https://www.traccar.org/map-layers/

**Comment by zawyehtet** [comment]
Thanks, 
Now i am using custom map(google satellite ).
Would that be ok ?
i want to use as default and how to configuration it.
Pls

**Comment by tananaev** [comment]
Please use forum for questions.
