### ISSUE TITLE
Dynamic track playback

### ISSUE THREAD

**Issue by oopsoft** [traccar/traccar-web#76]
System has not achieved track playback function. Can get to the latitude and longitude coordinates, these coordinates can be concatenated portrayed its running track, running track, he can play.
for example:   http://www.gpsoo.net/track-history.jsp?objectID=65979

**Comment by Transglobalgeomatics** [comment]
hi,

Where can we check the vehicle travelled distance in map with history back up..?

**Comment by spacecabbie** [comment]
> hi,
> 
> Where can we check the vehicle travelled distance in map with history back up..?
Please ask support questions on the forum: https://www.traccar.org/forums/

**Comment by spacecabbie** [comment]
> System has not achieved track playback function. Can get to the latitude and longitude coordinates, these coordinates can be concatenated portrayed its running track, running track, he can play.
> for example: http://www.gpsoo.net/track-history.jsp?objectID=65979

I am not sure what is wanted but we have route reports now so unless that not what you where looking for i think we can close this.

**Comment by tananaev** [comment]
We have playback in the modern app.
