### ISSUE TITLE
problem with retreiving the session

### ISSUE THREAD

**Issue by vaskovasilev** [traccar/traccar-web#760]
hello dear team,
sometimes when i try to retrieve new session, i get:
```
Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value - IllegalArgumentException (... < DataConverter:40 < SessionResource:66 < ...)
```
i am making get request like:
```
server/api/session?token=....
```
if i login manually and then open the same link - it is working.
this means it is not creating a session only by token.

can you tell me what can be the problem.

thank you

**Comment by tananaev** [comment]
Please use forum for questions.

**Comment by vaskovasilev** [comment]
but this is a problem with the server..
