### ISSUE TITLE
status 

### ISSUE THREAD

**Issue by spacecabbie** [traccar/traccar-web#761]
Just quick question is new ui still in development or suspended atm ?

Last commits where 1 year ago just wondering if i should mod mine.

**Comment by tananaev** [comment]
Last commit is 13 days ago. It's maintained and supported, but I don't think we are actively adding new major features, but pull requests are welcome.

**Comment by spacecabbie** [comment]
> Last commit is 13 days ago. It's maintained and supported, but I don't think we are actively adding new major features, but pull requests are welcome.

Oh just to be sure i was referencing to traccar-web/modern/ Current web is quite maintained ofc. Didn't mean to imply it wasn't.

**Comment by tananaev** [comment]
I haven't done any work on the modern version, but pull requests are welcome there as well.

**Comment by spacecabbie** [comment]
> I haven't done any work on the modern version, but pull requests are welcome there as well.

Truly wish i could but my coding is very limited and mainly web based css php html.
I tend to change and update templates where it suits me. But with the recompile needed of the web files that unfortunately is not a option for me atm. 
Although debug works but am afraid of the performance. If wished i can ofc share my changes. Mainly adding logo of our company and add text with instructions. 

thanks for the speedy reply is it only you working on the code currently ?

Do let me know if i can help out in any other way. I have send you install manual for centos. Wil make some more to extend the current documentation a bit. To make it "newbie" proof ? 👍 

Also will update the centos one for compatibility with directadmin later this week. (mainly setup proxy redirect)

If you have any request do not hesitate to ask me.

**Comment by tananaev** [comment]
Mostly me with some occasional contributions from others.
