### ISSUE TITLE
(re) enable OpenSeaMap as a base map

### ISSUE THREAD

**Issue by webkrab** [traccar/traccar-web#763]
Hi,

Great job i love the work of Traccar.
On the forum & the internet, i find multiple request for OpenSeaMap integration.
In a very old thread here on the GitHub, https://github.com/vitalidze/traccar-web/issues/203#issuecomment-121378767 is mentioned, it is be integrated.

Unfortanly i cant find it anymore in the current Traccar version.

**Comment by tananaev** [comment]
What you are referring to is not an official Traccar version.

**Comment by webkrab** [comment]
Ah okay that explains, unfortanly also a older version, so i cant use it for inspration to find a solution.
Anybody tips?

**Comment by tananaev** [comment]
Modern app now has an OpenSeaMap overlay.
