### ISSUE TITLE
Usefull option? Switching maps

### ISSUE THREAD

**Issue by webkrab** [traccar/traccar-web#764]
By using the traccar, i discover the wish to switch between a card & areal photo.
Maybe in a new release there can be an option, that in the active screen, we can switch between the map-layers.

It will also be nice, when there is a posibility to connect to "online" files from for example google maps, and i dont need to export a KML to the local server.
And also enable/disable (switching) in a user setup wil be nice.

**Comment by tananaev** [comment]
This is already available in both apps.
