### ISSUE TITLE
Accuracy circle on map is calculated wrong/Shows wrong distance

### ISSUE THREAD

**Issue by hansherlighed** [traccar/traccar-web#765]
As far as I can see, the calculation of the accuracy circle around objects, is calculated wrong on the map. Look at the screenshot I have attached. The accuracy in the details panel is set to 100.00km(In the Database the value is 100000).
According to the map, the scale is set to 100m and that distance is what the accuracy circle is showing as being the accuracy, even though it should be set to 1000m. Seems the accuracy circle is off by a factor of 10
![accuracy_circle](https://user-images.githubusercontent.com/47210174/73524138-c72af900-440c-11ea-9b55-a1cee36ae285.jpg)

**Comment by tananaev** [comment]
Fixed, thanks.
