### ISSUE TITLE
Web: Report Color selection does not work with Safari

### ISSUE THREAD

**Issue by ckrey** [traccar/traccar-web#766]
Selection of new color has no effect in Safari (13.0.5) on macOS
Works with Chrome

![Bildschirmfoto 2020-02-28 um 08 51 51](https://user-images.githubusercontent.com/4027289/75521345-d733f980-5a07-11ea-9f76-fe071e866c9d.png)

**Comment by tananaev** [comment]
I don't think we can do anything about that. Probably another ExtJS issue.

**Comment by tananaev** [comment]
Closing as it's not related to the modern app.
