### ISSUE TITLE
No scroll after updating to 4.9 on mobile

### ISSUE THREAD

**Issue by karls4** [traccar/traccar-web#776]
After updating the application to 4.9 I can no longer move the map with my fingers, I need to zoom out and in again to see the positions.

**To Reproduce**
1. Open Mobile Application
2. Try move the map

**Expected behavior**
The map to move when moving

**Comment by dough29** [comment]
Yes same here !

**Comment by tananaev** [comment]
Interesting. Maybe it's related to the new version of OpenLayers.

**Comment by dough29** [comment]
When I double tap to zoom in then I can scroll.

**Comment by tananaev** [comment]
Fixed in 2a22ce7c01b5e75c029705ff043c9c08ba7592cc. Had to downgrade OpenLayers library.

**Comment by carlosedunascimento** [comment]
Same problem in 4.10, map does not move in mobile.

**Comment by karls4** [comment]
Hi,

This has become an issue again after the latest release

**Comment by tananaev** [comment]
I was hoping they fixed the issue. Will investigate.

**Comment by tananaev** [comment]
Applied another fix. This time it works with the latest version of OpenLayers.

**Comment by karls4** [comment]
Thank you for the quick response.

**Comment by legrandron** [comment]
> 
> 
> Applied another fix. This time it works with the latest version of OpenLayers.

Where can i find this fix? I am experiencing this issue

**Comment by tananaev** [comment]
It's in the latest source code.

**Comment by legrandron** [comment]
> 
> 
> It's in the latest source code.

Thanks. Do i need to reinstall completely or just update web/load.js?

**Comment by tananaev** [comment]
You have to compile new version of the web app.

**Comment by legrandron** [comment]
> 
> 
> You have to compile new version of the web app.

Just for clarity, do you mean rebuilding Traccar manager app?

**Comment by tananaev** [comment]
No, **web** app.
