### ISSUE TITLE
Modern version - Scroll bar in the EDGE browser

### ISSUE THREAD

**Issue by lukasha12** [traccar/traccar-web#777]
The scroll bar appears in the EDGE browser where it should not.
Microsoft Edge 44.18362.449.0

![Traccar_EDGE](https://i.ibb.co/VJT8QZ7/trac.jpg)

**Comment by tananaev** [comment]
Is that the version that's based on Chrome? Do you have any specific backward compatibility enabled or is it a default configuration?

**Comment by lukasha12** [comment]
This is the EDGE browser provided with Windows 10 in the default configuration.
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

**Comment by lukasha12** [comment]
I reinstalled server and I delete cookie, cache etc from EDGE. The problem is still there.
In addition, I noticed (I don't know if it was before) that the elements were not positioned correctly on the login screen.

![Login_EDGE](https://i.ibb.co/8DSBC49/trac1.jpg)

**Comment by tananaev** [comment]
Thanks for reporting the issue.

**Comment by tananaev** [comment]
Closing as there were a lot of changes and it shouldn't be a problem anymore. If it's still happens, please let me know.
