### ISSUE TITLE
Push Google tag manager events

### ISSUE THREAD

**Issue by RafaelMiquelino** [traccar/traccar-web#780]
Hi @tananaev, I included an integration with Google Tag Manager on my fork of Traccar-web. It’s a simple implementation to push events to GTM and monitor user engagement and usage on the web app using Google Analytics.
For the time being I’m pushing just three events to monitor app loaded, login and logout but it’s possible to be extended in the future. This allow us to go further than just monitoring pageviews. 
To enable it all you need to to do is to set an attribute and add the account specific GTM tracking code to the `release.html` file. 

Please let me know if that’s something interesting to integrate as a standard Traccar-web feature and I’ll issue a pull request. 

You can see the changes here: https://github.com/traccar/traccar-web/compare/master...RafaelMiquelino:google_tag_manager

**Comment by tananaev** [comment]
I don't think it's a good idea to include Google proprietary code in an open source solution by default. How does it actually work? I don't see any extra dependencies in the changes that you linked.

**Comment by RafaelMiquelino** [comment]
I don't see it as a default option but as an add-on, the same way we have several providers for the reverse geo-location feature on the server.
There is no aditional dependencies on the code, they are loaded from the `release.html`. It is quite the same for the Google Analytics.
To enable it, you need to set an attribute and also included your own account tracking code (provided by Google) on the `release.html` file and then it start pushing the events to GTM throught the dataLayer object. Once on GTM, you can push it to Google Analytics or several other "tags" (full list [here](https://support.google.com/tagmanager/answer/6106924?hl=en&ref_topic=3281056)).
You can find more details about the Google Tag Manager here: https://support.google.com/tagmanager/answer/6102821?hl=en&ref_topic=3441530

**Comment by tananaev** [comment]
What is loaded from `release.html`? I don't see any changes to `release.html` in your code.

**Comment by RafaelMiquelino** [comment]
I didn’t put it on the standard code as part of this needs to be loaded in the `<head>` and there is no way to conditionally remove it. So the user will have to add it if he wants to use the feature. This is the code that needs to be added:  
In the `<head>`  
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer',’GTM-XXXXX');</script>
<!-- End Google Tag Manager —>
```
In the `<body>`:  
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) —>
```

**Comment by tananaev** [comment]
GitHub doesn't recognize markdown in email comments. Can you please replace your comment with something more readable.

**Comment by RafaelMiquelino** [comment]
I didn’t put it on the standard code as part of this needs to be loaded in the `<head>` and there is no way to conditionally remove it. So the user will have to add it if he wants to use the feature. This is the code that needs to be added:
In the `<head>`
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer',’GTM-XXXXX');</script>
<!-- End Google Tag Manager —>
```
In the `<body>`:
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) —>
```

**Comment by tananaev** [comment]
So there is a dependency.

**Comment by RafaelMiquelino** [comment]
Ok, so shall we continue the discussion or close this issue and leave it behind? As I told, this is implemented and I’m using this on my fork but it may not be interesting as a general use case.

**Comment by tananaev** [comment]
I think we should close it for now. It seems very tied to Google analytics.

**Comment by RafaelMiquelino** [comment]
Ok, no problem, I see. Let me know if this turns out to be a general use case and I can issue a pull request.

**Comment by tananaev** [comment]
Sure, thanks.
