### ISSUE TITLE
Slowness when opening an interface that contains +500 vehicles

### ISSUE THREAD

**Issue by JBFelizberto** [traccar/traccar-web#783]
reference:  https://www.traccar.org/forums/topic/modern-traccar-web/

After logging in using an administrator user, who will see +500 devices:

- takes a long time to appear on the map and, it presents a lot of block and crash, especially when using the zoom, even appear the screen is blank that force to reload the browser

- Sometimes, the processor computer goes to 100% of the due process in chrome (only opened this interface and no more)

**Comment by tananaev** [comment]
I believe this is already fixed.
