### ISSUE TITLE
"server responded with a status of 404" /l10n/en.json

### ISSUE THREAD

**Issue by alexbk66** [traccar/traccar-web#787]
I have same problem described here: https://www.traccar.org/forums/topic/login-window-wont-load-remotely/

When I load the website using https:// (even locally on the server) - the background image is loaded, the spinning wheel is showing.

Console window shows /l10n/en.json 404 (Not Found).

The server is Windows Server 2008, IIS 7.  
I checked, the file exists, permissions are fine.

![image](https://user-images.githubusercontent.com/2533315/94989901-4a63a680-05bb-11eb-8eae-dc80969e9524.png)

**Comment by alexbk66** [comment]
Update: after a bit of Googling and some fiddling now I get error 502.3

![image](https://user-images.githubusercontent.com/2533315/94993219-c1586980-05d2-11eb-8542-d084ca45807e.png)

**Comment by tananaev** [comment]
How is this related to Traccar? Why is there IIS involved? Traccar has its own web server.

**Comment by alexbk66** [comment]
Ok, I must be in the wrong place?
Yeah, Anton, you are right, it's not a Traccar problem, it's a problem with my installation of Traccar.
