### ISSUE TITLE
Discussion Regarding Chart Library - Recharts

### ISSUE THREAD

**Issue by mail2bishnoi** [traccar/traccar-web#796]
Hi Anton,

Should we use [http://recharts.org/en-US](url) chart library for chart reporting? It's based on React plus D3 and fully supports SVG.

**Comment by tananaev** [comment]
Your link is broken.

**Comment by mail2bishnoi** [comment]
https://recharts.org/en-US/

**Comment by tananaev** [comment]
Looks like a pretty solid option. I like it.

**Comment by mail2bishnoi** [comment]
Can I start implementation chart  reports using this?

**Comment by tananaev** [comment]
Sure, feel free to send a pull request.

**Comment by mail2bishnoi** [comment]
Ok. Thanks.

**Comment by mail2bishnoi** [comment]
.
