### ISSUE TITLE
Report feature not working

### ISSUE THREAD

**Issue by asmitamt** [traccar/traccar-web#798]
**Describe the bug**
Gave 17-11-2020 00:00 to 17-11-2020 23:45 shows no records even though there is data for the particular device. We tried different reports but faced same problem

When tried same thing with chart got error.
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by tananaev** [comment]
You would need to prove that that's a bug in Traccar. So far I don't see any concrete details.
