### ISSUE TITLE
Error in running Traccar Server

### ISSUE THREAD

**Issue by MuhammedRefaat** [traccar/traccar-web#80]
i have an error happens when launching the server : 
the error from the wrapper logger : 
STATUS | wrapper  | 2013/07/15 09:40:21 | Traccar service installed.
STATUS | wrapper  | 2013/07/15 09:42:36 | --> Wrapper Started as Service
STATUS | wrapper  | 2013/07/15 09:42:37 | Java Service Wrapper Community Edition 32-bit 3.5.19
STATUS | wrapper  | 2013/07/15 09:42:37 |   Copyright (C) 1999-2013 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2013/07/15 09:42:37 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2013/07/15 09:42:37 | 
STATUS | wrapper  | 2013/07/15 09:42:38 | Launching a JVM...
FATAL  | wrapper  | 2013/07/15 09:42:38 | Unable to execute Java command.  The system cannot find the file specified. (0x2)
FATAL  | wrapper  | 2013/07/15 09:42:38 |     "java" -Djava.library.path="../lib" -classpath "../lib/wrapper.jar;../tracker-server.jar" -Dwrapper.key="ZPkFvKrE3aVlbAHB" -Dwrapper.port=32000 -Dwrapper.jvm.port.min=31000 -Dwrapper.jvm.port.max=31999 -Dwrapper.pid=3192 -Dwrapper.version="3.5.19" -Dwrapper.native_library="wrapper" -Dwrapper.arch="x86" -Dwrapper.service="TRUE" -Dwrapper.cpu.timeout="10" -Dwrapper.jvmid=1 org.tanukisoftware.wrapper.WrapperSimpleApp org.traccar.Main "C:\Program Files (x86)\Traccar\conf\traccar.cfg"
ADVICE | wrapper  | 2013/07/15 09:42:38 | 
ADVICE | wrapper  | 2013/07/15 09:42:38 | --------------------------------------------------------------------
ADVICE | wrapper  | 2013/07/15 09:42:38 | Advice:
ADVICE | wrapper  | 2013/07/15 09:42:38 | Usually when the Wrapper fails to start the JVM process, it is
ADVICE | wrapper  | 2013/07/15 09:42:38 | because of a problem with the value of the configured Java command.
ADVICE | wrapper  | 2013/07/15 09:42:38 | Currently:
ADVICE | wrapper  | 2013/07/15 09:42:38 | wrapper.java.command=java
ADVICE | wrapper  | 2013/07/15 09:42:38 | Please make sure that the PATH or any other referenced environment
ADVICE | wrapper  | 2013/07/15 09:42:38 | variables are correctly defined for the current environment.
ADVICE | wrapper  | 2013/07/15 09:42:38 | --------------------------------------------------------------------
ADVICE | wrapper  | 2013/07/15 09:42:38 | 
FATAL  | wrapper  | 2013/07/15 09:42:39 | Critical error: wait for JVM process failed

**Comment by edgiru** [comment]
такая же ошибка

STATUS | wrapper  | 2015/10/26 15:32:10 | Launching a JVM...
FATAL  | wrapper  | 2015/10/26 15:32:10 | Unable to execute Java command.  Не удается найти указанный файл. (0x2)

до явы путь указан правильно. из командной строки ява нормально вызывается.

**Comment by tananaev** [comment]
@edgiru, какую операционную систему используете? Traccar сервис работает от имени системного пользователя, у него могут быть другие пути прописаны. Подозреваю что у вас Java прописана только для текущего пользователя.

**Comment by edgiru** [comment]
Спасибо Вам за ответ. Вообщем все снес JDK JRE несколько версий стояло. снес все пути прописаные в path. Все заново настроил и прописал. Все заработало. Все же была моя ошибка не правильной прописке path.
