### ISSUE TITLE
Login session "expires" after 24hrs and asks to login even though you click "remember"

### ISSUE THREAD

**Issue by est61** [traccar/traccar-web#801]
**Describe the bug**
When clicking "remember" in the login screen, whether its in Android or the web interface. After 24hrs passes, the session expires and asks to login again.
This never was the case with v4.6 Server.
Ive noticed this happening over the passed few weeks after upgrading.

Is there a specific setting to keep the session cookie to NOT expire until the user decides to clear cache and cookies?

**Expected behavior**
On v4.6 This never used to happen, the only time it asked me to re-login is only when the actual server did a reboot.  Other than that, it kept me logged in on phone and firefox.

**Desktop (please complete the following information):**
 - Browser Firefox 

**Smartphone (please complete the following information):**
 - Device: Oneplus 6t, Android 9

Server v4.11

**Comment by tananaev** [comment]
My guess is that it's something in the Firefox. Maybe they have time limit on cookies.

**Comment by est61** [comment]
Remember i said that this never happened in Server v4.6.  Its not Firefox.  And what about the Android app? it cant be coincidence.

**Comment by est61** [comment]
Does "remember" checkbox work for you for more than a day without it logging you out?

**Comment by est61** [comment]
@tananaev i reverted back to Server 4.6 and its been more than 24hrs now and it hasnt logged me out, **neither on the App nor Firefox**.  v4.6 Only ever logged me out when i restarted the server.  So it means something is wrong on v4.11, it seems as though the cookies/session is maybe expiring much sooner or something else is logging the user out.

Please can I ask you not to dismiss this and to have a look at what is causing it in v4.11 ?

**Comment by tananaev** [comment]
Maybe you can check Jetty version difference and read their changelog to see if there were any relevant changes.

**Comment by est61** [comment]
Apologies @tananaev i sorted it out, the fault was on my end.

**Comment by tananaev** [comment]
What was the cause of the issue?

**Comment by est61** [comment]
I had an automated script to backup the server, so it would stop and start the traccar service each time, So everytime traccar service restarted, it clears all logins.  Was wondering if its possible to persist logged-in users, even after restarting the service?

**Comment by dough29** [comment]
What do you have to backup other than the database ?
