### ISSUE TITLE
marker color based on digital input

### ISSUE THREAD

**Issue by MarcSN311** [traccar/traccar-web#805]
It would be great if the Tracker color could be linked to a digital input instead of online/offline status.

I tried to get familiar with the code base to implement this feature myself, but my code changes don't seem to have any effect on the page. Do I have to flush a cache or something like that?

**Comment by tananaev** [comment]
We've finally added support for custom marker color logic. You need to have the "color" attribute in the position to override status color. You can use computed attributes to achieve it. For example, if you want to change color on digital input, you can have an expression like this:
```
di1 ? "primary" : null
```

Supported color options:
- primary - brand color (indigo by default)
- positive - green
- negative - red
- neutral - gray
