### ISSUE TITLE
issue on adding something on calendar

### ISSUE THREAD

**Issue by emsici** [traccar/traccar-web#807]
**Describe the bug**
I try to create a calendar and i receive this error:

```
Error at line 1:Unexpected end of file
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 32] (through reference chain: org.traccar.model.Calendar["data"])
```
![tracar](https://user-images.githubusercontent.com/7910648/104020286-9ed37f00-51c5-11eb-82b7-de7612429f8b.PNG)

**To Reproduce**
1. Click on 'Settings' icon
2. Click on 'Calendars'
3. Click on 'Add'
4. Enter a name 
5. Click submit

**Expected behavior**
An entry to be added.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version latest

**VPS Settings**
root@grab:/opt/traccar/logs# cat /etc/issue
Ubuntu 20.04.1 LTS \n \l

root@grab:/opt/traccar/logs# uname -a
Linux grab.e5pl.com 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@grab:/opt/traccar/logs#

**Additional context**
I also tested on demo.traccar.org and i receive the same error there.

**Comment by tananaev** [comment]
You are missing a step. You have to upload the calendar file itself. Have you done that?

**Comment by emsici** [comment]
No, sorry, i thought it creates from that form, thanks.
