### ISSUE TITLE
[Modern] Markers do not display correctly on Firefox

### ISSUE THREAD

**Issue by nicolas-perez** [traccar/traccar-web#809]
**Describe the bug**
Using Firefox, markers are not displayed correctly on the map. Only the white background appears.

**To Reproduce**
Open the traccar app on Firefox.
See video: https://user-images.githubusercontent.com/4498566/104137810-e3b30d80-539f-11eb-9275-afe8fd71a674.mp4

**Expected behavior**
The markers on the map should display correctly on Firefox. 

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Browser: Firefox
 - Version: 84 (latest)

**Comment by Mindreader12345** [comment]
Same Problem here in modern Web
Firefox Version 86 (latest)

**Comment by Fmstrat** [comment]
Now the icons do not appear at all in Firefox. It seems there may be a `drawImage` that is attempting to run before the canvas loads:
```
Uncaught (in promise) DOMException: CanvasRenderingContext2D.drawImage: Passed-in canvas is empty
```

**Comment by tananaev** [comment]
Have you tried a version from master?

**Comment by tananaev** [comment]
The issue is already fixed.
