### ISSUE TITLE
[Modern] Bug when switching between mapbox map styles

### ISSUE THREAD

**Issue by nicolas-perez** [traccar/traccar-web#810]
**Describe the bug**
When switching to one of the 3 Mapbox map styles, sometimes the app crashes. 

**To Reproduce**
Try switching to each of the Mapbox map styles. You may have to try switching multiple times to reproduce the error. 
See video: https://user-images.githubusercontent.com/4498566/104137903-8b304000-53a0-11eb-8d0a-1866b0a852ae.mp4

**Expected behavior**
We should be able to switch between the 3 Mapbox map styles without the app failing. 

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Browser: Firefox
 - Version: 84 (latest)

**Additional context**
The mapboxAccessToken has been correctly set up in the server attributes.

**Comment by tananaev** [comment]
The issue is already fixed.
