### ISSUE TITLE
Show management device location in the APP

### ISSUE THREAD

**Issue by Artiom-M** [traccar/traccar-web#816]
It would be good to the in the APP the phone location. When searching for something/someone it will really help.

**Comment by tananaev** [comment]
It's already available, unless I misunderstand something.

**Comment by Artiom-M** [comment]
Well, the current Traccar Management android application doesn't show **it's own location** on the map. This is what the request about. It can be worked around by installing Traccar Client, but its far the best option. Client will work all the time (and consume battery) while what is really needed is to show my own location when I open Traccar Manager to see the tracker's location.
Other good features could be:

-  distance to the tracker (may be even route ? LocationIQ proposes routing service in the same free bundle).
-  automatic zoom so you and the tracker are on the screen

**Comment by tananaev** [comment]
Have you checked the modern web app?

**Comment by Artiom-M** [comment]
Yes, I am using APK downloaded from github, the latest. And it doesn't even ask for location permissions

**Comment by tananaev** [comment]
How is APK related to the web app?

**Comment by Artiom-M** [comment]
Ok, probably I have posted in the wrong repository...

**Comment by Artiom-M** [comment]
By the way Just had a look at the web app and cannot find it

**Comment by Artiom-M** [comment]
So now I have 4.12 modern interface and still cannot find my location there.

**Comment by tananaev** [comment]
Screenshot?

**Comment by Artiom-M** [comment]
I have added a screenshot

**Comment by tananaev** [comment]
This button should show your location:
<img width="80" alt="Screen Shot 2021-02-11 at 12 16 08 AM" src="https://user-images.githubusercontent.com/1161863/107614041-60831280-6bfe-11eb-9b00-75efec92cc7c.png">

If it doesn't work, then your browser doesn't support the location API.

**Comment by Artiom-M** [comment]
I've tested the browsers and they **does** support location API. Here are test screenshots:
![Screenshot_20210212-120441_Samsung Internet](https://user-images.githubusercontent.com/4058815/107729451-122c5b80-6d45-11eb-85b9-26eb2135af0d.jpg)
It asks for permission, then shows the location
![Screenshot_20210212-120533_Samsung Internet](https://user-images.githubusercontent.com/4058815/107729478-26705880-6d45-11eb-8af3-ea46919c366c.jpg)
This is from Samsung's browser. Google Chrome works the same, however in traccar web the button you are pointing to is not working.
![Screenshot_20210212-120759_Chrome](https://user-images.githubusercontent.com/4058815/107729547-54559d00-6d45-11eb-98f5-095cd88fdbe1.jpg)
In samsung browser that I've posted earlier if I click it, it will turn to grey as on Chrome screenshot and no way to turn it back except reload.

**Comment by tananaev** [comment]
It works on a desktop browser. Could be some issue on mobile.

**Comment by Artiom-M** [comment]
What desktop browser? I've tried in firefox and the button greyed out saying "Location not available". And it didn't as for location permission. The same browser another tab works well with mylocation.org.

**Comment by tananaev** [comment]
Chrome.

**Comment by Artiom-M** [comment]
Doesn't work in Chrome
![image](https://user-images.githubusercontent.com/4058815/107733232-9800d480-6d4e-11eb-9a63-eb3cb16d39b3.png)

**Comment by jmatbastos** [comment]
own location button in demo.traccar.org web site and manager set to demo.traccar.org works
but own location button in personal server version 6.7.2 does not work...
Why? Any suggestions?

**Comment by jmatbastos** [comment]
Answering above question:
personal web server must have https protocol activated (port 443 open) ...
[https://www.traccar.org/secure-connection/](url)
