### ISSUE TITLE
Utilization Coulumn in Summary and Daily Summary Report

### ISSUE THREAD

**Issue by mail2bishnoi** [traccar/traccar-web#820]
Hi Anton,

I want to add a new column utilization to the Summary and Daily Summary reports. By utilization, I mean how many hours a vehicle remained moving in the selected time period. See attachment for more information-

![utilization](https://user-images.githubusercontent.com/41992346/109114679-fe7cee00-7763-11eb-838c-b53207e85c0b.jpeg)

**Comment by tananaev** [comment]
Don't we already have hours there?

**Comment by mail2bishnoi** [comment]
Hi Anton,

Yes, Engine hours are there. But I have 2 questions -
1. From what is calculated from the vehicle's movement or ignition status?
2. How can the engine hours be expressed as a percentage?

I want to show in percentage because when the selected time period is more than 24 hours, such as a week, a month, the percentage value is more useful for analysis. And absolute values are more useful for less than 24 hours.

**Comment by tananaev** [comment]
I guess I'm not strongly against it, but I would keep only the absolute value, to make it consistent.

**Comment by mail2bishnoi** [comment]
Ok. No problem.
