### ISSUE TITLE
[Modern] web UI do not show some characters

### ISSUE THREAD

**Issue by vitekf** [traccar/traccar-web#824]
I use this "name" for my scooter: "ₒ-\ₒ"
It is ok in old web interface, 
In Modern interface is visible on map only: "-\\"  (missing first and last character - wheels :-)
(In device list is it ok: "ₒ-\ₒ")

**Comment by tananaev** [comment]
Works for me
<img width="158" alt="Screen Shot 2021-03-09 at 10 03 40 AM" src="https://user-images.githubusercontent.com/1161863/110516679-c1e3b780-80be-11eb-8067-65a2e3c23509.png">
