### ISSUE TITLE
Show or hide table column dynamically for reports and other tables

### ISSUE THREAD

**Issue by mail2bishnoi** [traccar/traccar-web#826]
Hi Anton,

I want to start development to show and hide columns in the reports and other tables.

Would you like to recommend me a package? However, I have thought of implementing it in plain javascript.

I am using this reference  [Show or Hide Table column](https://htmldom.dev/show-or-hide-table-columns)

What is your opinion?

**Comment by tananaev** [comment]
I was thinking it can work similar to chart selection. With multi-select combobox.
