### ISSUE TITLE
GMAIL SMTP CONFIGURATION

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar-web#831]
Hi Anton,

is this confuration in traccar.xml or default.xml?

Gmail is one of the most popular free email services. To configure Gmail for notifications in Traccar follow steps below.

Assuming that you are using two factor authentication for your Google account, first you have to create an app password:

Go to your Google Account.
On the left navigation panel, choose Security.
On the "Signing in to Google" panel, choose App Passwords. If you don’t see this option check Google support page with more details.
At the bottom, choose Select app and choose Mail.
Choose Select device and choose Other. Enter "Traccar" as a name.
Choose Generate.
The App Password is the 16-character code in the yellow bar on your device. Copy it into the configuration below.
Choose Done.
Add following lines to the Traccar configuration file:
```xml
<entry key='mail.smtp.port'>587</entry>
<entry key='mail.smtp.starttls.enable'>true</entry>
<entry key='mail.smtp.host'>smtp.gmail.com</entry>
<entry key='mail.smtp.from'>YourAddress@gmail.com</entry>
<entry key='mail.smtp.auth'>true</entry>
<entry key='mail.smtp.username'>YourAddress@gmail.com</entry>
<entry key='mail.smtp.password'>YourPassword</entry>
```
You have to replace following items in the above configuration:

YourAddress@gmail.com - your Gmail address. It will be used as a sender address
YourPassword - App Password that we created in the first part. Don't include spaces
Note that recepient address is your Traccar user email address. Default "admin" is not a valid address, so if you are using default account, you need to update email address to be a valid one.

thanks for the info!

**Comment by tananaev** [comment]
For questions please use the forum. GitHub is not the right place to ask this.

**Comment by tananaev** [comment]
Also I don't see the reason for copy-pasting documentation. Why not just provide a link?

**Comment by tananaev** [comment]
Also, please don't use UPPER CASE letters in title.
