### ISSUE TITLE
[Modern] Geofence names are not visible on map when map is zoomed out

### ISSUE THREAD

**Issue by mikems66** [traccar/traccar-web#833]
**Describe the bug**
When map is zoomed out at lowest, geofence names are not visible on map.

**To Reproduce**
1. Create geofence (in old UI)
2. in modern UI open map
3. zoom out
4. only device positions are visible, but not geofences

**Expected behavior**
Geofence names should be visible regardless of zoom level.

**Comment by tananaev** [comment]
Can you please provide screenshots.

**Comment by mikems66** [comment]
![new ui zoomed in](https://user-images.githubusercontent.com/77976973/113861040-0c804e80-97a7-11eb-8fbc-d6e9f0fd04c1.jpg)
![new ui zoomed out - no geofence](https://user-images.githubusercontent.com/77976973/113861045-0db17b80-97a7-11eb-8443-f2fc6657bf1a.jpg)
![old ui zoomed out](https://user-images.githubusercontent.com/77976973/113861050-0ee2a880-97a7-11eb-9b85-89175f3d160c.jpg)

**Comment by mikems66** [comment]
![new ui zoomed in detail](https://user-images.githubusercontent.com/77976973/113862921-4fdbbc80-97a9-11eb-8bc4-37b293374983.jpg)

**Comment by tananaev** [comment]
Closing as no details provided.
