### ISSUE TITLE
Minor change in Replay Map Status Window

### ISSUE THREAD

**Issue by mail2bishnoi** [traccar/traccar-web#847]
Hi Anton,

Currently, when we click on the device icon in the replay screen, the current device detail shows in the status window. But my suggestion is that in the status window, what device details were there at the point you clicked on, should be shown.

For example, my truck went on a trip yesterday and its location was xyz and the speed was 60 km/hr (position id= 35) at 7:30 PM. Today when I check the history in the replay map and check the speed at 7:30 pm, the speed shows 0 km/hr because the current speed of the truck is 0 km/hr. With this, when I click on more details, the detail of the current position is shown (say position id = 235).

**Comment by tananaev** [comment]
I believe this is already fixed. We show relevant position info on click.
