### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by sky107** [traccar/traccar-web#850]
On running command npm run build .
It created build folder on deploying to static hosting websites its not creating proxy and hence apis not working 404 not found showing in network tab. Note I have updated .env file with my API path

**Comment by tananaev** [comment]
Proxy is only used for debugging. We don't use proxy in production. You would have to configure it yourself, if you need one.

**Comment by sky107** [comment]
> Proxy is only used for debugging. We don't use proxy in production. You would have to configure it yourself, if you need one.

how to configure ? static website hosts l does not provide option for setting proxy. Please respond

**Comment by tananaev** [comment]
For questions please use forum.
