### ISSUE TITLE
Unable to run npm start

### ISSUE THREAD

**Issue by sky107** [traccar/traccar-web#851]
![image](https://user-images.githubusercontent.com/69970001/118137845-4afece00-b423-11eb-8cc6-d754d2f2a532.png)
from couple of days ago unable to run npm start due to this error?

**Comment by dkyeremeh** [comment]
@sky107 I encountered this problem with a different app. I'm not sure if the solution applies here.

1. Delete all node modules
2. Ensure you are using node version 15 or higher (required by some traccar dependencies) 
3. Run npm install

Hopefully this helps

**Comment by manna018** [comment]
I have tried to run npm run build
The build completes but when I run the build. It just doesn't come up. 
The UI is blank

**Comment by tananaev** [comment]
What exactly are you trying to run?

**Comment by ARChilton** [comment]
I had to install @material-ui/core, @material-ui/icons and eslint-plugin-jsx-a11y to get the page to load

**Comment by tananaev** [comment]
You shouldn't need any additional dependencies.
