### ISSUE TITLE
GoogleGeolocationProvider return 404 not found error

### ISSUE THREAD

**Issue by ninioe** [traccar/traccar-web#853]
**Describe the bug**
Google Geolocation provider return an error

**To Reproduce**
1. Go to GeolocationProviderTest
2. Add the folowing test:
```java
    public void testLocationProviderGoogle() throws Exception {
        GoogleGeolocationProvider provider = new GoogleGeolocationProvider("Your KEY");

        Network network = new Network(CellTower.from(208, 1, 2, 1234567));

        provider.getLocation(network, new GeolocationProvider.LocationProviderCallback() {
            @Override
            public void onSuccess(double latitude, double longitude, double accuracy) {
                assertEquals(60.07254, latitude, 0.00001);
                assertEquals(30.30996, longitude, 0.00001);
            }

            @Override
            public void onFailure(Throwable e) {
                fail();
            }
        });

        Thread.sleep(Long.MAX_VALUE);
    }
```
3. Run the test
```
javax.ws.rs.NotFoundException: HTTP 404 Not Found
```

**Comment by tananaev** [comment]
And what do you get in the response from Google API?

**Comment by ninioe** [comment]
![image](https://user-images.githubusercontent.com/8347415/118533487-ced0f700-b750-11eb-9c5c-28d2ad9a5611.png)

**Comment by tananaev** [comment]
OK, so it seems like Google returned error 404. Is there a reason you posting it here as a bug?

**Comment by ninioe** [comment]
I am trying to get location from WIFI with Google Geolocation.
The Key is valid but it fails, so I made the test and it failed too.
I don't know what is the reason.

**Comment by tananaev** [comment]
You should contact Google about it. The error is clearly coming from them, as you can see.

**Comment by ninioe** [comment]
I just wanted to know if anyone else is getting this error?
maybe they made a change in the API?
are you getting a valid response from their API?

**Comment by tananaev** [comment]
If you just want to ask a question, this is the wrong place. Use the forum.

**Comment by ninioe** [comment]
what are the alternative services that can return locations based on WIFI and LBS?

**Comment by ninioe** [comment]
> If you just want to ask a question, this is the wrong place. Use the forum.

I thought it was a bug

**Comment by ninioe** [comment]
In the past I used Traccar platform with Google Geolocation Service and it was working great.
I hope this issue will be solved in the future.
For now I will have to try another service provider.
