### ISSUE TITLE
[modern] New layout for options and configurations

### ISSUE THREAD

**Issue by dkyeremeh** [traccar/traccar-web#856]
## Mockup
- [Desktop](https://www.figma.com/proto/FnEzXweO1PpXoBYSSAAXVP/Traccar-UI?node-id=189%3A225&scaling=contain&page-id=31%3A0) >= `lg`
- [Tablet](https://www.figma.com/proto/FnEzXweO1PpXoBYSSAAXVP/Traccar-UI?node-id=1632%3A1819&scaling=scale-down&page-id=743%3A1646) =  `sm` and `md`
- [Mobile](https://www.figma.com/proto/FnEzXweO1PpXoBYSSAAXVP/Traccar-UI?node-id=500%3A264&scaling=scale-down&page-id=500%3A0) = `xs`

## Requirements (General)
1. Create a master layout template to be used for all settings and options
5. Update all the pages referenced in the sidebar(navigational drawer) to use the new template
2. The active item on the navigational drawer (sidebar)should have a gray background as indicated
4. Mobile and Tablet should display the name of the active page on the Title/App Bar 
4. No need to implement the bottom navigation
5. No need to implement any changes to the content of the page

## Dimensions and styles
1. Get a free Figma account. You can use an existing account if you have one
1. View dimensions and styles by opening it in the editor as shown below <img width="1211" alt="Screenshot 2021-04-30 at 7 26 18 PM" src="https://user-images.githubusercontent.com/52928432/116744740-3c0f2900-a9ea-11eb-8553-3588d9200e43.png">
1. Click the inspect button and scroll down to see the dimensions
<img width="451" alt="Screenshot 2021-04-30 at 7 34 28 PM" src="https://user-images.githubusercontent.com/52928432/116745845-39610380-a9eb-11eb-9dac-43fa7b271f3e.png"> 
<img width="1211" alt="Screenshot 2021-04-30 at 7 25 51 PM" src="https://user-images.githubusercontent.com/52928432/116744758-429da080-a9ea-11eb-9936-f4712da4d045.png">

## Notes
Kindly enable comments to view notes on the designs. You can also ask questions in the comment section
Enable comment by clicking the comment icon as highlighted in the image below
<img width="1290" alt="Screenshot 2021-04-30 at 7 30 46 PM" src="https://user-images.githubusercontent.com/52928432/116745486-acb64580-a9ea-11eb-94f4-c09f5825daee.png">

**Comment by tananaev** [comment]
Looks awesome. Really appreciate all these design contributions.

A couple of small comments that might not be related to this specific ticket, but just don't want us to miss it:

- When you click on a device on the map, we need to show small popup first. I see in some cases you show a full screen view. Not sure if it's final or not.
- We want to avoid making assumptions that Traccar is only used for vehicle tracking. It's a big market, but it can be used anywhere. One example - you have a vehicle icon next to devices. Maybe we can remove it or replace with something more generic.
- Last one is more of a question. Where do you get those icons? Where can we download them and what's the license?

**Comment by dkyeremeh** [comment]
Responding orderly
1. I've updated how the map screen works. I've created a separate ticket for it
2. I really thought long and hard concerning the icon to use, but nothing came to mind. You can recommend something though
3. I'm using material icons [@material-ui/icons](https://www.npmjs.com/package/@material-ui/icons). The only exception is the ignition icon which is a combination of 2 icons. But that can be directly downloaded from the figma page

**Comment by tananaev** [comment]
2. Could be some generic icon, like a circle, square or something. Alternatively we can also use satellite or antenna.

**Comment by dkyeremeh** [comment]
@tananaev @mail2bishnoi Will be working on this

**Comment by tananaev** [comment]
Awesome.

By the way, just a couple of days ago I added a geofence editing screen. We probably need to think how it works in the new design system. It looks very similar to main screen because it requires map. lmk what you think.

**Comment by dkyeremeh** [comment]
Will take a look at it and determine how best to integrate it

**Comment by dkyeremeh** [comment]
@tananaev I've managed to integrated the GeofencePage and the editing screen with the other options. I'll be designing a mockup for the GeofencePage soon to allow better integration. I'll attach screenshots to the PR

**Comment by dkyeremeh** [comment]
@tananaev I'll need some clarification concerning the geofencing. I'm seeing a number of files related to the geofencing. I w

**Comment by tananaev** [comment]
@dkyeremeh sure, do you have any specific questions?

**Comment by dkyeremeh** [comment]
I've figured it out. I typed the message yesterday but didn't send it. Sent it today by mistake
