### ISSUE TITLE
[modern] Map Screen Device List

### ISSUE THREAD

**Issue by dkyeremeh** [traccar/traccar-web#857]
## Mockup
- [Desktop](https://www.figma.com/proto/FnEzXweO1PpXoBYSSAAXVP/Traccar-UI?node-id=56%3A0&scaling=contain&page-id=31%3A0) >= `lg`
- [Tablet](https://www.figma.com/proto/FnEzXweO1PpXoBYSSAAXVP/Traccar-UI?node-id=863%3A1651&scaling=scale-down&page-id=743%3A1646) =  `sm` and `md`
- [Mobile](https://www.figma.com/proto/FnEzXweO1PpXoBYSSAAXVP/Traccar-UI?node-id=500%3A1&scaling=scale-down&page-id=500%3A0) = `xs`
**Note:** Mockups are interactive.

## Requirements (General)
1. Create a sidebar an move the device list into it
3. Update the device list to conform to the new design
4. Implement the design of the search bar, but do not add any functionality
3. Do not implement the bottom navigation
1. Do not remove the Title/App bar from the map screen: it will be removed when the bottom navigation is implemented
4. **Note:** The device list should slide out when it collapses; and slide in when it is being shown

### Desktop
1. The sidebar should show by default when the map screen is opened
2. When the user clicks the x button on the search bar, the sidebar should collapse/hide. Try it in the mockup
3. When the sidebar collapses, the devices toggle button (<img width="140" alt="Screenshot 2021-05-29 at 1 58 51 AM" src="https://user-images.githubusercontent.com/52928432/120054760-6d970680-c021-11eb-8f4c-9476595a0146.png">) should show.
4. Clicking the devices toggle button should show the sidebar once again

### Tablet and Mobile
1. The device list should be hidden when the map screen is opened
2. When the user clicks the devices toggle button, the device list should open as a modal filling the entire screen
3. Clicking the arrow button next to the search bar should close the modal

### Icons, text and indicators
1. Battery percentage less than 30 should be  colored with red
2. Battery percentage above 70 should be green
3. Anything between 31 - 69% should be grey

## Dimensions and styles
1. Get a free Figma account. You can use an existing account if you have one
1. View dimensions and styles by opening it in the editor as shown below <img width="1211" alt="Screenshot 2021-04-30 at 7 26 18 PM" src="https://user-images.githubusercontent.com/52928432/116744740-3c0f2900-a9ea-11eb-8553-3588d9200e43.png">
1. Click the inspect button and scroll down to see the dimensions
<img width="451" alt="Screenshot 2021-04-30 at 7 34 28 PM" src="https://user-images.githubusercontent.com/52928432/116745845-39610380-a9eb-11eb-9dac-43fa7b271f3e.png"> 
<img width="1211" alt="Screenshot 2021-04-30 at 7 25 51 PM" src="https://user-images.githubusercontent.com/52928432/116744758-429da080-a9ea-11eb-9936-f4712da4d045.png">

## Notes
Kindly enable comments to view notes on the designs. You can also ask questions in the comment section
Enable comment by clicking the comment icon as highlighted in the image below
<img width="1290" alt="Screenshot 2021-04-30 at 7 30 46 PM" src="https://user-images.githubusercontent.com/52928432/116745486-acb64580-a9ea-11eb-94f4-c09f5825daee.png">

**Comment by mail2bishnoi** [comment]
Hi @tananaev @dkyeremeh 

I am starting working on this issue. 

Thanks.

**Comment by dkyeremeh** [comment]
@tananaev @mail2bishnoi 

If getting good icons is the limitation, then that shouldn't be an issue. There's a royalty-free svg icon website I use to use. It's been a while, but I can find it

**Comment by mail2bishnoi** [comment]
Hi @dkyeremeh @tananaev 

For some devices, there is no position data available. In that case, what should I show for Ignition and battery status?

**Comment by dkyeremeh** [comment]
@mail2bishnoi You don't need to show anything that is not present

**Comment by tananaev** [comment]
Correct. Don't show anything. Also, even if position is present, it doesn't mean either of those values is available.

**Comment by tananaev** [comment]
This is already implemented.
