### ISSUE TITLE
[modern] Device quick menu

### ISSUE THREAD

**Issue by dkyeremeh** [traccar/traccar-web#859]
## Requirements
- Update the quick menu which shows up when a device icon is clicked on the map
- Battery percentage should be color coded
  - <= 30% => red
  - 31% - 69% => gray
  - \> 71% => green
- Status should be color coded
  - Offline => red
  - online => green
  - unkonwn => default color

## How it works
1. The quick menu shows up below a device icon when the icon is clicked on the map. 
1. When a user clicks an item inside the devices list,  the  icon of that device should be centered on the map (current behavior). The quick menu should show up below the icon just as point 1.

### Mobile & Tablet
- When a device is clicked on the device list (mobile & tablet), the device list collapses. The quick menu shows just like point 2 above. 

- [Mockup](https://www.figma.com/file/FnEzXweO1PpXoBYSSAAXVP/Traccar-UI?node-id=189%3A183)
<img width="439" alt="Screenshot 2021-06-07 at 1 39 34 AM" src="https://user-images.githubusercontent.com/52928432/120948208-403d0d80-c731-11eb-91b7-333d27563d9a.png">

## Dimensions and styles
1. Get a free Figma account. You can use an existing account if you have one
1. View dimensions and styles by opening it in the editor as shown below <img width="1211" alt="Screenshot 2021-04-30 at 7 26 18 PM" src="https://user-images.githubusercontent.com/52928432/116744740-3c0f2900-a9ea-11eb-8553-3588d9200e43.png">
1. Click the inspect button and scroll down to see the dimensions
<img width="451" alt="Screenshot 2021-04-30 at 7 34 28 PM" src="https://user-images.githubusercontent.com/52928432/116745845-39610380-a9eb-11eb-9dac-43fa7b271f3e.png"> 
<img width="1211" alt="Screenshot 2021-04-30 at 7 25 51 PM" src="https://user-images.githubusercontent.com/52928432/116744758-429da080-a9ea-11eb-9936-f4712da4d045.png">

**Comment by mail2bishnoi** [comment]
Hi @tananaev @dkyeremeh 

I am picking this one.

**Comment by tananaev** [comment]
Sounds good 👍

**Comment by dkyeremeh** [comment]
@mail2bishnoi I just noticed that I didn't add the requirement for the behavior so I'm doing it now

**Comment by tananaev** [comment]
Implemented.
