### ISSUE TITLE
Zoom level of geofence editing window inadequate

### ISSUE THREAD

**Issue by sboldt1978** [traccar/traccar-web#862]
According to https://www.traccar.org/forums/topic/editing-geofences-zoom-level/#post-62854 the zoom level of the geofence editing map window seems to have a bug:

When adding a new geofence the map windows shows the area around the selected device. But editing an exisiting geofence is quite harder, because the map window opens in minimum zoom level, showing the whole earth, even though it is quite clear where the area is located that I'm interested in. 

Can be reproduced by opening the geofence window, then edit a random existing geofence, then click the map icon.

**Comment by tananaev** [comment]
Fixed, thanks for reporting the issue.
