### ISSUE TITLE
[modern] WebUI -> User -> Attributes -> UI features: does not work

### ISSUE THREAD

**Issue by glbatistabh** [traccar/traccar-web#863]
Attributes setting for a given User, referring to "Interface UI" are not working in the new modern interface.

`traccar version: "4.12"
`

```
attributes: {ui.disableDrivers: true, ui.disableComputedAttributes: true, ui.disableCalendars: true,…}
ui.disableCalendars: true
ui.disableComputedAttributes: true
ui.disableDrivers: true
ui.disableMaintenance: true
```

![image](https://user-images.githubusercontent.com/8257020/122479890-37a2cd80-cfa2-11eb-84fa-3c4a1db89314.png)
👆👆  **FILE: http://My-IP/api/server:** Note in the image, that the left menu is complete even with the "ui.disable{any}" attributes enabled

![image](https://user-images.githubusercontent.com/8257020/122479992-6751d580-cfa2-11eb-8b78-7f8a7e219dd8.png)
👆👆  **FILE: http://MY-IP/api/session:** Note in the image, that the left menu is complete even with the "ui.disable{any}" attributes enabled

**Comment by tananaev** [comment]
Please don't file bugs against modern interface. It is still in active development and a lot of things are not implemented.

**Comment by glbatistabh** [comment]
@tananaev  Sorry! 

Is there a prediction when permission rules will be implemented in the modern interface?

I ask why disabling everything for a given user and allowing only the vehicle view, is something quite common. And this part does not implement in menu, prevents this action.

**Comment by tananaev** [comment]
Can't provide any timeline, but you are welcome to contribute.
