### ISSUE TITLE
Direction indication on the map

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar-web#864]
@dkyeremeh do you have any ideas on how to show direction in the modern app.

In the old app we can a little arrow off the circle side like this:

<img width="86" alt="Screen Shot 2021-06-23 at 10 45 04 AM" src="https://user-images.githubusercontent.com/1161863/123144025-131a7b80-d410-11eb-90c9-fa3ef24c40b1.png">

Modern version is currently just a circle:

<img width="113" alt="Screen Shot 2021-06-23 at 10 45 34 AM" src="https://user-images.githubusercontent.com/1161863/123144084-24fc1e80-d410-11eb-97a7-925ca2bf9465.png">

I guess one option is to hide into the popup dialog and show direction there instead.

**Comment by dkyeremeh** [comment]
@tananaev I think we can rotate the icon to point in the direction of the device motion. We will have to change the default marker to avoid confusion

**Comment by mail2bishnoi** [comment]
Hi @tananaev @dkyeremeh 

I have a thought in my mind since I am using Traccar, We can use small vehicle icons like in Uber app.

**Comment by tananaev** [comment]
It's hard to find good assets for those kind of icons.

**Comment by dkyeremeh** [comment]
@tananaev @mail2bishnoi

If getting good icons is the limitation, then that shouldn't be an issue. There's a royalty-free svg icon website I use to use. It's been a while, but I can find it

**Comment by tananaev** [comment]
Feel free, but I don't think it's that easy to find a set of all the icons that we need. That are also in a Uber like style.

**Comment by jonathandreyer** [comment]
Hi everyone,

And what do you think about a dark (or other darker colour) line with a dot (or triangle) around the current modern? Something like: 
![Icon_idea](https://user-images.githubusercontent.com/4079443/123549369-07f58180-d769-11eb-88eb-59db1a2199b4.png)

With this idea, the default icon can be replaced others (car, plane, etc) without any issue.

**Comment by tananaev** [comment]
Looks pretty good, but maybe a bit too small.

**Comment by jonathandreyer** [comment]
Yes, you are right. The dot/triangle/marker can be expended, but the initial idea is to be as discreet as possible.

**Comment by dkyeremeh** [comment]
This is the website for high quality svg icons: https://freesvg.org. They have thousands of svgs to choose from

**Comment by mail2bishnoi** [comment]
Hi @dkyeremeh,

As @tananaev said, the problem with free SVG icons is that finding all the icons of the same style is very hard. I tried but couldn't get all the icons.

If we can hire a designer for icon designing, I can contribute a few dollars.

**Comment by dkyeremeh** [comment]
Understood. I can work towards an iconset in the long term. But in the short term, I think we have a number of options
1. Use the old indicator
2. Use the new indicator which is rotated to point in the direction of motion
3. Use the indicator designed by @jonathandreyer

Any of them works for me. So what do you guys think?

**Comment by tananaev** [comment]
I'd say short terms we can leave it as is and add direction info to the popup screen.

**Comment by jonathandreyer** [comment]
> I'd say short terms we can leave it as is and add direction info to the popup screen.

That seems a good idea. I can try to implement the indicator that I have explained before. Unfortunately, I have no skill in front-end, but I can try when I have little time.

**Comment by jonathandreyer** [comment]
> > I'd say short terms we can leave it as is and add direction info to the popup screen.
> 
> That seems a good idea. I can try to implement the indicator that I have explained before. Unfortunately, I have no skill in front-end, but I can try when I have little time.

Hi @tananaev, is it OK for you if I try to work on the idea of indication of direction by a dot/triangle/marker? I have already investigated a bit, but without implementation.

**Comment by tananaev** [comment]
Sure. Please make sure to test performance of your solution.

**Comment by jonathandreyer** [comment]
Sure, but I will see if I can have something that work.

**Comment by jonathandreyer** [comment]
Hi @tananaev, Hi everyone,
I have analysed the documentation and I did a few tests. Unfortunately, it is not possible to create a marker (or symbol) with two elements (one fix and another which rotate). One solution (see on the internet) would be to deactivate the cluster feature, but that seems a bad idea.
Maybe an alternative would be to combine two icons (dynamically during the runtime) or during the initialization with the correct rotation. But this solution requires to create an icon for every angle (or each device with angle). Probably this solution would impact the performance.
What is your feeling about this idea?

**Comment by tananaev** [comment]
How deactivating cluster would help?

One way to implement it is add a layer with arrow only. Icons can be pre-created programmatically at initialization stage. We don't need a lot of them. Probably 20-30 angles should be enough.

**Comment by jonathandreyer** [comment]
@tananaev I think that we can consider this issue as resolve, right?

**Comment by tananaev** [comment]
Yes, direction is supported.
