### ISSUE TITLE
internet explorer 11 not working

### ISSUE THREAD

**Issue by truebest** [traccar/traccar-web#866]
After getting the latest sources from traccar-web, Internet Explorer not working

The trouble in last version olVersion and usage olLayerSwitcherVersion, i use local copy of original libs (local / remote libraries - no difference):
```
   extjsVersion = '6.2.0';
   olVersion = '6.5.0';
   olLayerSwitcherVersion = '3.8.3';
   proj4jsVersion = '2.6.0';
   fontAwesomeVersion = '4.7.0';

addStyleFile('ajax/libs/ol3/' + olVersion + '/ol.css');
addScriptFile('ajax/libs/ol3/' + olVersion + '/ol.js');
addStyleFile('ajax/libs/ol-layerswitcher/' + olLayerSwitcherVersion + '/ol-layerswitcher.css');
addScriptFile('ajax/libs/ol-layerswitcher/' + olLayerSwitcherVersion + '/ol-layerswitcher.js');
```
after upgrade olVersion and olLayerSwitcherVersion, IE not working
![image](https://user-images.githubusercontent.com/12430603/123337082-6515eb00-d54f-11eb-8c71-e03b97a8e649.png)

When i returned to olVersion = '6.1.1'; not solve the problem.

I got:
![image](https://user-images.githubusercontent.com/12430603/123338897-3e0ce880-d552-11eb-993d-1b0589dddc42.png)

Some simular trobles i have on visit demo.traccar.org:
![image](https://user-images.githubusercontent.com/12430603/123338243-28e38a00-d551-11eb-957d-06581c990ee1.png)

Google Chrome working perfectly!

Please fix it, i don't understand deeply in web tech.

**Comment by tananaev** [comment]
What version of IE are you using? I thought it's not supported anymore.

**Comment by truebest** [comment]
I use win10 preinstalled internet explorer 11.
My previous set, which worked great:
    extjsVersion = '6.2.0';
    olVersion = '6.1.1';
    proj4jsVersion = '2.6.0';
    fontAwesomeVersion = '4.7.0';

after add olLayerSwitcherVersion, IE11 stopped working correctly.

**Comment by tananaev** [comment]
Internet Explorer has about a year of support left from Microsoft. Not sure if it's a good investment of our time to fix it. You can probably continue using older version of the app for now.

**Comment by tananaev** [comment]
Closing as IE is no longer a relevant browser. Almost everyone dropped support for it.
