### ISSUE TITLE
Save per-user UI preferences for columns

### ISSUE THREAD

**Issue by soshial** [traccar/traccar-web#867]
In the old UI:
![image](https://user-images.githubusercontent.com/100644/123054767-42cc8200-d416-11eb-8823-f10227fa3ceb.png)

In the new UI:
![image](https://user-images.githubusercontent.com/100644/123522107-4db03c80-d6cc-11eb-85f7-0c8020861836.png)

**Comment by tananaev** [comment]
Already implemented.
