### ISSUE TITLE
[modern] Simplify development inside docker container

### ISSUE THREAD

**Issue by jonathandreyer** [traccar/traccar-web#877]
**Is your feature request related to a problem? Please describe.**
To simplify & reduce the necessary of npm (& dependencies) for UI developer, I have created a simple docker (& docker-compose) solution to develop inside docker container. That allows developers to edit files without installing all node dependencies, only Docker with Docker-Compose are necessary. It is inspired by this medium [article](https://medium.com/bb-tutorials-and-thoughts/react-local-development-with-docker-compose-5a247710f997) with few modifications.
That launch one docker container with the modern UI and another container with traccar application (as backend). All API requests are automatically forwarded to the backend.
If you are interested, I can create a PR.

**Describe the solution you'd like**
N/A (Solution already developed)

**Describe alternatives you've considered**
N/A

**Additional context**
The current branch is available [here](https://github.com/jonathandreyer/traccar-web/tree/docker).

**Comment by tananaev** [comment]
Doesn't seem like there's a lot of interest in this, so I think we can close this for now. I personally prefer NPM.

**Comment by jonathandreyer** [comment]
Hi @tananaev, it is OK for me. From my side, I prefer to use this docker alternative for the development, but I fully understand if you prefer to use NPM.
