### ISSUE TITLE
Home screen issues

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar-web#878]
1. Top and bottom padding cuts list items.

<img width="671" alt="Screen Shot 2021-07-21 at 11 29 37 PM" src="https://user-images.githubusercontent.com/1161863/126599065-ebacacfd-4a80-499a-b4ad-394c3b90545e.png">

2. Large virtual list doesn't work well with map background.

https://user-images.githubusercontent.com/1161863/126598976-a513ce8c-d298-4fcd-ba48-2b15c1c6142e.mp4

^ download video file if it doesn't play directly in GitHub

For the second issue should we just have white background? @dkyeremeh what do you think?

There's also a problem that map doesn't center properly. It should center in the visible only, which means that we need to apply map padding.

cc @mail2bishnoi

**Comment by dkyeremeh** [comment]
I'll create a PR for issue 1.

I was expecting issue 2 to come up. We'll be using a SectionList or infinite scroll to increase the performance.

**Comment by dkyeremeh** [comment]
@tananaev can we close this issue?

**Comment by tananaev** [comment]
Yes, thanks for fixing it.
