### ISSUE TITLE
Report: Default to all devices and today

### ISSUE THREAD

**Issue by psyciknz** [traccar/traccar-web#880]
**Is your feature request related to a problem? Please describe.**
Just after a simple (hopefully) UI update, to allowing the  Show button to work with defaults upon first selecting the reports panel.

Rather than forcing the users at the minimum to choose a device and a date.

**Describe the solution you'd like**

I'd have thought easiest was just to allow nothing, which is the default selected when you enter the panel, to default to all devices and the default date of the current date.

**Describe alternatives you've considered**

**Additional context**

**Comment by tananaev** [comment]
I don't think it's currently possible with the modern app because we don't allow multiple devices for some reports.
