### ISSUE TITLE
[Modern] Devices List and Dialogs in the modern interface

### ISSUE THREAD

**Issue by hieund612** [traccar/traccar-web#881]
Hi Anton and everyone, I have some questions (and feature requests) about the modern interface.

1. I saw the new Devices List in the latest commit from @mail2bishnoi and @dkyeremeh. Would you have the intention of including the editing and the deleting button from the old devices list in the future? I tried to add the button but it didn't work.

2. I read @dkyeremeh's design back in April, which includes the device status colors in the devices list. If you like to implement this, I would create a pull request as soon as possible.

![Main Page](https://user-images.githubusercontent.com/75609123/126733973-32151499-aadb-4523-8aad-3a460bd5c029.png)

3. Anton, I heard you would migrate all the current features to the modern interface. Do you have plans to remake the current "pages" (like the pages from notifications and settings menus) to the dialogs like the old interface? I think it would allow us to follow the tracking session uninterruptedly.

Thank you.

**Comment by tananaev** [comment]
1. That functionality will be added back soon, of course.
2. Feel free to send a pull request. @dkyeremeh please share latest design if there were any changes.
3. No. You can always just open new window/tab for settings.

**Comment by hieund612** [comment]
Thank you for your quick response Anton.

**Comment by dkyeremeh** [comment]
@hieund612

1. This is in progress.
2. It's been done in the device list PR. The colors being used are a little different though. We're now using gray to indicate `unknown` status.

**Comment by dkyeremeh** [comment]
@hieund612 concerning the colors, I changed the design because the bright colors made the icons more prominent than it was supposed to be after I added the indicator icons to the design.

I think I can do a design with the colors being less distracting. 

It also looks like we can use the icons belonging to the various categories as well. @tananaev what do you think?

**Comment by tananaev** [comment]
@dkyeremeh can you please link designs here once you have them.

**Comment by dkyeremeh** [comment]
I will

**Comment by hieund612** [comment]
Thank you @dkyeremeh for your prompt response.

**Comment by tananaev** [comment]
This is already implemented.
