### ISSUE TITLE
[Modern] Update bottom navigation and add it to relevant pages

### ISSUE THREAD

**Issue by dkyeremeh** [traccar/traccar-web#886]
## Mockup
[Tablet](https://www.figma.com/proto/FnEzXweO1PpXoBYSSAAXVP/Traccar-UI?node-id=1163%3A0&scaling=scale-down&page-id=743%3A1646&starting-point-node-id=743%3A1694)
[Mobile](https://www.figma.com/proto/FnEzXweO1PpXoBYSSAAXVP/Traccar-UI?node-id=500%3A1&scaling=scale-down&page-id=500%3A0&starting-point-node-id=743%3A1641)

## Requirements
Note: The bottom navigation will be visible only on Tablet and Mobile

### Adding bottom nav to pages
- Add bottom navigation to the settings/options template
- Add bottom navigation to the reports template
- Add the replay icon to the map screen right below the devices list (Mobile And Tablet)

### Updates to bottom nav
- Highlight the nav item related to the current page
- Change the options/settings icon to `@material-ui/icons/Handyman`

**Comment by tananaev** [comment]
This is already implemented.
