### ISSUE TITLE
The alignments of the buttons are not correct

### ISSUE THREAD

**Issue by rbiswal77** [traccar/traccar-web#887]
**Describe the bug**
In reports section, click on any reports. The buttons seems to be out of place on the left hand side.
**To Reproduce**
1. Go to 'Menu'
2. Click on 'Reports->Route'
3. Check the Show,export and email report buttons. 

**Expected behavior**
The whole group of buttons is not inside/outside the div that contains device and period.

**Screenshots**
![traccar_bug1](https://user-images.githubusercontent.com/26700878/127961351-0d2d89b1-d3cc-47af-b062-fa1351c0bd82.png)

**Additional context**
This problem is there in all the reports.

**Comment by tananaev** [comment]
It's already fixed.

**Comment by rbiswal77** [comment]
When it was fixed. Why I don't see it. This package was installed 2 days back only.

**Comment by tananaev** [comment]
Are you building from master?

**Comment by rbiswal77** [comment]
We downloaded and self hosted. Didn't build from master
