### ISSUE TITLE
[Modern] About the Status View in the latest commit

### ISSUE THREAD

**Issue by hieund612** [traccar/traccar-web#890]
Hi Anton and everyone, I have some question about the latest commit.

I see that @mail2bishnoi has created a new quick device menu / status view, which included the new device deleting button.

However, when I try this, the device is still there and I have to refresh the web page for it to disappear. Is there a solution to delete the device like the original deleting button (which made the device icons on the devices list and the map disappear immediately?)

**Comment by tananaev** [comment]
Sounds like a bug that needs to be fixed.

**Comment by tananaev** [comment]
Already fixed.
