### ISSUE TITLE
[modern] websocket keeps connected after logout

### ISSUE THREAD

**Issue by mishika92** [traccar/traccar-web#896]
**Describe the bug**
When we press "Logout" we kill the session and go to the login screen, but the websocket connection stays alive.

**To Reproduce**
1. login with an account A
2. logout
3. if you go to developer tools > network you will see the socket still open and receiving messages (if any)
4. login with a different account B that doesn't have the devices from account A. If the devices from A are sending positions, you will see the devices from account A appearing in account B

**Expected behavior**
When modern app logs out it should kill the websocket.

**Screenshots**
![image](https://user-images.githubusercontent.com/89601564/131009165-c808e02b-0b19-486b-8df7-950d7120c187.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 92, Firefox 91

**Smartphone (please complete the following information):**

**Additional context**
The web app should close its websocket. But shouldn't the /api/socket endpoint in the server kill the corresponding connection after DELETE /api/session is called?

**Comment by tananaev** [comment]
The issue is fixed.
