### ISSUE TITLE
Back button on Geofence page in modern UI exits to legacy UI.

### ISSUE THREAD

**Issue by pc500** [traccar/traccar-web#897]
If you click the left arrow "back" as highlighted in this screenshot on the modern UI of 4.14, it exits to the legacy UI. I believe the intent would be to stay in the modern UI and return to the main modern map page.

To reproduce:

1) Load Geofences page via settings or navigate to it via a method of your choice. (":8082/modern/#/geofences")
2) Click this back button:
![image](https://user-images.githubusercontent.com/33823824/131266467-8baa24dd-8407-4c09-ac4f-9debc7a79fe3.png)

**Comment by tananaev** [comment]
Fixed, thank you.
