### ISSUE TITLE
[Modern] Feat: Track a Device (Live Route)

### ISSUE THREAD

**Issue by DoM1niC** [traccar/traccar-web#899]
#### like in the old Frontend called Live Route

![image](https://user-images.githubusercontent.com/1436958/132968197-50b604a9-3f06-47bb-a8b1-8ee9cc639314.png)

**Comment by tananaev** [comment]
Please don't report missing features in the modern app. It's still in active development and we are aware that some features are still missing. Once it's out of preview state, you can start reporting feature requests for it.
