### ISSUE TITLE
About Integration with OpenGTS

### ISSUE THREAD

**Issue by romaar** [traccar/traccar-web#90]
Hello
1.  How it work, how much protocol can use for gps ???? 
2.  Will be  use protocols from the traccar or will be use protocols from the OpenGTS ?????
   I think into Traccar the protocols is more  then in Open GTS. Am I right or not ????
3.  What database mysql using need new database or old database ?????
4.  What software from OpenGTS need install for integration with Traccar :  track.war,    events.war,    Database Administration,   OpenDMTP, TK10x, and Aspicore DCS Modules  ???????
5.  You can write please more details about how I can integrate with OpenGTS.
6.  What advantage if will integrate with OpenGTS from your point of view  ????

**Comment by kirantpatil** [comment]
I have following questions to clarify.

What features makes OpenGTS to integrate with Traccar ?

Why they are not supported in Traccar ?

What new features are in pipeline ?

Any pointer to understand both projects differences and common features in detail ?

Please help me to understand and know traccar better.

Thanks.

**Comment by tananaev** [comment]
@kirantpatil, please don't comment on 3 year old closed thread. Also, if you have questions about Traccar, you should be asking in different issue tracker:

https://github.com/tananaev/traccar/issues

**Comment by kirantpatil** [comment]
Yes Sir, I thought about it but felt to comment the existing thread.
