### ISSUE TITLE
[Modern] Local testing and NPM dependencies

### ISSUE THREAD

**Issue by ivan-avalos** [traccar/traccar-web#901]
**Describe the bug**
So, I'm trying to change the backend URL according to the instructions on `README.md`, but it keeps trying to connect `localhost:300/api` rather than the URL specified in `REACT_APP_URL_NAME` in `.env.local`.

I also noticed NPM dependencies are a bit old, so I had to run `npm install` with the `--legacy-peer-deps` flag. There are 11 moderate and 2 high severity security issues. Maybe this should be a separate issue.

**To Reproduce**
1. Run `npm install --legacy-peer-deps` on `modern/` subfolder.
2. Run `cp .env .en.local` and set `REACT_APP_URL_NAME` to backend URL.
3. Run `npm start` and open development tools to see the console logs.

**Expected behavior**
The UI should connect to the backend URL set on the environment variable.

**Comment by tananaev** [comment]
Where do you see connections to `localhost:3000/api`?

**Comment by ivan-avalos** [comment]
Console logs. I see multiple 404 errors in logs. It never seems to try to connect to the backend URL set in the environment variable.

I already decided not to use the modern interface for my clients, for the moment, since it lacks some features I consider important. But I'm willing to test further.

**Comment by tananaev** [comment]
You mean browser console? I think there's a bit of misunderstanding. This variable is for proxy configuration:

https://github.com/traccar/traccar-web/blob/master/modern/src/setupProxy.js

Your browser will still connect to `localhost:3000`.

**Comment by ivan-avalos** [comment]
You might want to clarify that on the README, so other people don't get confused. What is a proxy in this context, anyway? Would it proxy `localhost:3000` requests to the backend URL or something?

**Comment by tananaev** [comment]
Feel free to send a pull request.
