### ISSUE TITLE
Clustering Devices - Modern Interface

### ISSUE THREAD

**Issue by camende** [traccar/traccar-web#902]
Dears,

Apologies  for posting in the wrong repository.

Per question on the forum, it would be useful for our usage if there is a possibility to switch off the clustering of devices.
This is mainly because of a high concentration of devices in a small area.

**Comment by AlyRadwan2020** [comment]
You can cluster Devices using groupId.

**Comment by tananaev** [comment]
Can you elaborate? Why would you want to cluster devices by group?

**Comment by AlyRadwan2020** [comment]
If you have a lot of devices you can't remember who is this, so you need to group them according to their assigned groups

**Comment by tananaev** [comment]
How is that related to clustering? We already have filtering by groups that let you do what you seem to be asking for.

**Comment by tananaev** [comment]
We already have an option to turn off clustering.
