### ISSUE TITLE
[Modern] Markers don't display at all on Firefox 88-92

### ISSUE THREAD

**Issue by lultimouomo** [traccar/traccar-web#903]
**Describe the bug**
Markers don't show up at all in the map canvas

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox 
 - Version 88-92

**Smartphone (please complete the following information):**
 - Device: Xiaomi A2 Lite
 - OS: 10
 - Browser Firefox
 - Version 92

**Additional context**
The modern interface on the same traccar instance works correctly on Chromium 93.

In Firefox desktop the console shows `Uncaught (in promise) DOMException: CanvasRenderingContext2D.drawImage: Passed-in canvas is empty`

![image](https://user-images.githubusercontent.com/109914/135421872-cf716895-f157-453f-a044-2d93e1aa7b2b.png)

**Comment by tananaev** [comment]
Are you using latest version from master?

**Comment by lultimouomo** [comment]
No, I am using the current released version of traccar, 4.14

**Comment by tananaev** [comment]
This issue has already been fixed.
