### ISSUE TITLE
Bug on back arrow icon in Modern Web

### ISSUE THREAD

**Issue by nimamgs** [traccar/traccar-web#904]
**Describe the bug**
in Modern Type of WEB, when you go to Setting section, and then when you click on the Up-Left sise Back Arrow Icon, you move back to the Traditional WEB layout!!

**To Reproduce**
1. Go to 'Modern WEB Page'
2. For example click on "+" sign to add new Device, you will go to Setting section
3. Click on Back Arrow Icon on the Left Up side
4. See error: You will go to the traditional Layout

**Comment by tananaev** [comment]
This is already fixed. Thanks for reporting.
