### ISSUE TITLE
[modern] Duplication of geofences

### ISSUE THREAD

**Issue by Vladghan** [traccar/traccar-web#907]
When adding several geofences in a row, each next geofence is duplicated in an arithmetic progression

**Comment by tananaev** [comment]
Can you provide a screen recording or something to show the problem?

**Comment by Vladghan** [comment]
> Can you provide a screen recording or something to show the problem?

After firts drawing:
![image](https://user-images.githubusercontent.com/74247566/144209616-42d66eaa-1f36-46a4-bef9-d92f07d985f9.png)

After second drawing:
![image](https://user-images.githubusercontent.com/74247566/144210012-3d02973e-9a90-49f0-abba-05740c4e62c1.png)

After third drawing:
![image](https://user-images.githubusercontent.com/74247566/144210409-c537bda8-b6e5-4ce6-89eb-9c34c2d3cc05.png)

etc

I think dublication occurs when opening page /geofence/{id}. But I don't understand a reason

**Comment by tananaev** [comment]
Looks like I can reproduce it. Thanks.

**Comment by tananaev** [comment]
Already fixed.
