### ISSUE TITLE
[modern]StatusView favorite switch option

### ISSUE THREAD

**Issue by onethings** [traccar/traccar-web#909]
Please add statusview favorite display switch option
Due to each user or admin care different device status, please add this kind of option. Thanks.
I just screen shot and draw on picture.
![map-statusview](https://user-images.githubusercontent.com/18694038/147365542-4547cff8-3ca8-4180-80b1-ba6a99902180.png)

**Comment by tananaev** [comment]
We already implemented something similar. You can select attributes in preferences.
