### ISSUE TITLE
Map Error when navigating back to main screen from other screens

### ISSUE THREAD

**Issue by mail2bishnoi** [traccar/traccar-web#910]
I am getting "TypeError: Cannot read properties of undefined (reading 'setData')" error while navigating back to the main screen from the settings screen.

Steps to reproduce
step1. Login into the modern application.
step2. Click on the Settings option in the bottom menu.
step3. On the Settings page, click on the back arrow button.

![image](https://user-images.githubusercontent.com/41992346/147844030-10cadd21-876d-41ab-b51e-212854a63ffb.png)

Note: This error does not occur every time. 

![map_error1](https://user-images.githubusercontent.com/41992346/147844257-87a1b5c6-13e5-46e7-9f83-d2856b5cc6ae.gif)

**Comment by tananaev** [comment]
Are you using master branch?

**Comment by mail2bishnoi** [comment]
Yes.

**Comment by mail2bishnoi** [comment]
Any comment/update on this?

**Comment by tananaev** [comment]
Not really. Haven't had any time to look into it. If you manage to figure out, please send a PR.

**Comment by tananaev** [comment]
Finally found time to fix this properly.
