### ISSUE TITLE
Websocket in simple app.js

### ISSUE THREAD

**Issue by gaiththewolf** [traccar/traccar-web#913]
**Describe the bug**
I tried to run the simple on my traccar server but after session creation the get device prompt a popup for authentication like in pictures

**Expected behavior**
I guess the session not saved in the browser because with postman everything works fine

**Screenshots**
![popup](https://user-images.githubusercontent.com/4011175/150968132-d4e05514-310c-46ac-a014-ba732fe92180.png)
![session](https://user-images.githubusercontent.com/4011175/150968134-85dee15d-badb-4ad5-9859-84faacb55197.png)
![devices](https://user-images.githubusercontent.com/4011175/150968127-e3d72ed0-a799-468a-b4ac-aed333bf0f9f.png)

**Desktop:**

 - Traccar OS: windows server 2016
 - Browser : Chrome
 - Version : 97.0.4692.99 (Build officiel) (64 bits)

**Additional context**
i'm trying to execute this simple at first, because i tried many approaches in forum and here but not working, all approaches stack in session problem.

**Comment by tananaev** [comment]
Please use the forum for questions.
