### ISSUE TITLE
[modern] show device last activity

### ISSUE THREAD

**Issue by meifi** [traccar/traccar-web#923]
It is posible to add the device last aktivity to list view in the modern ui for each device like the older ui ?

**Comment by tananaev** [comment]
What information? We already have location details screen.

**Comment by meifi** [comment]
if a device goes offline i have in the old ui a column "last activity" - ist es posible to get this information in the moden ui ? actually only the device name and status will be shown in modern ui.

**Comment by BenjaminK87** [comment]
i think the idea with the idle time for deepsleep devices is quite nice.  So you could set it to the same value of the device config Than you can see on the first view, if something is wrong, or we are just waiting for the wakeup.

**Comment by tananaev** [comment]
We already show last update time in the modern app.
