### ISSUE TITLE
[modern] Device Direction

### ISSUE THREAD

**Issue by davatem17** [traccar/traccar-web#924]
Hi
I have a problem, in the modern interface there is no longer the arrow that moves according to the movement of the devices, I want to implement that but I have problems because I can not directly modify the icons because it is only passed as a parameter the colors.

**Comment by glbatistabh** [comment]
Hello Anton! Is it possible to add to the vehicle icon the direction that it is moving, the same as it was in the old interface?

This information is excellent for when sending a screenshot to the user, he knows in which direction the vehicle was moving on a highway for example.

**Comment by tananaev** [comment]
The old solution doesn't work very well and it also doesn't look very nice. We're thinking of some other option.

**Comment by glbatistabh** [comment]
OK. Thanks for the feedback
