### ISSUE TITLE
[modern] Adding one Geofence add multiples

### ISSUE THREAD

**Issue by fareed38** [traccar/traccar-web#925]
When we add new geofence, it adds multiples. please fix this issue.

**Comment by tananaev** [comment]
Not enough information.

**Comment by fareed38** [comment]
![Capture](https://user-images.githubusercontent.com/25245034/161708383-8593d854-b616-4584-809d-d5c79c1a1e35.JPG)
Please see attached image, when I add a geofence first time it adds without any error but when we add geofence second time it do not redirect to geofence map and also ad one extra geofence with no name.

**Comment by tananaev** [comment]
Have you tried master branch?

**Comment by fareed38** [comment]
Yes I have tried master branch from https://github.com/traccar/traccar-web.git

**Comment by tananaev** [comment]
I believe this is already fixed.
