### ISSUE TITLE
Mobile App in React Native

### ISSUE THREAD

**Issue by mail2bishnoi** [traccar/traccar-web#929]
Is it a good idea to start the development of a Mobile App for Traccar in React Native?

**Comment by iceberg1369** [comment]
that would be awesome

**Comment by tananaev** [comment]
Personally I don't think it makes much sense. I think it's better to put time into making the web app that can work well on mobile screen.

**Comment by gpproton** [comment]
Ionic Capacitor can be use to make a good hybrid mobile app, it would take lot of stress out compared to the react native option.
I'm currently creating an app with vue.js and capacitor and it quite nice.

**Comment by tananaev** [comment]
We already have a React based app. Why invent something else?
