### ISSUE TITLE
l10n new translation:  "mapClustering": "Clustering"

### ISSUE THREAD

**Issue by castillo92** [traccar/traccar-web#931]
https://github.com/traccar/traccar-web/blob/644a598fb76d23a042a69a45806623ccb9fb79de/web/l10n/en.json#L276

What does it means? I ask to make the best translation in Transifex

**Comment by tananaev** [comment]
Map clustering means combining closeby markers on a map to avoid clutter.

**Comment by castillo92** [comment]
Thanks for the explanation Anton,

What do you think about change "Clustering" by "Markers clustering"

**Comment by tananaev** [comment]
I don't mind changing. Feel free to send a pull request.

**Comment by castillo92** [comment]
Created a pull request.
