### ISSUE TITLE
Slow map above 1500 devices.

### ISSUE THREAD

**Issue by michaelloliveira** [traccar/traccar-web#932]
I noticed that the modern interface with more than 1500 devices, the map takes a long time to load and when it loads the system is very slow.

The server has 8 vCPU configuration, 500GB NVME 64GB RAM.

The Database is mysql, both the database and the server are tuned to support this amount of I/O.

**Comment by michaelloliveira** [comment]
I tested it on Windows and MAC, wifi and 4G, also on a smartphone, believing it was the client side.

At a certain point in the video I scroll through the list of devices, just the map that crashes and the transition between screens
![Captura de Tela 2022-05-11 às 20 45 27](https://user-images.githubusercontent.com/600484/168099519-cc450638-9a1a-43e5-bb0a-ca71c6d52c7c.png)
.

**Comment by michaelloliveira** [comment]
I tested it on Windows and MAC, wifi and 4G, also on a smartphone, believing it was the client side.

At a certain point in the video I scroll through the list of devices, just the map that crashes and the transition between screens

https://user-images.githubusercontent.com/600484/168099665-08cb461f-a6a2-493c-92a5-9eed2ba01678.mp4

.

**Comment by tananaev** [comment]
Can you please answer all questions.

**Comment by michaelloliveira** [comment]
Sorry, yes! 

In the version developed in Extjs this problem did not occur.

Vehicle monitoring and recovery company..

**Comment by tananaev** [comment]
> Vehicle monitoring and recovery company..

Unfortunately it doesn't really explain why someone needs to see so many devices at the same time. Can you please elaborate.

**Comment by michaelloliveira** [comment]
We have a monitoring panel where we follow the vehicles on the map.

When a vehicle is stolen we activate the route live and guide our team and police to recover the vehicle.

But for that it is necessary that the map loads first, because we were not able to filter the vehicle on the map because it simply crashes.

**Comment by tananaev** [comment]
- Are you using a version from master?
- Is the problem the same with version 4.15?
- Does the issue still happen if you stop location updates?
- How often do your devices report data?

**Comment by michaelloliveira** [comment]
Are you using a version from master?
-Yes

Is the problem the same with version 4.15?
-Yes

Does the issue still happen if you stop location updates?
- Yes, even with all devices offline the problem occurs.

How often do your devices report data?
-Between 60s (ignition on) and 1800s (ignition off)

**Comment by tananaev** [comment]
Tested with 3000 devices and virtually no slowdown.

<img width="1599" alt="Screen Shot 2022-05-21 at 2 04 34 PM" src="https://user-images.githubusercontent.com/1161863/169668957-0c8f3ad3-694f-4950-ac09-5eefa43c028c.png">

Are you sure you have issues even when none of devices report any data?

**Comment by michaelloliveira** [comment]
Do you have a screen recording?

**Comment by tananaev** [comment]
https://user-images.githubusercontent.com/1161863/169701015-c283ec36-bdaa-4dc7-960f-3e60c3c24898.mov

**Comment by michaelloliveira** [comment]
Hey!

I've also been doing some tests.

Based on your answer, I disabled the websocket and loaded the position data beforehand (along with the devices) and the map did not crash.

However, when activating the websocket the map crashes.

Occurs in the real-time update of the data.

When the data (position and devices) are static, the system flows freely, but when there is data being received by the socket, I believe that the map markers update mechanism is overloaded.

**Comment by tananaev** [comment]
OK, it makes more sense then. We probably need to implement some throttling.

**Comment by michaelloliveira** [comment]
I've read about performance drops in redux with large scale updates, and it seems to be something related to redux and not the map.

I'll try to create a batch updater, I should probably solve it.

Thank you for your attention, I will inform you of my progress.

**Comment by tananaev** [comment]
Try something like this to batch position updates:

https://github.com/crashtimer/redux-batch-middleware

**Comment by tananaev** [comment]
We have implemented throttling. Please let me know if it works better now. By default it updates every 1500ms if frequent updates are detected. You can adjust parameters in `throttleMiddleware.js`.
