### ISSUE TITLE
Add option to switch between modern / legacy once user is logged in

### ISSUE THREAD

**Issue by OutrightHosting** [traccar/traccar-web#935]
It would be really useful to be able to switch between the two once signed in, map libre doesn't support different coordinate projections so we still have to use the legacy interface when using maps in EPSG:27700

**Comment by tananaev** [comment]
We plan to remove the switch completely fairly soon. It's a temporary state where you can use both. In the future you'll have to use one or the other.

**Comment by OutrightHosting** [comment]
Do you know of any way support alternative projections in the modern app. I know map libre doesn't support natively, we'd love to be able to just use the modern interface.

**Comment by tananaev** [comment]
I think support is on their roadmap, but I'm not sure if there's a simple short term solution. Maybe there's some tile server that can convert it for you?

**Comment by ildar170975** [comment]
Is it possible to switch to the legacy version for the web-access?
I am not able to find a real-time path for a device...

**Comment by OutrightHosting** [comment]
I saw on their road map it's under consideration, hopefully it will go ahead I think something like MapProxy will do it, a rather inelegant solution admittedly, unless anyone has any ideas on an alternative?
