### ISSUE TITLE
[Modern] - User not able to edit own details unless admin

### ISSUE THREAD

**Issue by OutrightHosting** [traccar/traccar-web#938]
**Describe the bug**
Users aren't able to access their own account information

**To Reproduce**
Create a user with any permissions apart from admin
Sign in as user and try to access account using button at bottom right of LH menu. 
Error - 'User access denied - SecurityException'

**Expected behavior**
Users should be able to access own information as per old traccar ui

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/72134131/169879852-6aba7c89-a080-44c4-b526-0d57e7aa7d78.png)

**Comment by tananaev** [comment]
This is actually not an issue with the web app. It's a change on the backend. Here's the fix https://github.com/traccar/traccar/commit/69d45b4429be70ce079b51200f6baefeb3873220.
