### ISSUE TITLE
Yandex map in modern interface

### ISSUE THREAD

**Issue by apnagaev** [traccar/traccar-web#939]
Hi! how I can use yandexmap in modern interface?
Thanks in advance!

**Comment by tananaev** [comment]
It's not supported. The problem is that Yandex maps are not using a standard projection, so we can't use them currently.

**Comment by OutrightHosting** [comment]
You can vote for the feature here as it's still under consideration:



[Vote](https://roadmap.maplibre.org/c/91-custom-coordinate-system-epsg-non-mercator-projection)

**Comment by tananaev** [comment]
Closing for now as it's not possible to support. We can revisit it later if projections become available.
