### ISSUE TITLE
Difference in speed at reports

### ISSUE THREAD

**Issue by Eradicator-69** [traccar/traccar-web#943]
**Describe the bug**
In Route report speed is correct, but in Diagram speed draws in knots. Servers default speed set to km/h, uses same km/h.

**To Reproduce**
1. Go to route report see speed in km/h
2. Go to diagram report see speed in knots

**Expected behavior**
Speed in km/h in all reports

**Screenshots**
![image](https://user-images.githubusercontent.com/84265852/170226202-3ef61b71-d0bd-4d16-a542-e6238abb0e85.png)
![image](https://user-images.githubusercontent.com/84265852/170226231-edb54310-1668-4780-8da3-f7b083e8baee.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04.4
 - Browser Yandex Browser 22.5.0.1814 (64-bit)
 - Traccar Version 5.0

**Comment by tananaev** [comment]
Fixed, thanks for the report.
