### ISSUE TITLE
Support in V5 for Bing Ordinance Survey maps for the UK

### ISSUE THREAD

**Issue by helfirex** [traccar/traccar-web#947]
Would it be possible to implement the addition of the Bing maps for UK Ordinance survey as one that can be selected from the menu. As this is the default mapping for all of the UK used by many people.

Here is an example

https://www.bing.com/maps?osid=4b3075da-c078-4ad8-87cb-1804ab3a063f&cp=53.134587~-1.288477&lvl=13&style=s&v=2&sV=2&form=S00027

It used to be possible to do in the old version by editing some files but after upgrade it no longer works

**Comment by tananaev** [comment]
Can you provide details on how you integrated it into the legacy app?

**Comment by helfirex** [comment]
I followed this post to set it up

https://www.traccar.org/forums/topic/bing-os-map-layer/

**Comment by OutrightHosting** [comment]
If you look on the bing maps documentation you will see this is only available for London so not very useful. 

[BingMaps Docs](https://docs.microsoft.com/en-us/bingmaps/rest-services/imagery/get-imagery-metadata)

![image](https://user-images.githubusercontent.com/72134131/170799064-b9c2ccbc-4c54-4f1d-a084-e62dfe33176c.png)

Support for the coordinate projection used on the Ordnance Survey Data Hub API (EPSG:27700 )is under consideration with Map Libre and you can vote for it using this link. [Vote Here](https://roadmap.maplibre.org/c/91-custom-coordinate-system-epsg-non-mercator-projection)

**Comment by helfirex** [comment]
When I followed the above method it was working with 1:25 & 1:50 os maps for the whole of the UK not just London

**Comment by OutrightHosting** [comment]
The current documentation shows this would no longer be possible.

**Comment by helfirex** [comment]
Just checked it still working in the legacy version of V5 so are you saying its only the modern UI that does not support it ?
