### ISSUE TITLE
[Modern] - Side menu remains open when device is selected

### ISSUE THREAD

**Issue by OutrightHosting** [traccar/traccar-web#948]
**Describe the bug**
In mobile viewpoint - After a device is selected in the side menu the centre info box appears but the side menu doesn't close.

**To Reproduce**
Select any device from side menu using mobile viewpoint

**Expected behavior**
Device is selected -> centre info box is shown -> side menu closed -> device centred on map

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/72134131/170829137-788117d5-2705-4189-9195-3d3e8ac1bc18.png)

Smartphone 
All mobile viewpoints

**Comment by tananaev** [comment]
It's not really a bug. Why do you expect it to close? What if you want to go through the list?

**Comment by OutrightHosting** [comment]
I would say the flow is counter intuitive compared to the the majority of mobile apps / websites when you select something you'd expect to see what is selected which also matches the desktop UI. Having the info box overlaid over the menu also makes it harder to use as if you catch this when scrolling it then tries to scroll the whole page instead of just the list, until you click on another device. 

By go through the list do you mean select each device, or just scroll to choose one?

https://user-images.githubusercontent.com/72134131/170829908-82baf195-30e7-4d07-87de-87ab1c87d5de.mp4

**Comment by tananaev** [comment]
> when you select something you'd expect to see what is selected

But you do see it.

What I'm saying is that you're focusing on one flow, but there's also another where you're not really interested in the map, but more in the details for several devices. That's why we don't close it. We're actually thinking of making it either configurable or double click to show the map.
