### ISSUE TITLE
New Developer

### ISSUE THREAD

**Issue by mohammadraufzahed** [traccar/traccar-web#949]
Hi, I'm a front-end developer, and I like to contribute to the modern website of this project. My team and I are working on this project, and we improved the project in so many ways. And I would like to append this improvement to this project and have some contributions.
Can I start with refactoring?

**Comment by tananaev** [comment]
Depends on what the changes are. Happy to discuss one by one.

**Comment by mohammadraufzahed** [comment]
One of the improvements was that I migrated to the parcel-bundler, and after that, I worked on lazy loading, Suspense, and Error boundaries, and the result was so good. I reduced the website size from 4-6MB to only 700kb and added the loading animation and error handler to each component, making it so better.

**Comment by tananaev** [comment]
OK, let's see some changes, but please make sure you submit separate pull requests for each separate thing.

**Comment by mohammadraufzahed** [comment]
Thanks, I will start with migrating to the parcel and after that, I will begin to add lazy loading and some other features

**Comment by mohammadraufzahed** [comment]
Thanks for the time you spent. I reached a point I think you will not understand what I want to do.
I will continue my development in a new repo that forked from this.

I wish the bests for you and your team.
