### ISSUE TITLE
add "remember" option in modern interface

### ISSUE THREAD

**Issue by jdrr2590** [traccar/traccar-web#950]
Greetings, please take into consideration adding the "remember" option that was on the home screen in previous versions. Thank you

**Comment by tananaev** [comment]
What option? Screenshot?

**Comment by jdrr2590** [comment]
<img width="233" alt="Traccar remember option" src="https://user-images.githubusercontent.com/106564289/171069842-f40db5fd-604a-4af2-95e4-f19cc086400c.PNG">

this option

**Comment by tananaev** [comment]
I see now. That's login screen though, not home.

**Comment by jdrr2590** [comment]
Yes, the login screen and now that I have fixed the "reset password" option is also not in the new interface

**Comment by tananaev** [comment]
Reset password is available in the modern app.

**Comment by jdrr2590** [comment]
Ok, let me check the documentation if I have to activate the option because it doesn't work for me

![image](https://user-images.githubusercontent.com/106564289/171070184-e56516d2-cecc-43e1-a14e-fbd924924495.png)
