### ISSUE TITLE
Modern: Sort by

### ISSUE THREAD

**Issue by kjetilpp** [traccar/traccar-web#952]
When using the Modern UI, i miss the option of sort by, ex last update, status or name, like in the classic UI.
![Screenshot 2022-05-31 132344](https://user-images.githubusercontent.com/5620578/171162462-6b799174-9fa5-4851-91b7-ae20d1056023.png)
We always need to sort by last updated, so personally i dont need any other sorting.

**Comment by tananaev** [comment]
> We always need to sort by last updated

Can you please explain the use case and alternatives you can think of.

**Comment by kjetilpp** [comment]
A use case can be 
- Find a car that has been the longest without a mission
- Find cars that are busy now.

Sees no good alternative solutions to this feature.  The one that is now in the old UI works perfectly fine.

**Comment by tananaev** [comment]
Your devices don't report any data if they're stationary?

**Comment by tananaev** [comment]
Implemented some basic filtering and sorting:
<img width="375" alt="Screen Shot 2022-06-04 at 9 13 40 AM" src="https://user-images.githubusercontent.com/1161863/172015415-2b965c03-5dde-4b57-add6-0e51eabbfbea.png">
