### ISSUE TITLE
No marker after build to prod

### ISSUE THREAD

**Issue by BIhab** [traccar/traccar-web#953]
**Describe the bug**
After build the app to prod, no marker shown on the map. - works fine on prod - 
I think the problem occurred when svg icons was moved from public to resources and it's related to the asset being static, not sure about that, not even sure if I'm not the only one facing that issue.

**To Reproduce**
1. Go to '/opt/traccar/traccar-web/modern'
2. Execute 'npm run build_release' 
3. Connect to traccar in prod not using npm start
4. No marker show in the map

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu ]
 - Browser [Firefox, Chrome]

**Smartphone (please complete the following information):**
On mobile too

Even on docker

**Comment by tananaev** [comment]
Have you checked browsers console for errors?

**Comment by tananaev** [comment]
Looks similar to this:

https://www.traccar.org/forums/topic/modern-build-from-source-and-deploy-y-is-not-defined/

**Comment by BIhab** [comment]
> Looks similar to this:
> 
> https://www.traccar.org/forums/topic/modern-build-from-source-and-deploy-y-is-not-defined/

I followed what will_ed suggested.
 I installed node v18.2.0 tried to build with it - just to try if it'll work before using V16.15- , nothing changed.
 Then Installed node v16.15.0 and tried to build with but also nothing changed.
 
 It's really strange to get the error only in production, in your side, you can build the app and get the marker shown in the map?

**Comment by tananaev** [comment]
Haven't tried release version yet.

**Comment by MaTyyyJ** [comment]
@BIhab @tananaev - `"production": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ],` in package.json fix this issue

**Comment by tananaev** [comment]
That's not really a good solution. We want to support older browser versions as well, when possible.

**Comment by MaTyyyJ** [comment]
@tananaev 
`    "production": [
	  "defaults",
	  "not firefox < 55",
	  "not chrome < 55",
	  "not safari < 11",
	  "not opera < 40",
	  "not IE <= 11",
	  "not op_mini all",
      "not dead"
    ],`
something like this? this fix this too

**Comment by tananaev** [comment]
Wonder if we can find where exactly it breaks. Is it some specific browser?

**Comment by MaTyyyJ** [comment]
@tananaev @BIhab - ES6
![image](https://user-images.githubusercontent.com/13423730/171281968-b5b1f232-da43-4843-b2f3-b2820bac2a95.png)

`    "production": [
	 "defaults",
     "not ie 11"
    ],`
fix this too

**Comment by BIhab** [comment]
> @tananaev @BIhab - ES6? ![image](https://user-images.githubusercontent.com/13423730/171281968-b5b1f232-da43-4843-b2f3-b2820bac2a95.png)
> 
> ` "production": [ "defaults", "not ie 11" ],` fix this too (from [maplibre/maplibre-gl-js#1011 (comment)](https://github.com/maplibre/maplibre-gl-js/issues/1011#issuecomment-1073112585) )

I have a question out of the subject but it will be really helpful to me and to any one who want to collaborate in this project, how did you know that the problem was due to the browser support? I past the last 4 day trying to debug it without success.

**Comment by MaTyyyJ** [comment]
@BIhab - just look into package.json
`  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },`

if it works on development and not on production it means there must be a difference somewhere

**Comment by BIhab** [comment]
> @BIhab - just look into package.json ` "browserslist": { "production": [ ">0.2%", "not dead", "not op_mini all" ], "development": [ "last 1 chrome version", "last 1 firefox version", "last 1 safari version" ] },`
> 
> if it works on development and not on production it means there must be a difference somewhere

Feels like I lack on experience, I'll learned from you thanks a lot

**Comment by tananaev** [comment]
Decided to go with this for now:
```json
    "production": [
      "defaults",
      "not ie 11"
    ],
```
