### ISSUE TITLE
Set expiration date to user

### ISSUE THREAD

**Issue by al3x1s** [traccar/traccar-web#957]
**Describe the bug**
if you set a user expiration date and then try to edit that user, you got following error
 
![image](https://user-images.githubusercontent.com/2840995/172503771-3d3254fe-4b45-48a1-afa9-a06684a322d9.png)

 
![image](https://user-images.githubusercontent.com/2840995/172503846-a5346b8f-ed41-4be4-bdbf-eba47a2df5cd.png)

**Comment by tananaev** [comment]
Fixed. Thanks for reporting the problem.
