### ISSUE TITLE
[Modern] Crash when heading >359

### ISSUE THREAD

**Issue by jonathandreyer** [traccar/traccar-web#958]
**Describe the bug**
At first, I would like congrats to you because the new UI looks really nice. I like the design and the experience. As ever, some points can be improved but the initial results are looking nice :-)

I have the feeling that something work wrongs with a heading value greater than 359, because that crash the UI (only when a device is selected). I have the feeling that it is probably a mistake and can be fixed by modulo the variable (in the UI).

It is also curious because when the value is 0, the direction marker is not visible. For my perception, it is strange to have the marker visible only when the value is greater than 1.

**Screenshots**
The error in Firefox can be seen below:
![Bug_heading](https://user-images.githubusercontent.com/4079443/172719798-a074fb17-5f2f-4e1e-8e69-150092340843.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.6 
 - Safari & Firefox
 - Traccar-web on master branch and traccar 5.0 release as backend

**Comment by tananaev** [comment]
Is heading >359 a valid value?

**Comment by tananaev** [comment]
But where do you get the value from? GPS shouldn't give it.

**Comment by jonathandreyer** [comment]
From my head :-) I test the traccar platform & UI with raw values (with Postman). I have not already selected the device and I will not use a device protocol. I will use the osmand protocol with data from a IoT platform.

**Comment by jonathandreyer** [comment]
I have tested negative values and the limitation is not there.
