### ISSUE TITLE
[Modern] Missing translation for "Show Map on Selection"

### ISSUE THREAD

**Issue by jonathandreyer** [traccar/traccar-web#959]
**Describe the bug**
When the language is French, the text "Show Map on Selection" is empty. 

**Screenshots**
Settings screen in French:
![Bug_Settings_FR](https://user-images.githubusercontent.com/4079443/172724094-3cb31b9d-c608-495c-a89e-c85cb73317b2.png)

Settings screen in English:
![Bug_Settings_ENG_OK](https://user-images.githubusercontent.com/4079443/172724137-c9c8d989-d283-4dbf-90e4-68f37b57f395.png)

In other languages, it seems to me that it is the same problem.

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - Safari & Firefox
 - Traccar-web on master branch and traccar 5.0 release as backend

**Comment by tananaev** [comment]
This is not a bug. Translations are updated during release.

If you want to help with translation itself:

https://www.transifex.com/traccar/traccar/

**Comment by jonathandreyer** [comment]
Hum, OK. I can help for the French translation, but I didn't full understand what is the effect of this field (feature). I have seen that it is related to the #948. Can you briefly explain what does that "fix"?

**Comment by tananaev** [comment]
With this enabled, sidebar closes automatically when you select a device.

**Comment by jonathandreyer** [comment]
Thanks for your reply. I have edited the French translate for the web application. I have a doubt with the translate "Search Device" because the French string is a bit too long.

**Comment by tananaev** [comment]
You can probably just cut it to "search" or something like that. It should be pretty obvious.
