### ISSUE TITLE
Public/View-only-Webinterface (no login required)

### ISSUE THREAD

**Issue by RNDadmin** [traccar/traccar-web#96]
Dear tananaev,

i'm a big fan of traccar ever since i found it and from that moment on, it ran on my homeserver to track my routes whenever i need it to! Thank you for that!

While doing that, i regularly want to share that information with friends, family, co-workers or an unknown group of people (e.g. Facebook). So far, that only works by giving them the login credentials, which creates the possibility that somebody deletes data or changes passwords or messes up something else. Also, for some people, choosing the right device and timeframe is an obstacle as well (e.g. not-so-tech-savvy-grandparents).

It would be cool to have the possibility of a webinterface, which shows a simplified version without the need of a login. 

Effectively, there would be only the map itself and most basic options. The data shown could be predefined: For example "all data from last 3 days" or "all data from one device" or "present location only", which was "made public" by having a checkbox for this option. There would be no options to alter the data in any way (view-only). In a way, very similar to embedded google-maps.

This would open the possiblity to embed this traccar-interface into other Webpages to enable live tracking without the need to "login - choose device - choose timeframe - load data - zoom".

Wether it's done through a special user account specified in the URL-address, an additional button besides "Login" and "Register" or a parrallel webinterface running on a different port is not important, i guess.

It's just an idea so far, taken from daily use of traccar. Comments are welcome!

**Comment by spacecabbie** [comment]
@tananaev 

Issue can be closed. Is implented
