### ISSUE TITLE
Blank screen Traccar manager after replay

### ISSUE THREAD

**Issue by Dakiboy** [traccar/traccar-web#961]
**Describe the bug**

when you replay history on iOS Traccar manager, after he finised and you press on forward, it will turn to a blank screen. 

**To Reproduce**
1. Go to replay button in modern new playback
2. Click on play
3. After its finished
4. Press forward
5. See blank screen
**Expected behavior**
Nothing
**Screenshots**

https://user-images.githubusercontent.com/107458422/173505119-47911b30-026f-4f35-9008-299bfd1d212b.MOV

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 15.5
 - traccar app
 - Latest

**Comment by tananaev** [comment]
I believe it's already fixed. Please try a version from master.
