### ISSUE TITLE
Bug: Wrong position when zoom in

### ISSUE THREAD

**Issue by BIhab** [traccar/traccar-web#964]
**Describe the bug**
Bug on position when you zoom in, described on the screenshot.
![Screenshot 2022-06-14 at 22-35-55 Traccar](https://user-images.githubusercontent.com/33871976/173699480-b89a157c-d36d-4be4-8040-c5582d4c83ef.png)
![Screenshot 2022-06-14 at 22-36-05 Traccar](https://user-images.githubusercontent.com/33871976/173699478-7b787519-501c-4b43-9548-b5806f9d2704.png)

**Comment by tananaev** [comment]
Not sure I understand the problem.

**Comment by BIhab** [comment]
> Not sure I understand the problem.

In the first screenshot, the vehicle -position- is on top of the road, when you zoom in the position didn't stay on top of the road, but move next to it.

**Comment by tananaev** [comment]
Please provide a screen recording.

**Comment by BIhab** [comment]
> Please provide a screen recording.


https://user-images.githubusercontent.com/33871976/173704029-e82e4561-e92f-4b2f-9cfb-7dfcad315eae.mp4

**Comment by tananaev** [comment]
This looks correct to me. You realize that as you zoom, the road line gets thinner, right? So it looks like it gets off the road, but it was always off the road. It just looked like it was on the road at a low zoom level. You can try to draw a geofence to confirm that.

**Comment by BIhab** [comment]
> This looks correct to me. You realize that as you zoom, the road line gets thinner, right? So it looks like it gets off the road, but it was always off the road. It just looked like it was on the road at a low zoom level. You can try to draw a geofence to confirm that.

The vehicle I choose, is a real one, and he's moving now IRL using this road, it's impossible that he's moving next to the road, I faced that issue in different vehicle, Could it be that from the beginning - before the zoom - the position was drawn wrong?

**Comment by tananaev** [comment]
What do you mean by wrong? GPS location can fluctuate, so it's pretty normal for it to be off road by a few meters.

**Comment by BIhab** [comment]
> What do you mean by wrong? GPS location can fluctuate, so it's pretty normal for it to be off road by a few meters.

I think that is the reason
