### ISSUE TITLE
Bug: Stop / Moving Event

### ISSUE THREAD

**Issue by BIhab** [traccar/traccar-web#965]
Hi Anton,
I hope you're fine, I was trying to get the last device motion and for how long it was - stopped or moving - and in order to achieve that I was planing to use the stop and moving event, get the last event reported and calculate the duration between the event time and the current time, the result should be per example: stopped for 3 hours , and I discovered a little bug.

**Describe the bug**
It seems like the last event is not always reported correctly, I checked for some devices, the speed is 0, and the parking duration is more than the default one, but in the report the last event was: device moving not device stopped.

**To Reproduce**
It's hard to reproduce but you could check for 2 or 3 existing devices, I'll join a video.

In the video you'll notice that the device is offline, the speed is 0, the last position sent is on 01:20, the current time is: 01:36 but the device still reported moving from 23:38.

Even if you show more info you'll get that the motion and ignition have a no value

id |   | 71582011
-- | -- | --
deviceId |   | 1809
protocol | Protocol | teltonika
serverTime | Server Time | 2022-06-17 01:20:35
deviceTime | Device Time | 2022-06-17 01:20:33
fixTime | Fix Time | 2022-06-17 01:20:33
outdated |   | No
valid | Valid | Yes
latitude | Latitude | 34.950860°
longitude | Longitude | -2.737650°
altitude | Altitude | 277
speed | Speed | 0.00 kn
course | Course | W
address | Address | Show Address
accuracy | Accuracy | 0
network |   |  
priority |   | 0
sat | Satellites | 12
event | Event | 240
ignition | Ignition | No
motion | Motion | No

https://user-images.githubusercontent.com/33871976/174201037-affbc6e2-b6f6-4099-8b9b-89f65e6abac3.mp4

**Comment by tananaev** [comment]
Please provide logs.

**Comment by BIhab** [comment]
> Please provide logs.

The video was recorder from: http://demo3.traccar.org/modern/login
I don't think I can get the logs

**Comment by tananaev** [comment]
Then at least attach a route report with the raw data showing the issue. Ideally JSON format.

**Comment by BIhab** [comment]
Here is a route, stop & event report data, you'll notice that the result are contradictory:

Stop Report:

**Comment by BIhab** [comment]
Here is a route, stop & event report data, you'll notice that the result are contradictory:

Stop Report:

**Comment by BIhab** [comment]
Here is a stop & event report data, you'll notice that the result are contradictory:

Stop Report:


0 |  
-- | --
deviceId | 2
deviceName | "Accent - 70607-A-13"
distance | 0
averageSpeed | 0
maxSpeed | 0
spentFuel | 0
startOdometer | 50963288
endOdometer | 50963288
startTime | "2022-06-16T23:04:41.000+00:00"
endTime | "2022-06-17T01:15:28.000+00:00"
positionId | 230320
latitude | 35.589835
longitude | -5.3432983
address | "Avenue Allal Al Fassi, MA"
duration | 7847000
engineHours | 0


Event Report:


  |  
-- | --
0 | Object { id: 40915, deviceId: 2, type: "deviceMoving", … }
id | 40915
attributes | Object {  }
deviceId | 2
type | "deviceMoving"
eventTime | "2022-06-16T22:20:01.000+00:00"
positionId | 229501
geofenceId | 0
maintenanceId | 0

**Comment by BIhab** [comment]
I'll join a route Report in xlsx
[1o-vPLZs.xlsx](https://github.com/traccar/traccar-web/files/8923765/1o-vPLZs.xlsx)

**Comment by tananaev** [comment]
Wait. Did it report some new data? The value can only change if something is reported. It won't change by itself.

**Comment by BIhab** [comment]
> Wait. Did it report some new data? The value can only change if something is reported. It won't change by itself.

Normally yes, you can check that from the excel route, I forget to say that the Reports I joined were from a second car in my own traccar server.

In the route excel you'll notice that from 2022-06-16 22:59:30, the speed was 0 and the lat,long didn't change even if the device still sending the new data

**Comment by BIhab** [comment]
Even now after about 2 hours from the time I took the last screen the issue still there. And it still report other event like device online.
![Screenshot_20220617-030832_Traccar Manager.jpg](https://user-images.githubusercontent.com/33871976/174209359-d626f440-bd42-42a3-9440-2654732492c3.jpg)
![Screenshot_20220617-030815_Traccar Manager.jpg](https://user-images.githubusercontent.com/33871976/174209415-6fee5e71-4605-4384-845f-27996fbee601.jpg)
![Screenshot_20220617-030753_Traccar Manager.jpg](https://user-images.githubusercontent.com/33871976/174209451-046c6fd9-9ec1-4ba6-9467-bd55daf2c4a1.jpg)

**Comment by tananaev** [comment]
Online status doesn't mean that it's sending any data. It could be just a heartbeat.

Let's focus on the data. In your excel report I don't see the sample that you talked about originally. Am I missing something?

**Comment by BIhab** [comment]
> Online status doesn't mean that it's sending any data. It could be just a heartbeat.
> 
> Let's focus on the data. In your excel report I don't see the sample that you talked about originally. Am I missing something?

I used the example from traccar demo 3 just to be sure that I'm not facing the issue only in my own hosted traccar - even if I'm using the official one -, all the other report was from a car in my own hosted traccar that was facing the same issue, I'll join new screenshots, just one question, is a more decent fixtime means new data received?

![Screenshot_20220617-041144_Traccar Manager.jpg](https://user-images.githubusercontent.com/33871976/174217764-ea841f26-a30c-49d4-974a-7b1a8894c076.jpg)![Screenshot_20220617-041154_Traccar Manager.jpg](https://user-images.githubusercontent.com/33871976/174217777-9b65380b-5be9-4ac9-a93f-115b9dc7b2fe.jpg)![Screenshot_20220617-041230_Traccar Manager.jpg](https://user-images.githubusercontent.com/33871976/174217779-65704b6c-8a6c-46b0-80e1-1d3872234518.jpg)![Screenshot_20220617-041240_Traccar Manager.jpg](https://user-images.githubusercontent.com/33871976/174217785-35f63df2-baf7-40fc-acdb-e2fbbe44df9d.jpg)

**Comment by tananaev** [comment]
Closing as no details provided.
