### ISSUE TITLE
Traccar Web keeps in the loading screen

### ISSUE THREAD

**Issue by MarcosRBL** [traccar/traccar-web#978]
Hello!
I followed the documentation for executing Traccar Web with IntelliJ IDEA, and when I start the application it keeps in the loading screen. I've opened the web console and see some errors, like these:

![Screenshot_1](https://user-images.githubusercontent.com/55623203/176794630-0c4ee7d5-6e7a-43df-85e4-e83f2f6101ec.png)

Any tips to solve this?
Thanks in advance!

**Comment by tananaev** [comment]
Looks like you haven't done `npm install`.
