### ISSUE TITLE
Reset password on modern app return to login screen from email link.

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar-web#979]
Build modern app with npm run build and place content from build folder into web root folder.
Select reset password, enter email, follow link on email received. It returns to login screen

**Comment by tananaev** [comment]
You need to adjust URL in the template and add `/reset-password`.

**Comment by tananaev** [comment]
I think other urls should work.

**Comment by tananaev** [comment]
Sure. Also please include console errors if there are any.
