### ISSUE TITLE
Mail test function

### ISSUE THREAD

**Issue by Kublach** [traccar/traccar-web#980]
I don't see in settings/users button to send test mail
![Screenshot_1](https://user-images.githubusercontent.com/76429200/177390030-cc9c3396-df85-4729-b8a5-77a6c5d01c4c.png)

**Comment by Kublach** [comment]
> You mean in the modern app? It has been moved to the notifications page.

Yes, in the modern app... I cannot find it at notifications page?

Can you please navigate me?
![Screenshot_2](https://user-images.githubusercontent.com/76429200/177391674-3116569d-3ae6-4c09-a379-85f017bc1fea.png)

**Comment by tananaev** [comment]
You need to click edit. But I also see that you're using an outdated version. We just added it, so you need to upgrade first.

**Comment by Kublach** [comment]
I just (few seconds ago) upgraded Traccar (Other - Manual upgrade)

![,](https://user-images.githubusercontent.com/76429200/177393313-a1270251-feed-484c-8469-eae7ed7da4f6.png)

**Comment by tananaev** [comment]
What version have you upgraded to? Have you cleared your browser cache?

**Comment by Kublach** [comment]
I downloaded this version: https://github.com/traccar/traccar/releases/download/v5.0/traccar-other-5.0.zip
How can I check my currently installed version?
I tried from two different PCs

**Comment by tananaev** [comment]
Version 5.0 doesn't have it. You need this:

https://www.traccar.org/forums/topic/traccar-51-preview/

**Comment by Kublach** [comment]
I upgraded to 5.1. I found it. Thank you...
