### ISSUE TITLE
Blank page when creating user... Traccar 5.1 Alpha

### ISSUE THREAD

**Issue by Kublach** [traccar/traccar-web#982]
**Describe the bug**
Blank page after clicking "+" on Settings - Users

**To Reproduce**
1. Go to Settings tab, on the left pane click Users
2. Click on '+'
3. I get blank page

**Expected behavior**
Getting menu for creating user

**Screenshots**
![ezgif-1-7acd7d3bc4](https://user-images.githubusercontent.com/76429200/177631023-ea5ce010-6149-4d58-8c7d-4fdac1787edb.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome (& Firefox & Edge)
 - Version 103

**Comment by tananaev** [comment]
Fixed. Thanks for reporting.
