### ISSUE TITLE
Notifications - Not restricted to linked devices

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar-web#986]
Notifications sent to users from all devices, not only from devices linked to the user account.

**To Reproduce**
1. Create "Geofence Enter" or "Ignition On" notification and set channel to mail
2. Link Notification to specific user. Use a user with a small amount of devices linked to his account.

The user receive the notifications from devices that are not linked to his account.

**Comment by tananaev** [comment]
Can you please provide a specific example how to reproduce it from scratch. I've tried before and wasn't able to.

**Comment by tananaev** [comment]
Maybe I misunderstand something, but your steps to reproduce sounds like what's expected. If you link a group to a user, he should receive notifications from that group.

Can you please describe very specific example. Let's say we have:
- user 1
- user 2
- group 1
- group 2
- device 1
- device 2
- notification

What is linked to want?

**Comment by tananaev** [comment]
Just tested the exact scenario and still not able to reproduce. Are you sure you tried this with a clean server? Or you're just guessing?

Also very suspicion that it started after changing the web app. Web app has nothing to do with notifications. They are sent directly from the backend, especially emails.

Please test and make sure to test and provide details about user permissions, like admin non admin etc.

**Comment by tananaev** [comment]
Another option if you can send me your database dump and tell what users have this problem, this should help.

**Comment by FerLSanchez** [comment]
To reproduce in my environment:

Users affected: 2, 3, 4, 5 (real userid in my database)

Device that raised the issue: 3
Geofence that raised the issue: 16

User-Device relationships:
2	3
3	4
5	6
6	8
4	9

Notifications:
1	geofenceExit	{}	0		mail
3	deviceOnline	{}	0		mail,web
4	ignitionOn	{}	0		mail
5	deviceMoving	{}	0		mail
6	alarm	{"alarms":"powerCut,vibration"}	0		mail
8	deviceOnline	{}	0		

User notifications relationship:
2	1
3	1
3	3
4	3
4	1
2	4
2	5
2	6
5	3
5	1
2	8

Device notifications relationship:
3	1
4	1
3	3
3	4
3	5
3	6
6	3
6	1

User geofence relationship:
3	1
3	4
5	9
5	10
5	11
5	13
2	6
2	12
5	14
2	15
2	16
2	17
2	19
4	20
4	1

Device geofence relationship:
3	1
4	4
4	1
3	6
6	9
6	10
3	12
6	13
6	14
3	15
3	16
3	17
9	1
9	20
3	19

Then, when device 3 exited geofence 16, user 2,3,4,5 where notified when until now, only user 2 was the one receiving it as it is the only one linked to the device.
Hope this help and thank you very much.

**Comment by tananaev** [comment]
Is it possible to provide a database dump for that setup?

**Comment by tananaev** [comment]
You can send it to me over email. Address in the profile. Obviously I won't share any private info. You can also probably clean up some unrelated stuff before sending.

**Comment by FerLSanchez** [comment]
Done, Anton, thank you very much. Hope it helps!
Don't hesitate to count on me if you need anything else.

**Comment by tananaev** [comment]
I think I'm starting to understand the problem. It happens when you reuse same notification object for different users that have completely different devices.

@joystickjockey can you confirm if you have similar setup when you reuse notifications between users?

**Comment by FerLSanchez** [comment]
Absolutely, it is my case, the thing I understood as "notification definition" that later is configured/associated with users and devices, it is the same one for everything. But the way it worked until 5.1 was it took into account device-user relationship. 🤷

**Comment by tananaev** [comment]
I think it's finally fixed https://github.com/traccar/traccar/commit/3f46f759c24746ddd2b8cd05cfc6cb99d5f7fd48. Please test if possible.

**Comment by FerLSanchez** [comment]
Tell me how (I'm running it as a Docker) and I will be more then glad! Thank you!

**Comment by tananaev** [comment]
I don't have a docker image, but you can get latest files from here:

https://traccar.nyc3.digitaloceanspaces.com/builds/traccar-linux-arm-preview.zip

You really just need the JAR file.

**Comment by FerLSanchez** [comment]
Thank you very much, I will try it shortly and come back with feedback.
In any case, do you plan to distribute it as 5.1.1, maybe?
Thanks again.

**Comment by Kresnik003** [comment]
Hello,

I'm on raspberry and have the same issue. I just changed the jar file but also need to add new changelog on schema folder.

But now, i'm getting the following WARN and don't know where to check:

2022-07-13 20:52:47  WARN: Set property error - NullPointerException (Device:59 < ... < QueryBuilder:363 < *:449 < DatabaseStorage:71 < ...)
2022-07-13 21:07:47  WARN: Set property error - NullPointerException (Device:59 < ... < QueryBuilder:363 < *:449 < DatabaseStorage:71 < ...)
2022-07-13 21:22:47  WARN: Set property error - NullPointerException (Device:59 < ... < QueryBuilder:363 < *:449 < DatabaseStorage:71 < ...)
2022-07-13 21:37:47  WARN: Set property error - NullPointerException (Device:59 < ... < QueryBuilder:363 < *:449 < DatabaseStorage:71 < ...)


AND

2022-07-13 22:26:36  WARN: Set property error - NullPointerException (Device:59 < ... < QueryBuilder:363 < *:449 < DatabaseStorage:71 < ...)
2022-07-13 22:27:27  WARN: Set property error - NullPointerException (Device:59 < ... < QueryBuilder:363 < *:449 < DatabaseStorage:71 < ...)
2022-07-13 22:29:17  WARN: Set property error - NullPointerException (Device:59 < ... < QueryBuilder:363 < *:449 < DatabaseStorage:71 < ...)
2022-07-13 22:31:07  WARN: Set property error - NullPointerException (Device:59 < ... < QueryBuilder:363 < *:449 < DatabaseStorage:71 < ...)


Thanks in advance!!!

**Comment by tananaev** [comment]
Please create a separate ticket.

**Comment by tananaev** [comment]
The `NullPointerException` issue should be fixed now.

**Comment by oluwatobi-roie** [comment]
HI Anton, the notification issue seems not to be fixed in 5.2
I had earlier raised this issue but i seem to be able to reproduce it now. 

To reproduce:
1: from admin account create 2 user account(User A & User B)
2: From admin account create 4 vehicles,  A,B,C,D
3: Assign Vehicle A to user A and Vehicle B to user B
4: From admin account create Notification (Igniton On, Traccar/mail, check All device)
5: Sign into User A account and create notification as (Igniton On, Traccar/mail, check All device) Or assign notification from admin account to the user.
6: Turn on Ignition for Vehicle C and watch user A and B receive same notification despite not having the vehicle on their list.
