### ISSUE TITLE
Calculated Attributes Encode

### ISSUE THREAD

**Issue by juanpablo-garcia** [traccar/traccar-web#987]
When you have some special charaters in the computed attribute for example " or &, when the attribute is loaded it is decoded as &amp;#39; for " and &amp; for & 
![image](https://user-images.githubusercontent.com/63308600/178173042-2d10068c-7397-49f0-878c-ea093b5658f0.png)

When you try de test the formula it shows an error

![image](https://user-images.githubusercontent.com/63308600/178173157-2f499b10-e039-492d-abde-924297c6a57f.png)

The computed were fine in the previous version, and it is working as expected, the problem is only testing on modern version,

**Comment by tananaev** [comment]
You have to disable sanitization if you're using the modern app:
```xml
<entry key='web.sanitize'>false</entry>
```

**Comment by juanpablo-garcia** [comment]
Thanks, you are the best
