### ISSUE TITLE
Device Group Issue

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar-web#988]
On fresh copy of latest master.
1. Create 4 groups and set group relationship.
   name:groupid
   1:null
   2:1
   3:2
   4:3
2. Add new device to server
3. Link new device to group 4
4. Create new user, user 1
5. Link user 1 to group 1
6. Login as user 1

No devices displayed.....

7. Unlink device from group 4
8. Link device to group 3
9. Login as user 1 again

Device is displayed.

**Comment by tananaev** [comment]
Are you really using 4 levels of groups? We currently limit to 3, so this is expected.

**Comment by tananaev** [comment]
The reason I'm asking is because if there's a real need we can implement it. I was considering making it configurable. More levels means slower SQL requests, so I didn't want to go too deep. If there's a real need, we can make it configurable potentially.
