### ISSUE TITLE
Traccar Server Webpage Breaks When Zoom is 0

### ISSUE THREAD

**Issue by andyvuj24** [traccar/traccar-web#989]
**Describe the bug**
When server's zoom setting is set to 0, this breaks the react app and causes the page to go "blank" and unable to use. The page initially loads fine, displaying the navigation bar, the devices, the map, etc., but after about 1 second the page "updates" the map and it errors out.

```html
<div id="root" class="root"></div>
```
All contents of the app are removed and the user is unable to do anything and must reload the page.

Setting the zoom to a number > 0, fixes the issue.

**To Reproduce**
1. Go to 'https://{server}:{port}/modern/settings/server'
2. Within the 'Preferences' find the 'Zoom' setting
3. Set 'Zoom' to 0
4. Save Settings
5. Go to start page at 'https://{server}:{port}/modern'
6. See blank page after error occurs

**Expected behavior**
Zoom is 0, so the map view should be fully zoomed out, without error.

**Screenshots**
Broken page
![image](https://user-images.githubusercontent.com/30358400/179356628-31a608fa-d1e9-47ce-a53d-2ccf5fbf4a3b.png)

Console Errors
![image](https://user-images.githubusercontent.com/30358400/179356326-e53237dc-e682-4bce-afe9-a115f5c45001.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 101

**Additional context**
When zoom is set to 0, Traccar Manager also breaks on mobile (Android). Displays a blank white page once error occurs as well. Setting the zoom to a number > 0, fixes the issue.

**Comment by tananaev** [comment]
What version of Traccar?

**Comment by andyvuj24** [comment]
`https://{server}:{port}/api/server` says `Version 5.0`

**Comment by tananaev** [comment]
This issue has already been fixed. Please upgrade.

**Comment by tananaev** [comment]
Next time before filing a bug please make sure you test it on the latest release first.

**Comment by andyvuj24** [comment]
My apologies! Thank you.
