### ISSUE TITLE
Modern Page fails to load caused by invalid coordinate.

### ISSUE THREAD

**Issue by Itheras** [traccar/traccar-web#990]
Modern Page will fail to load if an invalid coordinate is sent by a device. Legacy page is tolerant to the fault and will still load. 

Modern Page Error Below caused by a device sending 

Latitude | 1144.018740°
Longitude | -255.971002°
```
Error: Invalid LngLat latitude value: must be between -90 and 90
    at new Hc (lng_lat.ts:42:19)
    at Hc.convert (lng_lat.ts:140:20)
    at Uc.extend (lng_lat_bounds.ts:89:47)
    at MapDefaultCamera.js:30:70
    at Array.reduce (<anonymous>)
    at MapDefaultCamera.js:30:38
    at zl (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Zn (react-dom.production.min.js:122:325)
    at Rl (react-dom.production.min.js:261:308)
```
Can we make modern version tolerant to this type or error or a method to filter this type of msg.

Attached offending msg in the log. Observation usually Atrack devices ID is their imei this device id is longer than usual.

[Atrack_720857707413766144.txt](https://github.com/traccar/traccar-web/files/9133161/Atrack_720857707413766144.txt)

**Comment by Itheras** [comment]
Update . Legacy can also fail to load.

**Comment by tananaev** [comment]
Implemented a fix here https://github.com/traccar/traccar/commit/35070c85e26fe75e73315506b8cae3360f79d12e.
