### ISSUE TITLE
feature request: support Traccar in server subdirectory

### ISSUE THREAD

**Issue by pkoevesdi** [traccar/traccar-web#995]
**Is your feature request related to a problem? Please describe.**
At the moment it is not recommended to operate a traccar server inside a subdirectory, see https://www.traccar.org/secure-connection. I can confirm: modern web gui doesn't work. This makes it impossible to have it on a server with other services if you cannot make any additional subdomain. In my case, the whole server is under one subdomain with dynamic DNS. I cannot make more subdomains with my DynDNS service, and even if I could, my router cannot update more than one. There are probably more use cases, as this topic is discussed several times in the community.

**Describe the solution you'd like**
Some config setting to give the gui the url path under which it is reached publicly. Or even simpler: make all references inside the gui relative, so that it doesn't matter where it resides.

**Comment by tananaev** [comment]
It's not a bug. You have to recompile the app if you want to use different path.

**Comment by pkoevesdi** [comment]
Of course it's not a bug,  see headline, it's a feature request. And even if it was a bug: "change it yourself" is no valid answer in my opinion. Any of the developers willing to better take care of this request? I already was willing to chip in, but if nobody is interested in sharing, instead, many people are forced to make the same work over and over again, it's simply dissipated effort. If I see no chance that it gets pulled, I will not offer my solution, in case I make one. Too sad, this answer.

**Comment by pkoevesdi** [comment]
"completed" is especially wrong. it is simply not, because it doesn't work.

**Comment by tananaev** [comment]
I'm not sure what exactly you're requesting. It's not possible to make it a configuration because to change path the code needs to be recompiled.

**Comment by pkoevesdi** [comment]
As suggested in opening post: I'm sure the code also can be changed and recompiled to read and use any configuration setting. It's called a "variable" instead of hard coded. 😁
I admit, i say that without looking at the code yet. I just cannot imagine, that this should be impossible. Maybe it could help to elaborate more on the problems you see? As said, I'm willing to help, and I could use some hints in advance on stumbling blocks or caveats

**Comment by tananaev** [comment]
Then it should be a feature request for React Scripts or Webpack. I'm not exactly sure where it becomes hard-coded, but it's not in Traccar code. Feel free to investigate if you're interested.

**Comment by pkoevesdi** [comment]
Doesn't matter, which library or whatever gets used, it's a feature request for traccar. It's up to the developers to either pass it on to their library makers, workaround their imperfections or change the library. But no way this feature request is wrong here, it's is clearly a requested feature by users of traccar. It's not their duty to look inside any code. The feature request is exactly about that: make it work for users without changing the program, even further not changing anything somewhere else.

**Comment by tananaev** [comment]
As I said, it is currently impossible to implement, as far as I know. If I'm wrong and you know a way, please provide technical details and I'm happy to reopen this request.
