### ISSUE TITLE
Notification Issues

### ISSUE THREAD

**Issue by oluwatobi-roie** [traccar/traccar-web#996]
1: Notification not restricted to linked devices issue still exist after upgrade to 5.2. Below is how i was able to reproduce this

I had earlier raised this issue but i seem to be able to reproduce it now.

To reproduce:
1: from admin account create 2 user account(User A & User B)
2: From admin account create 4 vehicles, A,B,C,D
3: Assign Vehicle A to user A and Vehicle B to user B
4: From admin account create Notification (Igniton On, Traccar/mail, check All device)
5: Sign into User A account and create notification as (Igniton On, Traccar/mail, check All device) Or assign notification from admin account to the user.
6: Turn on Ignition for Vehicle C and watch user A and B receive same notification despite not having the vehicle on their list.

Issue 2:
user deleted notification affects every other user. 
To reproduce:
Create notification in User A
Link notification to User B from admin login
Delete notification at user B
Issue: Notification at user A will be deleted also. 

once a notification has been linked to a user, it should be independently controlled by the user. further modification or deleting of the notification in the user account should not affect other user sharing the same notification. 

Thanks

**Comment by tananaev** [comment]
Next time please create separate tickets for different issues. Actually the "issue 2" is not a bug and it's expected behavior. When you share objects, removing it obviously removes it from everyone.

**Comment by tananaev** [comment]
I'm not able to reproduce the issue with the exact steps you provided.
