### ISSUE TITLE
Floating info panel

### ISSUE THREAD

**Issue by lzkill** [traccar/traccar-web#997]
The modern interface would feel a lot more intuitive if the device info panel was moveable. I spot myself trying to move the panel all the time, it's intuitive to try it.

**Comment by tananaev** [comment]
We can probably use something like `react-draggable`.

**Comment by lzkill** [comment]
@brunocaldara could you help here?

**Comment by lzkill** [comment]
Closed in 114c78dff8fbfdc19444c88fea45188012065a3a
