### ISSUE TITLE
[MODERN] Show routes for multiple devices at the same time - Partity to Legacy UI

### ISSUE THREAD

**Issue by MikaVilpo** [traccar/traccar-web#998]
**Is your feature request related to a problem? Please describe.**
I need to have way to visualize routes travelled by multiple devices at the same time. This is for planning further actions in search and rescue operations and to evaluate performance of the groups. 

**Describe the solution you'd like**
In legacy UI, I can draw multiple devices in the same time at the reports section. I would like to have same feature in modern UI to bring those solution in more parity. 

**Describe alternatives you've considered**
Currently I'm showing this kind of reports in legacy ui. 
Other solution is to export all tracks in KML files and combine them in other software. Requires manual work and it is not usable in dynamic situations.

**Comment by tananaev** [comment]
Did you use route report for it before?
