### ISSUE TITLE
Creating an optimized production build... Failed to compile.  Module not found: Error: Can't resolve './common/components/LocalizationProvider' in 'Z:\git\traccar\traccar-web\modern\src'

### ISSUE THREAD

**Issue by ImagineBijaya** [traccar/traccar-web#999]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tananaev** [comment]
This is not a bug.
